// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.

mod common;

use common::*;

// ---- (preamble) --------------------------------------------------------------------------------

#[tokio::test]
async fn hello_then_open_file() {
    let dir = tempfile::tempdir().unwrap();
    let file_path = dir.path().join("hello.rs");
    std::fs::write(&file_path, "fn main() {\n    println!(\"hi\");\n}\n").unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let mut ws = Ws::connect(&server).await;

    // Activate the workspace (replaces the old client/hello handshake — auth is now in the
    // WebSocket query string).
    let activated: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(activated.workspace.name, "test-proj");
    assert_eq!(activated.workspace.paths.len(), 1);
    // The instance stamp rides the activation result (clients use it for restart detection
    // instead of reading the discovery file). A running server has a non-zero start time.
    assert_ne!(
        activated.server_started_at, 0,
        "workspace/activate reports the server's instance start stamp over the wire"
    );

    // Open the file.
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("hello.rs".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert!(open.buffer_id > 0);
    assert_eq!(open.language.as_deref(), Some("rust"));
    assert_eq!(open.saved_revision, open.revision);
    assert_eq!(open.revision, 0);
    assert!(open.line_count >= 3);
    assert!(open.byte_count > 0);
    // First open: no prior cursor or scroll for this (client, buffer).
    assert_eq!(open.cursor, CursorState::default());
    assert!(open.scroll.is_none());

    // Re-opening returns the same buffer id (deduping by canonical path).
    let open2: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("hello.rs".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(open2.buffer_id, open.buffer_id);

    drop(server);
}

/// `workspace/delete` refuses to delete a workspace that's any client's active workspace — the
/// rug-pull guard, which runs before any on-disk config is touched.
#[tokio::test]
async fn workspace_delete_refuses_the_active_workspace() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test_multi(vec![
        ("p1".into(), vec![dir.path().to_path_buf()]),
        ("p2".into(), vec![dir.path().to_path_buf()]),
    ])
    .await
    .unwrap();

    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p1".into(),
            open_last: false,
        },
    )
    .await;

    // Deleting the workspace we're sitting in is refused, with a message that says why.
    let msg = send_request_expect_err::<WorkspaceDelete>(
        &mut ws,
        &WorkspaceDeleteParams { name: "p1".into() },
    )
    .await;
    assert!(
        msg.contains("active"),
        "refusal should explain the workspace is active, got {msg:?}"
    );

    drop(server);
}

#[tokio::test]
async fn buffer_open_restores_cursor_and_scroll() {
    // Multi-line file so we can scroll meaningfully.
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    let mut content = String::new();
    for i in 0..30 {
        content.push_str(&format!("line {i}\n"));
    }
    std::fs::write(&path, &content).unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;

    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: view_of(buffer_id),
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    let viewport_id = sub.viewport_id;

    // Move the cursor and scroll the viewport so the (client, buffer) state diverges from defaults.
    let cursor_target = LogicalPosition { line: 12, col: 3 };
    let _: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: cursor_target,
            anchor: cursor_target,
        },
    )
    .await;
    let _ = window_from_row(&mut ws, viewport_id, 8, 10).await;

    // Reopen the same path (file-browser navigation pattern). The server should report the
    // prior cursor and scroll so the client can restore the view.
    let reopen: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen.buffer_id, buffer_id);
    assert_eq!(reopen.cursor.position, cursor_target);
    let scroll = reopen.scroll.expect("scroll restored on reopen");
    assert_eq!(scroll.line, 8);

    drop(server);
}

/// Scrolling via `view/window` (the path every wheel/page scroll takes, as the client refetches
/// near the loaded edge) must be restored on reopen, not only the position a subscribe opened at.
/// Regression: the scroll fetch updated the viewport but forgot the restore map, so switching back
/// to a buffer jumped to where it was first opened.
#[tokio::test]
async fn buffer_open_restores_scroll_from_a_window_request() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    let mut content = String::new();
    for i in 0..60 {
        content.push_str(&format!("line {i}\n"));
    }
    std::fs::write(&path, &content).unwrap();

    let server = spawn_for_test("scroll-row-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "scroll-row-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: view_of(buffer_id),
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;

    // Scroll by row (no wrap → row 20 of the one element is line 20).
    let _ = window_from_row(&mut ws, sub.viewport_id, 20, 10).await;

    let reopen: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen.buffer_id, buffer_id);
    let scroll = reopen.scroll.expect("scroll restored on reopen");
    assert_eq!(
        scroll.line, 20,
        "a row-based scroll is restored on reopen, not just logical-line scrolls"
    );

    drop(server);
}

#[tokio::test]
async fn buffer_open_jump_drops_saved_scroll() {
    // A `jump_to` open (grep `<`/`>`, goto-definition, nav history) moves the cursor, so the
    // scroll recorded before the jump is stale and must NOT be restored — the server returns
    // `scroll: None` so the client frames the jumped cursor instead of the old viewport. Without
    // this the editor "sometimes doesn't scroll" to the match: the subscribe restores the prior
    // scroll, the match falls outside the loaded window, and the reveal silently bails.
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    let mut content = String::new();
    for i in 0..30 {
        content.push_str(&format!("line {i}\n"));
    }
    std::fs::write(&path, &content).unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;

    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: view_of(buffer_id),
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    // Record a non-default scroll for this (client, view).
    let _ = window_from_row(&mut ws, sub.viewport_id, 8, 10).await;

    // Reopen the same buffer with a jump (the grep-navigate pattern): the cursor lands on the
    // jump target, and the stale scroll is dropped.
    let jump = LogicalPosition { line: 20, col: 0 };
    let reopen: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: Some(jump),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen.buffer_id, buffer_id);
    assert_eq!(reopen.cursor.position, jump);
    assert!(
        reopen.scroll.is_none(),
        "a jump open must drop the saved scroll, got {:?}",
        reopen.scroll
    );

    drop(server);
}

#[tokio::test]
async fn buffer_open_isolates_scroll_per_client() {
    // Two clients on the same buffer should see independent restored scroll positions.
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    let mut content = String::new();
    for i in 0..30 {
        content.push_str(&format!("line {i}\n"));
    }
    std::fs::write(&path, &content).unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let connect = || async {
        let mut ws = Ws::connect(&server).await;
        let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
            &mut ws,
            &WorkspaceActivateParams {
                worktrees: None,
                name: "test-proj".into(),
                open_last: false,
            },
        )
        .await;
        let open: ViewOpenResult = send_request::<ViewOpen>(
            &mut ws,
            &ViewOpenParams {
                transient: None,
                path_index: Some(0),
                relative_path: Some("a.txt".into()),
                language: None,
                create_if_missing: false,
                jump_to: None,
                ..Default::default()
            },
        )
        .await;
        let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
            &mut ws,
            &ViewportSubscribeParams {
                view_id: open.view_id,
                cols: 80,
                rows: 10,
                overscan_rows: 0,
                scroll: ScrollPosition {
                    element: 0,
                    line: 0,
                    sub_row: 0.0,
                },
                focus: None,
                wrap: WrapMode::None,
                continuation_marker_width: 0,
                tab_width: 4,
                diff_view: false,
            },
        )
        .await;
        (ws, open.buffer_id, sub.viewport_id)
    };

    let (mut ws_a, buf_a, vp_a) = connect().await;
    let (mut ws_b, buf_b, vp_b) = connect().await;
    assert_eq!(buf_a, buf_b, "shared buffer, deduped by canonical path");

    let _ = window_from_row(&mut ws_a, vp_a, 5, 10).await;
    let _ = window_from_row(&mut ws_b, vp_b, 17, 10).await;

    let reopen_a: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws_a,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let reopen_b: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws_b,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen_a.scroll.expect("a").line, 5);
    assert_eq!(reopen_b.scroll.expect("b").line, 17);

    drop(server);
}

/// A browser page on another site can't authenticate a WebSocket: its honest `Origin` header isn't
/// our loopback origin, so the upgrade is refused. This is the cross-site / DNS-rebinding defense on
/// the WS path (the native TUI sends no `Origin`, which is allowed — see `connects_with_no_origin`).
#[tokio::test]
async fn ws_rejects_foreign_origin() {
    use tokio_tungstenite::tungstenite::client::IntoClientRequest;

    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let mut req = server.ws_url().into_client_request().unwrap();
    req.headers_mut()
        .insert("origin", "http://evil.com".parse().unwrap());
    let result = tokio_tungstenite::connect_async(req).await;
    assert!(
        result.is_err(),
        "connect should fail with a cross-site Origin, got Ok"
    );
}

/// The page served from our own loopback origin *can* connect: its `Origin` matches, so a browser
/// client served by the daemon authenticates fine.
#[tokio::test]
async fn ws_accepts_loopback_origin() {
    use tokio_tungstenite::tungstenite::client::IntoClientRequest;

    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let mut req = server.ws_url().into_client_request().unwrap();
    req.headers_mut().insert(
        "origin",
        format!("http://127.0.0.1:{}", server.port).parse().unwrap(),
    );
    let result = tokio_tungstenite::connect_async(req).await;
    assert!(
        result.is_ok(),
        "connect should succeed from our own loopback origin"
    );
}

/// The native TUI is not a browser and sends no `Origin`; that must be accepted (every other test
/// connects this way via `ws_url`, but pin it explicitly since it's the load-bearing case).
#[tokio::test]
async fn connects_with_no_origin() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let result = tokio_tungstenite::connect_async(server.ws_url()).await;
    assert!(result.is_ok(), "TUI (no Origin) should connect");
}

/// A client announcing a different build version is rejected at the handshake: this is the
/// stale-daemon guard (a freshly-installed binary must not talk to an old daemon on a drifted wire
/// format). The matching-version case is covered by every other test, which connects via `ws_url`.
#[tokio::test]
async fn ws_rejects_version_mismatch() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let url = format!("ws://127.0.0.1:{}/?version=9.9.9-stale", server.port);
    let result = tokio_tungstenite::connect_async(url).await;
    assert!(
        result.is_err(),
        "connect should fail when the client version differs from the server"
    );
}

/// A client that announces no version at all is allowed through — the gate only fires on a
/// *declared* mismatch, so the web dev shell and ad-hoc tooling keep working.
#[tokio::test]
async fn ws_accepts_absent_version() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let url = format!("ws://127.0.0.1:{}/", server.port);
    let result = tokio_tungstenite::connect_async(url).await;
    assert!(
        result.is_ok(),
        "connect should succeed when no client_version is sent"
    );
}

#[tokio::test]
async fn rejects_path_outside_workspace() {
    let dir = tempfile::tempdir().unwrap();
    // File is in /tmp directly, not in the workspace's path.
    let outside = std::env::temp_dir().join("aether-outside-test.txt");
    std::fs::write(&outside, "outside").unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;

    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    // Try to open by providing relative_path that escapes upward.
    let req = Request {
        jsonrpc: JsonRpc,
        id: 2,
        method: ViewOpen::NAME.into(),
        params: Some(
            serde_json::to_value(ViewOpenParams {
                transient: None,
                path_index: Some(0),
                relative_path: Some("../aether-outside-test.txt".into()),
                language: None,
                create_if_missing: false,
                jump_to: None,
                ..Default::default()
            })
            .unwrap(),
        ),
    };
    ws.send(Message::text(serde_json::to_string(&req).unwrap()))
        .await
        .unwrap();

    let text = next_text(&mut ws).await;
    let v: Value = serde_json::from_str(&text).unwrap();
    assert_eq!(v["error"]["code"], -32010, "expected INVALID_PATH");

    std::fs::remove_file(&outside).ok();
}

#[tokio::test]
async fn viewport_subscribe_renders_window() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    // 5 short lines.
    std::fs::write(&path, "alpha\nbeta\ngamma\ndelta\nepsilon\n").unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;

    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;

    // Subscribe to a viewport showing the full file.
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: open.view_id,
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::Soft,

            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;

    let (first, last) = loaded_lines(&sub.window);
    assert_eq!(first, 0);
    // 5 newlines in our content => ropey reports 6 lines (final empty).
    assert!(last >= 5);

    let line0 = &sub.window.root.lines()[0];
    assert_eq!(line0.logical_line, 0);
    assert_eq!(line0.visual_rows.len(), 1);
    assert_eq!(line0.visual_rows[0].segments[0].text, "alpha");
    let line2 = &sub.window.root.lines()[2];
    assert_eq!(line2.visual_rows[0].segments[0].text, "gamma");
}

#[tokio::test]
async fn viewport_subscribe_wraps_long_line() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("long.txt");
    std::fs::write(&path, "the quick brown fox jumps over the lazy dog\n").unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("long.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;

    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: open.view_id,
            cols: 20,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::Soft,

            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;

    // The single logical line should wrap to multiple visual rows.
    let line0 = &sub.window.root.lines()[0];
    assert_eq!(line0.logical_line, 0);
    assert!(
        line0.visual_rows.len() >= 2,
        "expected long line to wrap, got {} rows",
        line0.visual_rows.len()
    );

    // And the joined visual rows reconstruct the original text (mod stripped break-whitespace).
    let joined: String = line0
        .visual_rows
        .iter()
        .map(|r| {
            r.segments
                .iter()
                .map(|s| s.text.as_str())
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join(" ");
    assert_eq!(joined, "the quick brown fox jumps over the lazy dog");
}

#[tokio::test]
async fn viewport_scroll_returns_new_window() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("many.txt");
    let mut content = String::new();
    for i in 0..50 {
        content.push_str(&format!("line {i}\n"));
    }
    std::fs::write(&path, &content).unwrap();

    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("many.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: open.view_id,
            cols: 80,
            rows: 5,
            overscan_rows: 2,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::Soft,

            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    assert_eq!(loaded_lines(&sub.window).0, 0);

    // A client showing line 20 with two rows of overscan asks from row 18.
    let scrolled = window_from_row(&mut ws, sub.viewport_id, 18, 12).await;
    let (first, last) = loaded_lines(&scrolled.window);
    assert_eq!(first, 18);
    assert!(last >= 25);
    let first_text = &scrolled.window.root.lines()[2].visual_rows[0].segments[0].text;
    assert_eq!(first_text, "line 20");
}

// ---- the harness itself -------------------------------------------------------------------------

/// `Ws` logs the notifications it reads past, so a push can be asserted *after* the fact rather
/// than only by a test that happened to be blocked on it at the right moment.
///
/// Two clients on one buffer: A's edit provokes a `viewport/lines_changed` push to B. B is not
/// waiting for it — it just issues an unrelated request, and `send_request` drains the push on its
/// way to the reply. Deterministic because A's edit has already returned, so the server has queued
/// B's push before B's own request goes out, and the connection delivers them in order.
#[tokio::test]
async fn the_socket_logs_pushes_it_read_past() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("a.txt"), "hello\nworld\n").unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    server.keep_alive(dir);

    let activate = WorkspaceActivateParams {
        worktrees: None,
        name: "test-proj".into(),
        open_last: false,
    };
    let open = ViewOpenParams {
        transient: None,
        path_index: Some(0),
        relative_path: Some("a.txt".into()),
        language: None,
        create_if_missing: false,
        jump_to: None,
        ..Default::default()
    };

    let mut a = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(&mut a, &activate).await;
    let a_open: ViewOpenResult = send_request::<ViewOpen>(&mut a, &open).await;

    let mut b = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(&mut b, &activate).await;
    let b_open: ViewOpenResult = send_request::<ViewOpen>(&mut b, &open).await;
    assert_eq!(a_open.buffer_id, b_open.buffer_id, "same path, same buffer");

    // B watches the buffer, then stops paying attention.
    let _: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut b,
        &ViewportSubscribeParams {
            view_id: b_open.view_id,
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    b.clear_seen();
    assert!(
        b.saw::<ViewportLinesChanged>().is_empty(),
        "nothing has changed the buffer yet"
    );

    // A types. B is asked for something unrelated, and picks the push up on the way.
    let _: EditResult = send_request::<InputText>(
        &mut a,
        &InputTextParams {
            buffer_id: a_open.buffer_id,
            text: "X".into(),
            select_pasted: false,
            replace_selection: false,
            at: None,
        },
    )
    .await;
    let _: BufferContentResult = send_request::<BufferContent>(
        &mut b,
        &BufferContentParams {
            buffer_id: b_open.buffer_id,
        },
    )
    .await;

    let pushes = b.saw::<ViewportLinesChanged>();
    assert!(
        !pushes.is_empty(),
        "B's socket should have logged the lines_changed push it read past"
    );
    assert!(
        pushes.iter().any(|p| p.window.root.lines().iter().any(|l| l
            .visual_rows
            .iter()
            .any(|r| r.segments.iter().any(|s| s.text.contains('X'))))),
        "and the logged push should carry A's edit, got {pushes:?}"
    );

    drop(server);
}

/// Dropping a `ServerHandle` must hand back the watcher's OS handle.
///
/// Each watcher is one **inotify instance**, and the kernel caps those at
/// `fs.inotify.max_user_instances` — 128 by default, counted per *user*, so orders of magnitude
/// below `ulimit -n` and shared with everything else the developer is running. They used to leak
/// outright: the watcher lived in `ServerState`, the pump task reading its events held
/// `ServerState`, and so each kept the other alive long past the test that made them. The suite
/// only survived it because slow tests were interleaved with fast ones; grouping the fast ones
/// into a single binary started failing unrelated tests with `Too many open files`.
///
/// Asserted on the handle rather than by counting this process's inotify descriptors: that count
/// is process-global, and the sibling tests running concurrently in this binary spawn servers of
/// their own, so it can only ever be a flaky approximation of what this test means.
#[tokio::test]
async fn dropping_a_server_releases_its_watcher() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("a.txt"), "hi\n").unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();

    let watcher = server
        .state
        .lock()
        .await
        .watcher
        .clone()
        .expect("a test server runs a watcher");
    assert!(
        !watcher.is_shut_down(),
        "the watcher should be live while the server is"
    );

    drop(server);
    assert!(
        watcher.is_shut_down(),
        "dropping the server must release the watcher, synchronously"
    );
}

// ---- settings/get + settings/set ----------------------------------------------------------------

/// A server whose app settings live in a tempfile rather than the developer's real
/// `settings.toml` — see `ServerState::settings_path`. Returns the server and the settings path.
async fn setup_settings_server() -> (aether_server::ServerHandle, std::path::PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let settings = dir.path().join("settings.toml");
    let mut server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    server.state.lock().await.settings_path = Some(settings.clone());
    server.keep_alive(dir);
    (server, settings)
}

/// A fresh install has no `settings.toml`; that is not an error, it is the defaults.
#[tokio::test]
async fn settings_get_returns_defaults_when_nothing_is_stored() {
    let (server, path) = setup_settings_server().await;
    assert!(!path.exists(), "no settings file yet");
    let mut ws = Ws::connect(&server).await;

    let got: AppSettings = send_request::<SettingsGet>(&mut ws, &SettingsGetParams {}).await;
    assert_eq!(got, AppSettings::default());
    drop(server);
}

/// `settings/set` persists and echoes back what actually landed, so the client reconciles against
/// disk rather than against what it hoped it sent.
#[tokio::test]
async fn settings_set_persists_and_a_later_get_reads_it_back() {
    let (server, path) = setup_settings_server().await;
    let mut ws = Ws::connect(&server).await;

    let defaults = AppSettings::default();
    let want = AppSettings {
        editor_font_size: 22,
        ui_font_size: 13,
        ligatures: !defaults.ligatures,
        hints: !defaults.hints,
        ..defaults
    };

    let echoed: AppSettings = send_request::<SettingsSet>(&mut ws, &want).await;
    assert_eq!(echoed, want, "the echo is what was stored");
    assert!(path.exists(), "settings were written to disk");

    let reread: AppSettings = send_request::<SettingsGet>(&mut ws, &SettingsGetParams {}).await;
    assert_eq!(reread, want, "and a fresh read agrees");

    // A second client — connecting after the write — sees the stored settings, not the defaults.
    let mut other = Ws::connect(&server).await;
    let theirs: AppSettings = send_request::<SettingsGet>(&mut other, &SettingsGetParams {}).await;
    assert_eq!(theirs, want);
    drop(server);
}

/// Settings are app-wide, so the change is pushed live to every *other* client. The setter learns
/// the new state from its own result and must not be pushed to as well.
#[tokio::test]
async fn settings_set_pushes_to_other_clients_but_not_the_setter() {
    let (server, _path) = setup_settings_server().await;
    let mut setter = Ws::connect(&server).await;
    let mut watcher = Ws::connect(&server).await;
    // Give the watcher a request in flight first, so it has read up to the current point.
    let _: AppSettings = send_request::<SettingsGet>(&mut watcher, &SettingsGetParams {}).await;
    watcher.clear_seen();
    setter.clear_seen();

    let want = AppSettings {
        editor_font_size: 19,
        ..AppSettings::default()
    };
    let _: AppSettings = send_request::<SettingsSet>(&mut setter, &want).await;

    // The watcher picks the push up on its way to an unrelated reply.
    let _: AppSettings = send_request::<SettingsGet>(&mut watcher, &SettingsGetParams {}).await;
    let pushed = watcher.saw::<SettingsChanged>();
    assert_eq!(
        pushed.len(),
        1,
        "the other client is told, so the change applies live"
    );
    assert_eq!(pushed[0].editor_font_size, 19);

    assert!(
        setter.saw::<SettingsChanged>().is_empty(),
        "the setter already has the answer in its own result"
    );
    drop(server);
}
