// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.

mod common;

use common::*;

// ---- picker grep -------------------------------------------------------------------------------

#[tokio::test]
async fn picker_grep_finds_matches_and_select_returns_file_at() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await; // initial empty push

    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;

    let final_update = drain_grep_until_done(&mut ws).await;
    assert_eq!(final_update.kind, PickerKind::Grep);
    assert_eq!(final_update.generation, 1);
    // 2 hits in main.rs + 1 hit in lib.rs = 3 GrepHits total (headers don't count).
    assert_eq!(final_update.total_matches, 3);
    // One header row per file, hit counts on the rows; every group starts collapsed.
    assert_eq!(
        group_rows(final_update.items()),
        vec![
            ("src/lib.rs".to_string(), 1, false),
            ("src/main.rs".to_string(), 2, false),
        ]
    );
    // Expand lib.rs's group and re-view to get its hit row in hand.
    let (row, update) = expand_file_group(&mut ws, PickerKind::Grep, "src/lib.rs").await;
    assert_eq!(row, 0, "lib.rs's header stays the first row");
    let hit = update
        .items()
        .iter()
        .find(|i| matches!(i, PickerItem::GrepHit { relative_path, .. } if relative_path == "src/lib.rs"))
        .expect("lib.rs hit present after expanding its group");
    let (line, col, preview) = match hit {
        PickerItem::GrepHit {
            line, col, preview, ..
        } => (*line, *col, preview.clone()),
        _ => unreachable!(),
    };
    assert_eq!(line, 0, "lib.rs hit is on line 0 (`fn needle() {{}}`)");
    assert_eq!(col, 3, "col 3 is the `n` of `needle`");
    assert!(preview.contains("needle"));

    // Select that hit; should return FileAt with the absolute path and position.
    let select_result: PickerSelectResult = send_request::<PickerSelect>(
        &mut ws,
        &PickerSelectParams {
            kind: PickerKind::Grep,
            item: hit.clone(),
        },
    )
    .await;
    let (sel_path, sel_pos) = match select_result {
        PickerSelectResult::FileAt { path, position, .. } => (path, position),
        other => panic!("expected FileAt, got {other:?}"),
    };
    assert!(sel_path.ends_with("src/lib.rs"));
    assert_eq!(sel_pos.line, 0);
    assert_eq!(sel_pos.col, 3);

    drop(server);
}

/// `Space Alt-/`: `picker/view { from_selection }` slices the buffer's selection into a literal
/// grep query and runs the search in the same call — the query rides back in the response and the
/// hits stream in, with no separate `picker/query`.
#[tokio::test]
async fn picker_grep_from_selection_seeds_query_and_searches() {
    let (server, mut ws) = setup_grep_workspace().await;
    // Open src/main.rs and select "needle" on line 1 (`    needle();`, cols 4..=9).
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("src/main.rs".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;
    send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 9 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;

    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            from_selection: true,
            reset: PickerReset::Keep,
            limit: 30,
            buffer_id: Some(buffer_id),
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert_eq!(view.query, "needle", "query is seeded from the selection");

    // The search ran from the view call — no `picker/query` needed. Drain to completion.
    let final_update = drain_grep_until_done(&mut ws).await;
    assert_eq!(
        final_update.generation, view.generation,
        "tagged with the echoed generation"
    );
    assert_eq!(final_update.total_matches, 3, "2 in main.rs + 1 in lib.rs");

    drop(server);
}

/// A from-selection grep on an empty selection (point cursor on a blank line) seeds no query and
/// spawns no search — grep just opens unseeded.
#[tokio::test]
async fn picker_grep_from_selection_empty_is_unseeded() {
    let (server, mut ws) = setup_grep_workspace().await;
    // README.md ends with a newline; opening it and sitting on the trailing empty line gives a
    // point cursor over an empty slice.
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("README.md".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;
    send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 0 },
            anchor: LogicalPosition { line: 1, col: 0 },
        },
    )
    .await;

    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            from_selection: true,
            reset: PickerReset::Keep,
            limit: 30,
            buffer_id: Some(buffer_id),
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert_eq!(view.query, "", "empty selection leaves grep unseeded");
    // The initial push is the open snapshot, not a search tick.
    let push = expect_notification::<PickerUpdate>(&mut ws).await;
    assert!(!push.ticking, "no search spawned for an empty selection");

    drop(server);
}

/// A grep query's initial push is a count-only tick (`items: None`), not an empty window. That
/// keeps the previous query's results on screen while the new search spawns, so typing doesn't
/// flash the list empty every keystroke. The streaming batches + completion push (always
/// `Some(...)`) then replace them.
#[tokio::test]
async fn picker_grep_query_initial_push_keeps_the_window() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await; // the view's own push

    // Send the query raw (not via `send_request`, which discards notifications while awaiting the
    // response — and the initial push races ahead of it) so we can inspect the first push.
    let req = Request {
        jsonrpc: JsonRpc,
        id: 11,
        method: PickerQuery::NAME.into(),
        params: Some(
            serde_json::to_value(&PickerQueryParams {
                filters: Default::default(),
                kind: PickerKind::Grep,
                query: "needle".into(),
                generation: 1,
            })
            .unwrap(),
        ),
    };
    ws.send(Message::text(serde_json::to_string(&req).unwrap()))
        .await
        .unwrap();

    // The first push after the query is the synchronous initial tick (sent before the worker runs).
    let initial = expect_notification::<PickerUpdate>(&mut ws).await;
    assert_eq!(initial.generation, 1);
    assert!(initial.ticking, "the search is in flight");
    assert!(
        initial.items.is_none(),
        "a count-only tick keeps the client's window rather than blanking it; got {:?}",
        initial.items
    );

    // The search still completes normally, replacing the window with the real hits.
    let final_update = drain_grep_until_done(&mut ws).await;
    assert_eq!(final_update.total_matches, 3);
    assert!(final_update.items.is_some());

    drop(server);
}

/// Queries shorter than the min length don't spawn a search and produce an empty,
/// not-ticking result set.
#[tokio::test]
async fn picker_grep_short_query_yields_empty_result() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;

    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "n".into(), // below MIN_QUERY_LEN
            generation: 1,
        },
    )
    .await;
    let update: PickerUpdateParams = expect_notification::<PickerUpdate>(&mut ws).await;
    assert_eq!(update.generation, 1);
    assert_eq!(update.total_matches, 0);
    assert!(
        !update.ticking,
        "below-min queries should not flag the picker as still searching"
    );

    drop(server);
}

/// Grep hits persist across a `Keep` re-view *within one open* — the scroll/refetch cycle — so
/// paging through a long result list never re-runs the (slow) workspace walk. The query stays
/// active and the prior result set is intact.
#[tokio::test]
async fn picker_grep_keeps_hits_across_a_keep_scoped_re_view() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;

    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let before = drain_grep_until_done(&mut ws).await;
    let before_hits = before.total_matches;
    assert!(before_hits >= 1);

    // A `Keep`-scoped re-view — what a scroll refetch sends, *without* closing
    // the picker — gets the prior hits back rather than re-running the walk. (Closing wipes, and a
    // fresh open sends `All`; see `grep_fresh_open_wipes_hits_and_filters`.)
    let resume = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert_eq!(resume.query, "needle", "query survives a re-view");
    let update: PickerUpdateParams = expect_notification::<PickerUpdate>(&mut ws).await;
    assert_eq!(
        update.total_matches, before_hits,
        "hits reused — the walk doesn't re-run"
    );

    drop(server);
}

/// Closing a picker releases its state there and then, rather than parking it until the next open
/// wipes it. Two things ride on this: an in-flight grep walk sees the bumped generation and stops
/// (instead of scanning the rest of the workspace into a list nobody will see), and a closed
/// picker can't hand old results back even to a client that asks for them with `Keep`.
#[tokio::test]
async fn closing_a_picker_clears_it_and_moves_the_generation() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let found = drain_grep_until_done(&mut ws).await;
    assert!(found.total_matches >= 1, "the search ran");

    let _: () = send_request::<PickerHide>(
        &mut ws,
        &PickerHideParams {
            kind: PickerKind::Grep,
        },
    )
    .await;

    // Ask for the closed picker back the most permissive way there is — no client does this, which
    // is the point: there is nothing left to resume even for a caller that asks.
    let after: aether_protocol::picker::PickerViewResult = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert_eq!(after.query, "", "the query went with the close");
    assert_eq!(after.total_candidates, 0, "so did the hits");
    assert!(
        after.generation > 1,
        "the generation moved past the closed search — how the walk learns to stop"
    );

    drop(server);
}

/// A fresh grep open (`PickerReset::All`) throws away the query, the hits it produced *and* the
/// filter chips — grep opens exactly as clean as Files and the Explorer do. Recalling a query along
/// with the chips it ran under is the input history's job, and stepping the old *results* is the
/// jumplist's.
#[tokio::test]
async fn grep_fresh_open_wipes_hits_and_filters() {
    let (server, mut ws) = setup_grep_filter_workspace().await;
    let filters = PickerFilters {
        whole_word: true,
        ..Default::default()
    };
    let update = grep_with_filters(&mut ws, "needle", filters.clone(), 1).await;
    assert_eq!(update.total_matches, 6);

    let _: () = send_request::<PickerHide>(
        &mut ws,
        &PickerHideParams {
            kind: PickerKind::Grep,
        },
    )
    .await;

    let reopen: aether_protocol::picker::PickerViewResult =
        send_request::<PickerView>(&mut ws, &view_params(PickerKind::Grep)).await;
    assert_eq!(reopen.query, "", "the query is wiped on a fresh open");
    assert_eq!(reopen.total_candidates, 0, "so are the hits it produced");
    assert_eq!(
        reopen.filters,
        PickerFilters::default(),
        "and so are the chips — a stale scope must not narrow the next search"
    );
    // The wipe drops the whole slot, but the generation counter is carried past the retired one:
    // grep's streaming worker is cancelled by generation comparison, and the previous open's walk
    // may still be running. A restart at 0 would let it collide and append hits for the old query.
    assert!(
        reopen.generation > 1,
        "generation carried past the retired slot, not restarted"
    );

    // Searching again from the clean slate runs unfiltered — the whole-word chip is gone, so the
    // substring matches the earlier search excluded are back.
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: PickerFilters::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: reopen.generation + 1,
        },
    )
    .await;
    let again = drain_grep_until_done(&mut ws).await;
    assert!(
        again.total_matches > 6,
        "unfiltered search sees more than the whole-word one ({} hits)",
        again.total_matches
    );

    drop(server);
}

/// A *seeded* fresh open installs the caller's filters rather than the defaults the wipe leaves
/// behind — the ordering the Explorer's "grep here" (`Ctrl-g`, which hands the browsed directory
/// over as a dir chip) rides on. The wipe and the seed both land in one `picker/view`, and the seed
/// has to win.
#[tokio::test]
async fn grep_fresh_open_installs_seeded_filters_over_the_wipe() {
    let (server, mut ws) = setup_grep_filter_workspace().await;
    // A prior open with chips of its own, so the reopen has a populated slot to wipe.
    let stale = PickerFilters {
        whole_word: true,
        ..Default::default()
    };
    let _ = grep_with_filters(&mut ws, "needle", stale, 1).await;
    let _: () = send_request::<PickerHide>(
        &mut ws,
        &PickerHideParams {
            kind: PickerKind::Grep,
        },
    )
    .await;

    let seed = PickerFilters {
        include_hidden: true,
        ..Default::default()
    };
    let reopen: aether_protocol::picker::PickerViewResult = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            filters: Some(seed.clone()),
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert_eq!(
        reopen.filters, seed,
        "the seed survives the wipe — otherwise 'grep here' would lose its directory scope"
    );
    assert_eq!(
        reopen.query, "",
        "still a fresh open in every other respect"
    );

    drop(server);
}

/// Grep treats the query as a regex when the `.*` chip is on (opt-in, like buffer search). A
/// pattern like `n.+dle` then matches `needle`; by default the query is literal.
#[tokio::test]
async fn picker_grep_treats_query_as_regex() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;

    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: PickerFilters {
                regex: true,
                ..Default::default()
            },
            kind: PickerKind::Grep,
            query: "n.+dle".into(),
            generation: 1,
        },
    )
    .await;
    let final_update = drain_grep_until_done(&mut ws).await;
    assert!(
        final_update.total_matches >= 1,
        "regex `n.+dle` should match `needle` ({} hits)",
        final_update.total_matches,
    );

    drop(server);
}

/// Re-issuing the same query after a search completes uses the cached candidates: the response
/// arrives without `ticking: true` (no fresh walker spawned) and the hit count matches the
/// previous run.
#[tokio::test]
async fn picker_grep_caches_completed_query() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;

    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let first = drain_grep_until_done(&mut ws).await;
    let first_hits = first.total_matches;
    assert!(first_hits >= 1);

    // Same query again — should hit the cache. The single push that arrives must already be
    // non-ticking (no spawn) and carry the cached hit count.
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 2,
        },
    )
    .await;
    let cached: PickerUpdateParams = expect_notification::<PickerUpdate>(&mut ws).await;
    assert_eq!(cached.generation, 2);
    assert_eq!(cached.total_matches, first_hits);
    assert!(
        !cached.ticking,
        "cache hit must not mark the picker as ticking — no new search was spawned"
    );

    drop(server);
}

/// Run a grep query against `setup_grep_workspace`'s "needle" pattern and return (server, ws,
/// final picker update). Shared setup for the navigation tests.
async fn setup_grep_with_needle_query() -> (aether_server::ServerHandle, Ws) {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;
    (server, ws)
}

/// A bare file-scoped `jumplist/step` (`Alt-]` / `Alt-[`, no composite open).
async fn step_in_file(ws: &mut Ws, buffer_id: u64, direction: Direction) -> JumplistStepResult {
    send_request::<JumplistStep>(
        ws,
        &JumplistStepParams {
            buffer_id,
            direction,
            count: 1,
            scope: JumplistStepScope::CurrentFile,
            open: false,
        },
    )
    .await
}

#[tokio::test]
async fn jumplist_capture_snapshots_and_step_composite_opens() {
    // Picker Ctrl-j snapshots the filtered results and reports the highlighted
    // row's position (the client then shows the Jumplist picker framed on it — capture itself
    // doesn't navigate). Stepping is the composite that opens. Workspace needle hits:
    // src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4.
    let (_server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 0 }).await;

    // Highlighted row: the lib.rs hit — the captured list's first entry (walker order).
    let captured = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    assert_eq!(captured.total, 3, "all three needle hits captured");
    assert_eq!(
        captured.index, 0,
        "the highlighted hit is the list's first entry (0-based, for center_on)"
    );

    // `[` from before main.rs's hits crosses into lib.rs — the step composite opens it:
    // transient, the match landed selected (anchor at its start, head on its last char;
    // "needle" = 6 chars), origin on nav history. No search priming involved.
    let target: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id,
            direction: Direction::Backward,
            count: 1,
            scope: JumplistStepScope::Full,
            open: true,
        },
    )
    .await;
    let target = target.moved().expect("captured list steps");
    let opened = target.opened.expect("composite opens the target");
    assert_ne!(opened.buffer_id, buffer_id);
    assert!(opened.transient, "jumplist jumps open transient previews");
    assert_eq!(opened.cursor.anchor, LogicalPosition { line: 0, col: 3 });
    assert_eq!(opened.cursor.position, LogicalPosition { line: 0, col: 8 });
    // The freshly-landed cursor already carries the status stamp: entry 1 of 3.
    let rp = opened
        .cursor
        .jumplist_position
        .expect("landed exactly on the captured entry");
    assert_eq!((rp.current, rp.total), (1, 3));

    // And the origin was recorded: nav/back returns to main.rs.
    let back: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: opened.buffer_id,
            direction: Direction::Backward,
        },
    )
    .await;
    assert_eq!(back.target.expect("origin recorded").buffer_id, buffer_id);
}

#[tokio::test]
async fn jumplist_step_within_file_falls_through_then_stops_at_end() {
    // Captured entries (normalized order): src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/main.rs", 1, 4).await;

    // Cursor at the top of main.rs (before any hit) — forward steps to the first entry in
    // this file. Targets land selection-shaped: anchor at the match start, position at its
    // last char ("needle" = 6 chars).
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let target = step_results(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("a captured list resolves the next entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/main.rs"));
    assert_eq!(target.anchor, Some(LogicalPosition { line: 1, col: 4 }));
    assert_eq!(target.position, Some(LogicalPosition { line: 1, col: 9 }));
    assert_eq!((target.index, target.total), (2, 3));

    // Cursor sitting on the last hit (line 2) — forward falls off the end of main.rs and, with
    // no later file in the list, STOPS at the end rather than wrapping (reported as AtEnd; the
    // client toasts "last entry"). This is the no-wrap behaviour.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 2, col: 4 }).await;
    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "forward past the last entry stops, no wrap: {outcome:?}"
    );

    // Backward from inside main.rs falls through to lib.rs after exhausting main.rs's hits.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 0 }).await;
    let target = step_results(&mut ws, buffer_id, Direction::Backward)
        .await
        .moved()
        .expect("hit in earlier file");
    assert!(target.path.as_deref().unwrap().ends_with("src/lib.rs"));
    assert_eq!(target.anchor, Some(LogicalPosition { line: 0, col: 3 }));
    assert_eq!(target.position, Some(LogicalPosition { line: 0, col: 8 }));

    drop(server);
}

#[tokio::test]
async fn jumplist_step_repeated_press_advances_then_stops_at_end() {
    // The "repeated press makes progress" property: stepping with the composite open from each
    // landed position advances entry-by-entry and never sticks — then stops (AtEnd) at the last,
    // rather than wrapping.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;

    // From the top of main.rs, forward steps land on 2 then 3 (main.rs's two hits, skipping the
    // earlier lib.rs entry), then the third press stops at the end — each re-keying off the
    // just-landed selection.
    let mut current = buffer_id;
    let mut seen = Vec::new();
    for _ in 0..2u64 {
        let target = send_request::<JumplistStep>(
            &mut ws,
            &JumplistStepParams {
                buffer_id: current,
                direction: Direction::Forward,
                count: 1,
                scope: JumplistStepScope::Full,
                open: true,
            },
        )
        .await
        .moved()
        .expect("composite opens each entry");
        current = target.opened.expect("composite opens each entry").buffer_id;
        seen.push(target.index);
    }
    assert_eq!(seen, vec![2, 3], "steps advance one at a time, no sticking");

    // On the last entry now: another forward press stops at the end (no wrap to entry 1).
    let outcome: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id: current,
            direction: Direction::Forward,
            count: 1,
            scope: JumplistStepScope::Full,
            open: true,
        },
    )
    .await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "stepping past the last entry stops: {outcome:?}"
    );

    drop(server);
}

#[tokio::test]
async fn jumplist_step_takes_a_count() {
    // `3]`: the count advances entry-by-entry (cycling), one round-trip.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    // Forward 2 from before main.rs's hits: entry 2 (main:1) then entry 3 (main:2).
    let target: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id,
            direction: Direction::Forward,
            count: 2,
            scope: JumplistStepScope::Full,
            open: false,
        },
    )
    .await;
    let target = target.moved().expect("captured list steps");
    assert_eq!((target.index, target.total), (3, 3));
    // A count the list cannot honour **refuses** — no wrap, and no clamp either. `5]` landing on
    // the last entry is what made `5]` then `5[` lose your place, since the return trip counted
    // back from wherever the clamp had put you.
    let target: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id,
            direction: Direction::Forward,
            count: 5,
            scope: JumplistStepScope::Full,
            open: false,
        },
    )
    .await;
    assert!(
        target.moved().is_none(),
        "a count past the last entry must not move at all"
    );

    drop(server);
}

#[tokio::test]
async fn jumplist_step_virtually_inserts_files_not_in_the_list() {
    // README.md has no entries. Forward jumps to the first entry of the file sorting *after*
    // it (src/lib.rs, since 'R' < 's'); backward, with nothing sorting before README.md, has
    // nowhere to go — it stops at the start (AtEnd) rather than wrapping.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "README.md").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;

    let target = step_results(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("forward jumps to the next file's entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/lib.rs"));
    assert_eq!((target.index, target.total), (1, 3));

    let outcome = step_results(&mut ws, buffer_id, Direction::Backward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "nothing sorts before README.md, so backward stops at the start: {outcome:?}"
    );

    drop(server);
}

#[tokio::test]
async fn jumplist_step_in_file_stays_in_the_current_file_and_stops() {
    // `Alt-]` / `Alt-[`: step only among the current file's entries, never falling through.
    // Captured entries (normalized): src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // From the top of main.rs, scoped forward lands its first hit (entry 2), skipping lib.rs.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let target = step_in_file(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("steps to the file's first entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/main.rs"));
    assert_eq!((target.index, target.total), (2, 3));

    // On main.rs's first hit, scoped forward → its second hit (entry 3).
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 4 }).await;
    let target = step_in_file(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("steps to the file's next entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/main.rs"));
    assert_eq!((target.index, target.total), (3, 3));

    // On main.rs's last hit, scoped forward stops — it does NOT fall through to a later file
    // (there is none) nor wrap; it's AtEnd within the file.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 2, col: 4 }).await;
    let outcome = step_in_file(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "scoped forward past the file's last entry stops: {outcome:?}"
    );

    // Scoped backward from main.rs's first hit stops too — it does NOT cross into lib.rs (which
    // plain `[` would).
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 0 }).await;
    let outcome = step_in_file(&mut ws, buffer_id, Direction::Backward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "scoped backward before the file's first entry stops, no cross-file: {outcome:?}"
    );

    drop(server);
}

#[tokio::test]
async fn jumplist_step_in_file_reports_none_for_a_file_without_entries() {
    // README.md has no captured entries. `Alt-]` there is a distinct no-op (NoneInFile) — unlike
    // plain `]`, which virtually inserts the file and jumps to an adjacent file's entry.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "README.md").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;

    let outcome = step_in_file(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::NoneInFile),
        "no entries in README.md: {outcome:?}"
    );
    // Sanity: plain `]` from the same spot DOES move (crosses into src/lib.rs).
    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        outcome.moved().is_some(),
        "cross-file step still jumps from a file with no entries"
    );

    drop(server);
}

#[tokio::test]
async fn jumplist_step_reports_empty_without_a_capture() {
    // Grep results exist server-side, but nothing was captured — `]` is a clean no-op reported as
    // Empty (the client toasts how to capture). The old implicit grep-hits stepping is gone by
    // design.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;

    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::Empty),
        "no captured list: {outcome:?}"
    );

    drop(server);
}

/// The list belongs to the **context**, so every shell attached to it steps the same one — and each
/// steps it from its *own* cursor, since a step is cursor-derived rather than indexed.
#[tokio::test]
async fn a_capture_is_shared_by_every_client_in_the_context() {
    // Client 1 captures the three needle hits: src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Client 2 joins the same workspace. It never opened a picker, let alone captured one.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let buffer_id2 = open_test_buffer(&mut ws2, "src/main.rs").await;

    // Park the two cursors at opposite ends of main.rs: client 1 on the file's last hit, client 2
    // above the first. Same list, two positions in it.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 2, col: 4 }).await;
    set_point_cursor(&mut ws2, buffer_id2, LogicalPosition { line: 0, col: 0 }).await;

    // Client 2 steps the list it never captured.
    let target = step_results(&mut ws2, buffer_id2, Direction::Forward)
        .await
        .moved()
        .expect("client 2 sees the context's captured list");
    assert!(target.path.as_deref().unwrap().ends_with("src/main.rs"));
    assert_eq!(target.anchor, Some(LogicalPosition { line: 1, col: 4 }));
    assert_eq!(
        (target.index, target.total),
        (2, 3),
        "the same three entries client 1 captured"
    );

    // …and client 1, on the same list from its own cursor, is at the end of it. Two clients, one
    // list, two places in it — which is what makes sharing the contents safe.
    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "client 1 steps from *its* cursor, past the last entry: {outcome:?}"
    );

    drop(server);
}

/// A window has no durable identity, so the list must not die with one. Capture, close the client,
/// reconnect: the context still holds it.
#[tokio::test]
async fn a_capture_outlives_the_client_that_made_it() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let _ = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // The window closes. The teardown runs on the server's own task, so wait for it to land
    // rather than guessing at how long it takes.
    drop(ws);
    wait_for_client_count(&server, 0).await;

    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let buffer_id2 = open_test_buffer(&mut ws2, "src/main.rs").await;
    set_point_cursor(&mut ws2, buffer_id2, LogicalPosition { line: 0, col: 0 }).await;

    let target = step_results(&mut ws2, buffer_id2, Direction::Forward)
        .await
        .moved()
        .expect("the capture survived the client that made it");
    assert_eq!((target.index, target.total), (2, 3));

    drop(server);
}

/// Switching workspace no longer *wipes* the list — it leaves it on the context it belongs to, so
/// coming back finds it. (The entries only ever pointed into that context's files, which is what
/// the wipe was protecting against; ownership does the same job without throwing anything away.)
#[tokio::test]
async fn a_capture_survives_switching_away_and_back() {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::create_dir_all(dir_path.join("src")).unwrap();
    std::fs::write(
        dir_path.join("src/main.rs"),
        "fn main() {\n    needle();\n    needle();\n}\n",
    )
    .unwrap();
    std::fs::write(
        dir_path.join("src/lib.rs"),
        "fn needle() {}\nfn other() {}\n",
    )
    .unwrap();
    let other = tempfile::tempdir().unwrap();
    std::fs::write(other.path().join("elsewhere.txt"), "nothing\n").unwrap();

    let mut server = aether_server::spawn_for_test_multi(vec![
        ("test-proj".to_string(), vec![dir_path]),
        ("other-proj".to_string(), vec![other.path().to_path_buf()]),
    ])
    .await
    .unwrap();
    server.keep_alive(dir);
    server.keep_alive(other);
    let mut ws = Ws::connect(&server).await;
    let activate = |name: &str| WorkspaceActivateParams {
        worktrees: None,
        name: name.into(),
        open_last: false,
    };

    let _: WorkspaceActivateResult =
        send_request::<WorkspaceActivate>(&mut ws, &activate("test-proj")).await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Away…
    let _: WorkspaceActivateResult =
        send_request::<WorkspaceActivate>(&mut ws, &activate("other-proj")).await;
    let elsewhere = open_test_buffer(&mut ws, "elsewhere.txt").await;
    set_point_cursor(&mut ws, elsewhere, LogicalPosition { line: 0, col: 0 }).await;
    let outcome = step_results(&mut ws, elsewhere, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::Empty),
        "the other workspace has its own (empty) list, not this one's: {outcome:?}"
    );

    // …and back.
    let _: WorkspaceActivateResult =
        send_request::<WorkspaceActivate>(&mut ws, &activate("test-proj")).await;
    let reopened = open_test_buffer(&mut ws, "src/main.rs").await;
    assert_eq!(reopened, buffer_id, "the same buffer, still open");
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let target = step_results(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("the capture was still on the context we returned to");
    assert_eq!((target.index, target.total), (2, 3));

    drop(server);
}

#[tokio::test]
async fn clearing_the_jumplist_empties_it_and_undecorates_the_cursor() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Park the cursor exactly on the main.rs:1 entry ("needle" spans cols 4..=9) so the status
    // stamp is showing — that stamp is what the clear has to take down with it.
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 9 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;
    assert!(st.jumplist_position.is_some(), "stamped before the clear");

    let cleared = clear_jumplist(&mut ws, Some(buffer_id)).await;
    assert_eq!(cleared.cleared, 3, "all three captured entries discarded");
    let cursor = cleared.cursor.expect("the caller's cursor comes back");
    assert_eq!(
        cursor.position,
        LogicalPosition { line: 1, col: 9 },
        "the cursor itself doesn't move"
    );
    assert!(
        cursor.jumplist_position.is_none(),
        "…but its k/N stamp goes with the list, on this response"
    );

    // And the list really is gone: stepping reports Empty, not AtEnd.
    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::Empty),
        "nothing captured any more: {outcome:?}"
    );

    drop(server);
}

/// Clearing what isn't there is a no-op, not an error — the client says "already empty" rather
/// than "clear failed".
#[tokio::test]
async fn clearing_an_empty_jumplist_reports_nothing_cleared() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 4 }).await;

    let cleared = clear_jumplist(&mut ws, Some(buffer_id)).await;
    assert_eq!(cleared.cleared, 0);
    assert!(cleared
        .cursor
        .expect("still decorated")
        .jumplist_position
        .is_none());

    // Twice over, and after a real capture-then-clear, it stays a no-op.
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    assert_eq!(clear_jumplist(&mut ws, Some(buffer_id)).await.cleared, 3);
    assert_eq!(clear_jumplist(&mut ws, Some(buffer_id)).await.cleared, 0);

    drop(server);
}

/// The clear reaches as far as the list does: every client in the context, and no further.
#[tokio::test]
async fn clearing_reaches_every_client_in_the_context() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;

    // A second client in the same workspace clears the list client 1 captured.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let cleared = clear_jumplist(&mut ws2, None).await;
    assert_eq!(cleared.cleared, 3, "client 2 clears the shared list");
    assert!(
        cleared.cursor.is_none(),
        "no buffer named, so nothing to decorate"
    );

    // Client 1's `]` finds nothing, without it having done anything itself.
    let outcome = step_results(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::Empty),
        "the clear reached the other client in the context: {outcome:?}"
    );

    drop(server);
}

/// A picker open on one client doesn't quietly go stale when another replaces or discards the list
/// under it. The notification carries nothing — it says "re-view", because a capture can change the
/// list's shape and that gate rides the view response, not a push.
#[tokio::test]
async fn changing_the_list_tells_other_clients_with_the_picker_open() {
    use aether_protocol::jumplist::JumplistChanged;

    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Client 2 joins and opens the Jumplist picker on the shared list.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let view: aether_protocol::picker::PickerViewResult =
        send_request::<PickerView>(&mut ws2, &view_params(PickerKind::Jumplist)).await;
    assert_eq!(view.total_candidates, 3, "client 2 is looking at the list");
    let _ = expect_notification::<PickerUpdate>(&mut ws2).await;

    // Client 1 narrows its grep and re-captures, so the new list is a *different* size.
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "fn needle".into(),
            generation: 2,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;
    let recaptured = capture_grep_results(&mut ws, "src/lib.rs", 0, 0).await;
    assert_eq!(recaptured.total, 1, "only lib.rs declares `fn needle`");
    let _: aether_protocol::jumplist::JumplistChangedParams =
        expect_notification_within::<JumplistChanged>(
            &mut ws2,
            std::time::Duration::from_millis(500),
        )
        .await;
    // The re-view the notification asks for is what actually refreshes the picker — and it must
    // pick up the new list under `PickerReset::Keep`, since that's what the client sends.
    let refreshed: aether_protocol::picker::PickerViewResult = send_request::<PickerView>(
        &mut ws2,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(
        refreshed.total_candidates, 1,
        "the re-view shows the other client's narrowed list"
    );

    // …and a clear reaches it the same way, leaving the re-view genuinely empty.
    assert_eq!(clear_jumplist(&mut ws, Some(buffer_id)).await.cleared, 1);
    let _: aether_protocol::jumplist::JumplistChangedParams =
        expect_notification_within::<JumplistChanged>(
            &mut ws2,
            std::time::Duration::from_millis(500),
        )
        .await;
    let refreshed: aether_protocol::picker::PickerViewResult = send_request::<PickerView>(
        &mut ws2,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(refreshed.total_candidates, 0, "the list is gone");

    // Clearing again changes nothing for anyone, so nobody is told.
    assert_eq!(clear_jumplist(&mut ws, Some(buffer_id)).await.cleared, 0);
    let quiet = tokio::time::timeout(std::time::Duration::from_millis(150), async {
        loop {
            let text = next_text(&mut ws2).await;
            if let Ok(ClientInbound::Notification(n)) = serde_json::from_str::<ClientInbound>(&text)
            {
                if n.method == JumplistChanged::NAME {
                    return n;
                }
            }
        }
    })
    .await;
    assert!(quiet.is_err(), "a no-op clear notifies nobody");

    drop(server);
}

/// The notification is scoped like the list itself: the client that caused the change doesn't get
/// told (it re-frames its own picker), and neither does a picker open in a different workspace.
#[tokio::test]
async fn the_changed_notification_skips_the_actor_and_other_contexts() {
    use aether_protocol::jumplist::JumplistChanged;

    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::create_dir_all(dir_path.join("src")).unwrap();
    std::fs::write(
        dir_path.join("src/main.rs"),
        "fn main() {\n    needle();\n    needle();\n}\n",
    )
    .unwrap();
    std::fs::write(
        dir_path.join("src/lib.rs"),
        "fn needle() {}\nfn other() {}\n",
    )
    .unwrap();
    let other = tempfile::tempdir().unwrap();
    std::fs::write(other.path().join("elsewhere.txt"), "nothing\n").unwrap();

    let mut server = aether_server::spawn_for_test_multi(vec![
        ("test-proj".to_string(), vec![dir_path]),
        ("other-proj".to_string(), vec![other.path().to_path_buf()]),
    ])
    .await
    .unwrap();
    server.keep_alive(dir);
    server.keep_alive(other);

    // Client 1 in test-proj, with a grep run and a Jumplist picker of its own open.
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;

    // Client 2 in the *other* workspace, also sitting on a Jumplist picker.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "other-proj".into(),
            open_last: false,
        },
    )
    .await;
    let _ = send_request::<PickerView>(&mut ws2, &view_params(PickerKind::Jumplist)).await;
    let _ = expect_notification::<PickerUpdate>(&mut ws2).await;

    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Neither the actor nor the other workspace's picker hears about it.
    for (label, sock) in [("the actor", &mut ws), ("another context", &mut ws2)] {
        let heard = tokio::time::timeout(std::time::Duration::from_millis(200), async {
            loop {
                let text = next_text(sock).await;
                if let Ok(ClientInbound::Notification(n)) =
                    serde_json::from_str::<ClientInbound>(&text)
                {
                    if n.method == JumplistChanged::NAME {
                        return n;
                    }
                }
            }
        })
        .await;
        assert!(heard.is_err(), "{label} must not be notified");
    }

    drop(server);
}

/// `jumplist_position` is `Some` on `CursorState` when the cursor's selection covers a captured
/// entry *exactly* (anchor at its span start, position at its last char), and `None`
/// otherwise — the same strict endpoint check `match_index_for_cursor` uses for `A/B`.
#[tokio::test]
async fn cursor_carries_jumplist_position_when_selection_covers_an_entry() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Captured entries: src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4.
    // "needle" is 6 bytes, so the main.rs:1 entry covers cols 4..=9 — the cursor must select
    // exactly that range to count as "on" it. This is the post-jump shape (anchor at the
    // span start, position at its last char).
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 9 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;
    let rp = st
        .jumplist_position
        .expect("selection covers the entry exactly");
    assert_eq!(rp.current, 2);
    assert_eq!(rp.total, 3);

    // Orientation-agnostic: swapping anchor/position still counts as "on" the entry.
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 4 },
            anchor: LogicalPosition { line: 1, col: 9 },
        },
    )
    .await;
    assert!(st.jumplist_position.is_some());

    // A point cursor at the entry's start (anchor == position == span start) doesn't cover the
    // whole span — indicator clears, matching how A/B drops a partial selection.
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 4 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;
    assert!(st.jumplist_position.is_none());

    // A larger selection that contains the span but extends past it also doesn't count.
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 10 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;
    assert!(st.jumplist_position.is_none());

    drop(server);
}

/// Capture the workspace's *files* into the jumplist (`Ctrl-j` in the Files picker) with
/// `relative_path` as the highlighted row. The rows are whole targets — no position — so the
/// captured list is ungrouped and steps one file at a time.
async fn capture_files(ws: &mut Ws, relative_path: &str) -> JumplistCaptureResult {
    let r: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        ws,
        &JumplistCaptureParams {
            kind: PickerKind::Files,
            item: PickerItem::File {
                path_index: 0,
                relative_path: relative_path.into(),
                match_indices: vec![],
                git_status: None,
            },
        },
    )
    .await;
    r.expect("the workspace has files, capture snapshots them")
}

/// A Files-picker capture is a list of whole targets: the Jumplist picker renders it **flat**
/// (no group rows, `collapsible: false`) with no line numbers, and `]`/`[` walk it one file per
/// press regardless of where the cursor sits — the file-list shape of the jumplist.
#[tokio::test]
async fn jumplist_captured_from_the_files_picker_is_flat_and_steps_by_file() {
    let (server, mut ws) = setup_grep_workspace().await;
    // The Files picker has to have been viewed for the capture to have candidates.
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Files)
        },
    )
    .await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    // Park the cursor deep inside main.rs — a whole-target entry ignores it.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 2, col: 4 }).await;

    let captured = capture_files(&mut ws, "src/main.rs").await;
    assert_eq!(
        captured.total, 3,
        "README.md, src/lib.rs and src/main.rs all captured"
    );

    // The view is flat: no group rows, no group spans, and every row carries a bare path with
    // no line number.
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert!(
        !view.collapsible,
        "a file-shaped capture has nothing to group by, so the view renders flat"
    );
    let update = view.update.expect("the view carries its initial window");
    assert!(
        update.groups.is_empty(),
        "no group spans pushed for a flat view, got {:?}",
        update.groups
    );
    let items = update.items();
    assert!(
        !items.iter().any(|i| matches!(i, PickerItem::Group { .. })),
        "no selectable header rows either, got {items:?}"
    );
    let rows: Vec<(&str, Option<u32>)> = items
        .iter()
        .map(|i| match i {
            PickerItem::JumplistEntry { display, line, .. } => (display.as_str(), *line),
            other => panic!("expected a JumplistEntry, got {other:?}"),
        })
        .collect();
    assert_eq!(
        rows,
        vec![
            ("README.md", None),
            ("src/lib.rs", None),
            ("src/main.rs", None)
        ],
        "one row per file in path order, none carrying a line number"
    );

    // Stepping walks files. From main.rs (the last in path order) `[` lands on lib.rs — one
    // press, one file, whatever line the cursor was on.
    let outcome = step_results(&mut ws, buffer_id, Direction::Backward).await;
    let target = outcome.moved().expect("a captured list steps");
    assert!(
        target.path.as_deref().unwrap().ends_with("src/lib.rs"),
        "got {:?}",
        target.path
    );
    assert_eq!(
        target.position, None,
        "a whole-target entry lands on the buffer's own cursor, not a captured position"
    );
    assert_eq!((target.index, target.total), (2, 3));

    // And `}` has nothing to walk *within* a file — the client toasts "] steps across files".
    let outcome = step_in_file(&mut ws, buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::NoneInFile),
        "whole-target entries have no interior to step, got {outcome:?}"
    );

    drop(server);
}

/// Selecting (or stepping to) a whole-target entry opens the file *where the cursor last was* in
/// it — `view/open` with no `jump_to`, which is exactly what the Files picker's own select
/// does. A file this client has never opened lands at the top.
#[tokio::test]
async fn jumplist_step_to_a_captured_file_restores_its_last_cursor() {
    let (server, mut ws) = setup_grep_workspace().await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Files)
        },
    )
    .await;
    // Leave a cursor in lib.rs, then move to main.rs.
    let lib = open_test_buffer(&mut ws, "src/lib.rs").await;
    set_point_cursor(&mut ws, lib, LogicalPosition { line: 1, col: 3 }).await;
    let main = open_test_buffer(&mut ws, "src/main.rs").await;
    set_point_cursor(&mut ws, main, LogicalPosition { line: 0, col: 0 }).await;
    let _ = capture_files(&mut ws, "src/main.rs").await;

    let target: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id: main,
            direction: Direction::Backward,
            count: 1,
            scope: JumplistStepScope::Full,
            open: true,
        },
    )
    .await;
    let opened = target
        .moved()
        .expect("steps")
        .opened
        .expect("the composite opens the target");
    assert_eq!(opened.buffer_id, lib);
    assert_eq!(
        opened.cursor.position,
        LogicalPosition { line: 1, col: 3 },
        "the open restored this client's own cursor rather than jumping to line 0"
    );
    // The status stamp reads "file k of N" for a whole-target entry: being in the buffer is
    // being on the entry, whatever the cursor does next.
    let rp = opened
        .cursor
        .jumplist_position
        .expect("the current buffer is a captured target");
    assert_eq!((rp.current, rp.total), (2, 3));

    drop(server);
}

/// The view picker captures too, and its one pathless row shape — a scratch buffer — rides as
/// a *buffer* target: stepping to it attaches by id, exactly as selecting it in that picker does.
#[tokio::test]
async fn jumplist_captured_from_the_buffers_picker_includes_scratch_buffers() {
    let (server, mut ws) = setup_grep_workspace().await;
    let main = open_test_buffer(&mut ws, "src/main.rs").await;
    let scratch: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Buffers)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;

    let captured: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        &mut ws,
        &JumplistCaptureParams {
            kind: PickerKind::Buffers,
            item: PickerItem::Buffer {
                buffer_id: main,
                view_id: view_of(main),
                display: "src/main.rs".into(),
                status: Default::default(),
                match_indices: vec![],
                path_index: Some(0),
                relative_path: Some("src/main.rs".into()),
                transient: false,
            },
        },
    )
    .await;
    assert_eq!(
        captured.expect("open buffers capture").total,
        2,
        "the file buffer and the scratch"
    );

    // From the file buffer, `]` steps to the scratch — pathless targets sort after files, and
    // the step identifies it by view id rather than a path.
    let outcome = step_results(&mut ws, main, Direction::Forward).await;
    let target = outcome.moved().expect("steps");
    assert_eq!(target.path, None, "a scratch buffer has no path");
    assert_eq!(target.view_id, Some(scratch.view_id));
    assert_eq!(target.position, None);

    // Stepping back off it reaches the file again — the scratch is a first-class entry, not an
    // outside-the-list origin.
    let outcome = step_results(&mut ws, scratch.buffer_id, Direction::Backward).await;
    let target = outcome.moved().expect("steps");
    assert!(
        target.path.as_deref().unwrap().ends_with("src/main.rs"),
        "got {:?}",
        target.path
    );
    // And forward off the last entry stops, as ever.
    let outcome = step_results(&mut ws, scratch.buffer_id, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "got {outcome:?}"
    );

    drop(server);
}

/// Grep no longer resolves `center_on_cursor`: a fresh open has no hits to frame, so the whole
/// "land on where you are in the restored results" gesture went with the resume
/// (`PickerKind::centers_on_cursor` excludes Grep). The server ignores the field for it even when
/// hits happen to be cached — the changes pickers and the jumplist keep the behaviour.
#[tokio::test]
async fn grep_ignores_center_on_cursor() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 0 }).await;
    let view: aether_protocol::picker::PickerViewResult = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            limit: 30,
            center_on_cursor: Some(buffer_id),
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    assert!(
        view.effective_center_on.is_none(),
        "grep resolves no cursor-anchored highlight"
    );
    assert_eq!(view.effective_offset, 0, "so the window opens at the top");

    drop(server);
}

/// The cursor that comes back from any cursor-returning RPC (here `search_set`) must carry
/// `jumplist_position` — without `wrap_for_response` being called on the response, the status
/// bar would only see the indicator on the next motion.
#[tokio::test]
async fn search_set_response_carries_jumplist_position() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Park the cursor before any hit, then SearchSet with anchor at the second entry's start —
    // the landed selection covers that entry exactly.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "needle".into(),
            anchor: Some(LogicalPosition { line: 1, col: 4 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // search_set parked us on the match — selection covers cols 4..=9, which is the entry.
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 1, col: 4 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 1, col: 9 });
    let rp = r
        .cursor
        .jumplist_position
        .expect("search_set response should be wrapped");
    assert_eq!(rp.current, 2);
    assert_eq!(rp.total, 3);

    drop(server);
}

#[tokio::test]
async fn cursor_jumplist_position_is_none_without_a_capture() {
    // Grep results are cached server-side, but nothing was captured: the stamp must stay off —
    // the cached picker state alone no longer drives the status counter.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let st: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 9 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;
    assert!(st.jumplist_position.is_none());

    drop(server);
}

/// Capture works per-kind: from the workspace changes picker, hunk rows become point-landing
/// entries on their anchor lines, grouped by file, stepping across files like grep hits.
#[tokio::test]
async fn jumplist_capture_from_git_changes_picker() {
    use aether_protocol::viewport::DiffStage;

    // The changes-picker fixture: a committed file modified on disk + an untracked file —
    // one modification hunk in a.rs and one whole-file-add hunk in new.rs.
    let dir = tempfile::tempdir().unwrap();
    git_commit_file(dir.path(), "a.rs", "one\ntwo\nthree\n");
    std::fs::write(dir.path().join("a.rs"), "one\nTWO\nthree\n").unwrap();
    std::fs::write(dir.path().join("new.rs"), "hello\nworld\n").unwrap();
    let dir_path = dir.path().canonicalize().unwrap();
    let server = spawn_for_test("changes-proj", vec![dir_path])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "changes-proj".into(),
            open_last: false,
        },
    )
    .await;
    let buffer_id = open_test_buffer(&mut ws, "a.rs").await;
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::GitChanges)
        },
    )
    .await;
    assert_eq!(view.total_candidates, 2, "one hunk per file");

    // Ctrl-j with the a.rs hunk highlighted. Hunk identity is
    // `(path_index, relative_path, hunk_index)` — the display fields ride empty.
    let captured: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        &mut ws,
        &JumplistCaptureParams {
            kind: PickerKind::GitChanges,
            item: PickerItem::GitChange {
                path_index: 0,
                relative_path: "a.rs".into(),
                hunk_index: 0,
                line: 1,
                stage: DiffStage::Unstaged,
                added: 1,
                removed: 1,
                preview: String::new(),
                match_indices: vec![],
            },
        },
    )
    .await;
    let captured = captured.expect("hunks captured");
    assert_eq!((captured.index, captured.total), (0, 2));

    // Stepping from the top of a.rs lands the hunk entry: a point cursor on the anchor line,
    // stamped as entry 1 of 2.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let target: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id,
            direction: Direction::Forward,
            count: 1,
            scope: JumplistStepScope::Full,
            open: true,
        },
    )
    .await;
    let target = target.moved().expect("captured hunks step");
    let opened = target.opened.expect("composite opens the hunk");
    assert_eq!(opened.cursor.position, LogicalPosition { line: 1, col: 0 });
    assert!(opened.cursor.is_point());
    let rp = opened
        .cursor
        .jumplist_position
        .expect("landed on the hunk entry");
    assert_eq!((rp.current, rp.total), (1, 2));

    // Step forward crosses into the untracked file's whole-file hunk (a point entry).
    let target = step_results(&mut ws, opened.buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("captured hunks step");
    assert!(target.path.as_deref().unwrap().ends_with("new.rs"));
    assert_eq!(target.position, Some(LogicalPosition { line: 0, col: 0 }));
    assert_eq!(target.anchor, None, "hunk entries land a point");
    assert_eq!((target.index, target.total), (2, 2));

    drop(server);
}

/// The Jumplist picker (`Space j`): the captured entries in collapsible groups under their
/// source group headers (one run always open — the selected group; `picker/set_group` moves it); a
/// fuzzy query narrows the entries in place (candidate order preserved); selecting jumps like the
/// source picker's Enter; and `Ctrl-j` re-captures the filtered subset — iterative narrowing.
#[tokio::test]
async fn jumplist_picker_lists_filters_and_recaptures() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Open the picker: the Jumplist is collapsible, so with nothing centred it opens with one
    // selectable `Group` row per captured file and every group shut — the entries hidden behind
    // their headers (but still counted: collapse is view state).
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(view.total_candidates, 3);
    let update = view.update.expect("the view carries its initial window");
    assert_eq!(update.kind, PickerKind::Jumplist);
    let items = update.items();
    assert_eq!(
        group_rows(items),
        vec![
            ("src/lib.rs".to_string(), 1, false),
            ("src/main.rs".to_string(), 2, false),
        ],
        "one header per file, in captured order, all collapsed"
    );
    assert_eq!(items.len(), 2, "2 headers, no entries inline");

    // Expand main.rs: its entries interleave below the header, each carrying its landing line
    // (0-based) for the right-aligned line number — main.rs's hits are on lines 1 and 2.
    let (_row, update) = expand_file_group(&mut ws, PickerKind::Jumplist, "src/main.rs").await;
    let items = update.items();
    assert_eq!(
        items.len(),
        4,
        "two headers + the expanded run's two entries"
    );
    let PickerItem::JumplistEntry {
        index,
        line,
        display,
        ..
    } = &items[2]
    else {
        panic!("expected JumplistEntry, got {:?}", items[2]);
    };
    assert_eq!(*index, 1);
    assert_eq!(*line, Some(1));
    assert!(
        display.contains("needle"),
        "row text is the source line: {display}"
    );
    assert!(
        matches!(
            &items[3],
            PickerItem::JumplistEntry {
                index: 2,
                line: Some(2),
                ..
            }
        ),
        "the run's second entry follows, got {:?}",
        items[3]
    );

    // Enter on a row jumps exactly like the source picker's select (match landed selected).
    let selected: PickerSelectResult = send_request::<PickerSelect>(
        &mut ws,
        &PickerSelectParams {
            kind: PickerKind::Jumplist,
            item: items[3].clone(),
        },
    )
    .await;
    match selected {
        PickerSelectResult::FileAt {
            path,
            position,
            anchor,
        } => {
            assert!(path.ends_with("src/main.rs"));
            assert_eq!(anchor, Some(LogicalPosition { line: 2, col: 4 }));
            assert_eq!(position, LogicalPosition { line: 2, col: 9 });
        }
        other => panic!("expected FileAt, got {other:?}"),
    }

    // Filter to the two main.rs call sites: "();" fuzzy-matches "    needle();" but not
    // "fn needle() {}" (no semicolon).
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Jumplist,
            query: "();".into(),
            generation: 1,
        },
    )
    .await;

    // Ctrl-j re-captures the filtered subset — item index 1 is the original list's second
    // entry (main.rs:1), which becomes the narrowed list's first.
    let captured: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        &mut ws,
        &JumplistCaptureParams {
            kind: PickerKind::Jumplist,
            item: PickerItem::JumplistEntry {
                index: 1,
                // Identity is `index`; line/display are ignored on capture.
                line: None,
                display: String::new(),
                match_indices: vec![],
            },
        },
    )
    .await;
    let captured = captured.expect("the filtered subset captures");
    assert_eq!(captured.total, 2, "narrowed to the two main.rs hits");
    assert_eq!(
        captured.index, 0,
        "the highlighted entry leads the narrowed list"
    );

    // Stepping now walks the narrowed set only: from the top of main.rs → 1, 2, then stops at
    // the end — lib.rs's entry is no longer in the list.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 0, col: 0 }).await;
    let mut current = buffer_id;
    let mut seen = Vec::new();
    for _ in 0..2u64 {
        let target = send_request::<JumplistStep>(
            &mut ws,
            &JumplistStepParams {
                buffer_id: current,
                direction: Direction::Forward,
                count: 1,
                scope: JumplistStepScope::Full,
                open: true,
            },
        )
        .await
        .moved()
        .expect("narrowed list steps");
        assert!(
            target.path.as_deref().unwrap().ends_with("src/main.rs"),
            "lib.rs is out of the narrowed list"
        );
        current = target.opened.expect("composite opens").buffer_id;
        seen.push(target.index);
    }
    assert_eq!(
        seen,
        vec![1, 2],
        "the narrowed list is the two main.rs hits"
    );

    // On the last narrowed entry, forward stops — lib.rs is not reachable by wrapping.
    let outcome: JumplistStepResult = send_request::<JumplistStep>(
        &mut ws,
        &JumplistStepParams {
            buffer_id: current,
            direction: Direction::Forward,
            count: 1,
            scope: JumplistStepScope::Full,
            open: true,
        },
    )
    .await;
    assert!(
        matches!(outcome, JumplistStepResult::AtEnd),
        "narrowed list stops at its end: {outcome:?}"
    );

    drop(server);
}

/// The Jumplist picker's dir/glob chips: path filters narrow the captured entries by their file
/// identity, re-capture bakes the narrowed set in, and the `path_filterable` echo tracks whether
/// the (current) capture is worth scoping at all — true while it spans multiple files, false once
/// narrowed to one.
#[tokio::test]
async fn jumplist_picker_path_filters_narrow_and_recapture_bakes_them_in() {
    // Workspace needle hits: src/lib.rs:0:3, src/main.rs:1:4, src/main.rs:2:4 — two files.
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let _buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Fresh open: the capture spans two files with in-root entries — path-scoping applies.
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(view.total_candidates, 3);
    assert!(
        view.path_filterable,
        "two captured files, both in-root: the dir/glob chips apply"
    );

    // Scope to src/main.rs (a file scope — Jumplist allows them, like Grep): the view narrows
    // to that file's two entries; the pattern is a filter change = query change.
    let filters = PickerFilters {
        directories: vec![ScopedPath {
            path_index: 0,
            relative_path: "src/main.rs".into(),
            is_file: true,
        }],
        ..Default::default()
    };
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: filters.clone(),
            kind: PickerKind::Jumplist,
            query: String::new(),
            generation: 1,
        },
    )
    .await;

    // Re-view (Keep): the filtered window shows one file group with its two entries; the
    // persisted filters echo back, and the flag still describes the *capture* (unchanged).
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(view.filters, filters, "the slot persists the filter set");
    assert!(
        view.path_filterable,
        "the backing capture still spans two files"
    );
    let items = view
        .update
        .expect("the view carries its window")
        .items()
        .to_vec();
    assert_eq!(
        group_rows(&items),
        vec![("src/main.rs".to_string(), 2, false)],
        "the lib.rs group is filtered out entirely"
    );
    assert_eq!(items.len(), 1, "its header, still collapsed");

    // Ctrl-j bakes the filtered set in: the narrowed list is main.rs's two entries.
    let captured: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        &mut ws,
        &JumplistCaptureParams {
            kind: PickerKind::Jumplist,
            item: PickerItem::JumplistEntry {
                index: 1,
                line: Some(0),
                display: String::new(),
                match_indices: vec![],
            },
        },
    )
    .await;
    let captured = captured.expect("the filtered subset captures");
    assert_eq!(captured.total, 2, "the file-scoped entries only");

    // A fresh open of the narrowed list: one file left, so path-scoping no longer applies —
    // the flag is recomputed from the entries on every view.
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(view.total_candidates, 2);
    assert!(
        !view.path_filterable,
        "a single-file capture is all-or-nothing under a path filter"
    );

    drop(server);
}

/// `Space j` opens the Jumplist picker framed on "where you are": `center_on_cursor` resolves
/// the entry at-or-after the cursor (inclusive — the just-jumped-to entry counts), wrapping
/// past the end, and echoes it via `effective_center_on` for the client to highlight.
#[tokio::test]
async fn jumplist_picker_centers_on_the_cursor_nearest_entry() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;
    // Entries: lib.rs:0:3 (#0), main.rs:1:4 (#1), main.rs:2:4 (#2). Cursor before main.rs's
    // first entry → nearest at-or-after is #1.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 1, col: 0 }).await;
    let view_params = |center: Option<u64>| PickerViewParams {
        view_id: None,
        limit: 30,
        center_on_cursor: center,
        ..view_params(PickerKind::Jumplist)
    };
    let view = send_request::<PickerView>(&mut ws, &view_params(Some(buffer_id))).await;
    match view.effective_center_on {
        Some(PickerItem::JumplistEntry { index, .. }) => assert_eq!(index, 1),
        other => panic!("expected a resolved JumplistEntry, got {other:?}"),
    }
    // Framing an entry implies revealing it: the centred entry's group opens expanded, the
    // other file's stays a collapsed header (the collapsible centred-open rule).
    let update = view.update.expect("the view carries its window");
    let expanded: Vec<(&str, bool)> = update
        .items()
        .iter()
        .filter_map(|it| match it {
            PickerItem::Group {
                header: GroupHeader::File { relative_path, .. },
                expanded,
                ..
            } => Some((relative_path.as_str(), *expanded)),
            _ => None,
        })
        .collect();
    assert_eq!(
        expanded,
        vec![("src/lib.rs", false), ("src/main.rs", true)],
        "the cursor-nearest entry's group auto-expands"
    );

    // Past every entry in the buffer's file — and the list — the resolution wraps to #0.
    set_point_cursor(&mut ws, buffer_id, LogicalPosition { line: 3, col: 0 }).await;
    let view = send_request::<PickerView>(&mut ws, &view_params(Some(buffer_id))).await;
    match view.effective_center_on {
        Some(PickerItem::JumplistEntry { index, .. }) => assert_eq!(index, 0),
        other => panic!("expected a resolved JumplistEntry, got {other:?}"),
    }

    drop(server);
}

/// With nothing captured, the Jumplist picker opens empty (the shells' placeholder explains) —
/// cheap discoverability, not an error.
#[tokio::test]
async fn jumplist_picker_opens_empty_without_a_capture() {
    let (server, mut ws) = setup_grep_workspace().await;
    let view = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Jumplist)
        },
    )
    .await;
    assert_eq!(view.total_candidates, 0);

    drop(server);
}

/// Regression carried over from grep navigation: when the cursor's selection covers an entry
/// (the post-jump shape — anchor at the entry's start, position at its end), `[` should skip
/// *past* the current entry rather than landing back on it. The server compares against the
/// selection's leading edge for Backward, not the trailing edge.
#[tokio::test]
async fn jumplist_step_backward_skips_currently_selected_entry() {
    let (server, mut ws) = setup_grep_with_needle_query().await;
    let buffer_id = open_test_buffer(&mut ws, "src/main.rs").await;
    let _ = capture_grep_results(&mut ws, "src/lib.rs", 0, 3).await;

    // Simulate the post-jump cursor: selection covers the "needle" match on line 1 (cols 4–9,
    // since "needle" is 6 chars; inclusive cursor lands on the last char, col 9; anchor at
    // the start of the match, col 4).
    let _: CursorState = send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line: 1, col: 9 },
            anchor: LogicalPosition { line: 1, col: 4 },
        },
    )
    .await;

    // Backward must walk past this entry (start at col 4 == selection's leading edge) and land
    // on the previous entry in src/lib.rs:0:3.
    let target = step_results(&mut ws, buffer_id, Direction::Backward)
        .await
        .moved()
        .expect("backward should step past the current entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/lib.rs"));
    assert_eq!(target.anchor, Some(LogicalPosition { line: 0, col: 3 }));

    // Forward from the same selection skips past the trailing edge (col 9) and lands on the
    // next entry at line 2 col 4.
    let target = step_results(&mut ws, buffer_id, Direction::Forward)
        .await
        .moved()
        .expect("forward should step past the current entry");
    assert!(target.path.as_deref().unwrap().ends_with("src/main.rs"));
    assert_eq!(target.anchor, Some(LogicalPosition { line: 2, col: 4 }));

    drop(server);
}

/// A workspace switch wipes the captured list along with the picker state — its entries point
/// into the prior workspace's files, so `]` afterwards is a no-op until the next capture.
/// (Re-activating the *same* workspace is not a switch and preserves it, like pickers.)
#[tokio::test]
async fn workspace_switch_wipes_the_captured_results() {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::write(dir_path.join("hay.txt"), "a needle here\n").unwrap();
    let server = spawn_for_test_multi(vec![
        ("p1".into(), vec![dir_path.clone()]),
        ("p2".into(), vec![dir_path]),
    ])
    .await
    .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p1".into(),
            open_last: false,
        },
    )
    .await;

    // Grep for the needle and capture the single hit.
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            view_id: None,
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;
    let buffer_id = open_test_buffer(&mut ws, "hay.txt").await;
    let _ = capture_grep_results(&mut ws, "hay.txt", 0, 2).await;
    assert!(
        step_results(&mut ws, buffer_id, Direction::Forward)
            .await
            .moved()
            .is_some(),
        "captured list steps before the switch"
    );

    // Switching to a different workspace tears the per-client state down, results included.
    let activated: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p2".into(),
            open_last: true,
        },
    )
    .await;
    let landed = activated.opened.expect("workspace lands on a buffer");
    assert!(
        matches!(
            step_results(&mut ws, landed.buffer_id, Direction::Forward).await,
            JumplistStepResult::Empty
        ),
        "the captured list did not survive the workspace switch"
    );

    drop(server);
}
