// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.

mod common;

use common::*;

// -------- transient buffers -----------------------------------------------------------------
//
// A buffer opened with `transient: true` (picker / goto-def navigation, the bootstrap scratch)
// closes itself once no viewport shows it anymore — switching away is what "hides" it, since
// `viewport/subscribe` supersedes the client's previous viewport. The first edit, a save, or an
// explicit `buffer/open { transient: false }` (pin) promotes it to a normal buffer.

async fn setup_transient_workspace() -> (aether_server::ServerHandle, Ws) {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::write(dir_path.join("a.txt"), "alpha\n").unwrap();
    std::fs::write(dir_path.join("b.txt"), "beta\n").unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws)
}

// ---- buffer/content + buffer/changed (markdown reading view support) ---------------------------

/// `buffer/open` params for a file in the transient-workspace workspace.
// ---- buffer/content + buffer/changed (markdown reading view support) ----------------------------

#[tokio::test]
async fn buffer_content_returns_full_text_and_tracks_revision() {
    let (_server, mut ws, buffer_id) = setup_with_buffer("alpha\nbeta\ngamma\n").await;

    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "alpha\nbeta\ngamma\n");

    // An edit bumps the revision; the next fetch reports it alongside the new text.
    let r: EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id,
            text: "X".into(),
            select_pasted: false,
            replace_selection: false,
            at: Some(SelectionEdge::Start),
        },
    )
    .await;
    let c2: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c2.revision, r.revision);
    assert!(c2.revision > c.revision);
    assert_eq!(c2.text, "Xalpha\nbeta\ngamma\n");
}

#[tokio::test]
async fn buffer_content_unknown_buffer_errors() {
    let (_server, mut ws, _buffer_id) = setup_with_buffer("x\n").await;
    let msg =
        send_request_expect_err::<BufferContent>(&mut ws, &BufferContentParams { buffer_id: 9999 })
            .await;
    assert!(
        msg.to_lowercase().contains("buffer"),
        "unexpected error message: {msg}"
    );
}

/// `syntax/highlight_snippet`: stateless tree-sitter over a snippet — real captures for a known
/// language, the fence alias table resolving short names, and an empty (not error) result for an
/// unknown language.
#[tokio::test]
async fn highlight_snippet_uses_registry_and_aliases() {
    use aether_protocol::syntax::{SyntaxHighlightSnippet, SyntaxHighlightSnippetParams};
    let (_server, mut ws, _buffer_id) = setup_with_buffer("x\n").await;

    let r = send_request::<SyntaxHighlightSnippet>(
        &mut ws,
        &SyntaxHighlightSnippetParams {
            language: "rust".into(),
            text: "fn main() { let s = \"hi\"; }".into(),
        },
    )
    .await;
    assert!(
        r.highlights.iter().any(|h| h.kind == "keyword"),
        "rust snippet yields keyword captures, got {:?}",
        r.highlights
    );
    assert!(
        r.highlights.iter().any(|h| h.kind.starts_with("string")),
        "rust snippet yields string captures"
    );

    // Fence short names resolve through the same alias table (`rs` → rust).
    let r = send_request::<SyntaxHighlightSnippet>(
        &mut ws,
        &SyntaxHighlightSnippetParams {
            language: "rs".into(),
            text: "fn x() {}".into(),
        },
    )
    .await;
    assert!(!r.highlights.is_empty(), "alias resolves");

    // Unknown language: empty, not an error — callers fire-and-adopt.
    let r = send_request::<SyntaxHighlightSnippet>(
        &mut ws,
        &SyntaxHighlightSnippetParams {
            language: "no-such-lang".into(),
            text: "whatever".into(),
        },
    )
    .await;
    assert!(r.highlights.is_empty());

    // The client sends the fence's full info string; metadata after the language — space- or
    // comma-separated (```rust ignore / ```rust,no_run) — doesn't defeat resolution.
    for (_, info) in [(13, "rust ignore"), (14, "rust,no_run")] {
        let r = send_request::<SyntaxHighlightSnippet>(
            &mut ws,
            &SyntaxHighlightSnippetParams {
                language: info.into(),
                text: "fn x() {}".into(),
            },
        )
        .await;
        assert!(
            r.highlights.iter().any(|h| h.kind == "keyword"),
            "info string {info:?} should still resolve to rust, got {:?}",
            r.highlights
        );
    }
}

/// Read frames until a change signal (`buffer/changed` or `viewport/lines_changed`) arrives;
/// returns which one, plus its params. Used to pin *which* branch of the edit-push range gate
/// fired, which `expect_notification`'s skip-unrelated behaviour can't distinguish.
async fn next_change_signal(ws: &mut Ws) -> (String, serde_json::Value) {
    loop {
        let text = next_text(ws).await;
        let inbound: ClientInbound = serde_json::from_str(&text).expect("parseable");
        if let ClientInbound::Notification(n) = inbound {
            if n.method == BufferChanged::NAME
                || n.method == aether_protocol::viewport::ViewportLinesChanged::NAME
            {
                return (n.method, n.params);
            }
        }
    }
}

/// A typed edit outside another client's pushed window sends that client the revision-only
/// `buffer/changed` — the `viewport/lines_changed` range gate would otherwise leave a
/// whole-document consumer (the markdown reading view) unaware of the mutation. An edit inside
/// the window still sends the full `viewport/lines_changed`.
#[tokio::test]
async fn out_of_window_edit_pushes_buffer_changed() {
    // 40 lines, so a 10-row viewport at the top leaves plenty of buffer outside its range.
    let content: String = (0..40).map(|i| format!("line {i}\n")).collect();
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("doc.md"), &content).unwrap();
    let dir_path = dir.path().to_path_buf();
    let server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();

    // Client 1: the editor (no viewport — edits don't need one).
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("doc.md", None)).await;
    let buffer_id = open.buffer_id;

    // Client 2: the reader, viewport pinned to the top 10 rows.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let _: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws2, &attach_open_params(buffer_id, None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws2, &transient_sub_params(buffer_id)).await;

    // Client 1 edits far below client 2's window → client 2 gets the revision-only signal.
    let _: CursorState = send_request::<CursorMove>(
        &mut ws,
        &CursorMoveParams {
            buffer_id,
            motion: Motion::Goto {
                position: LogicalPosition { line: 35, col: 0 },
            },
            extend_selection: false,
        },
    )
    .await;
    let r: EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id,
            text: "!".into(),
            select_pasted: false,
            replace_selection: false,
            at: Some(SelectionEdge::Start),
        },
    )
    .await;
    let (method, params) = next_change_signal(&mut ws2).await;
    assert_eq!(
        method,
        BufferChanged::NAME,
        "out-of-window edit → buffer/changed"
    );
    let changed: BufferChangedParams = serde_json::from_value(params).unwrap();
    assert_eq!(changed.buffer_id, buffer_id);
    assert_eq!(changed.revision, r.revision);

    // Client 1 edits inside client 2's window → the full window render as before.
    let _: CursorState = send_request::<CursorMove>(
        &mut ws,
        &CursorMoveParams {
            buffer_id,
            motion: Motion::Goto {
                position: LogicalPosition { line: 0, col: 0 },
            },
            extend_selection: false,
        },
    )
    .await;
    let r2: EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id,
            text: "!".into(),
            select_pasted: false,
            replace_selection: false,
            at: Some(SelectionEdge::Start),
        },
    )
    .await;
    let (method, params) = next_change_signal(&mut ws2).await;
    assert_eq!(
        method,
        aether_protocol::viewport::ViewportLinesChanged::NAME,
        "in-window edit → viewport/lines_changed"
    );
    let lc: aether_protocol::viewport::ViewportLinesChangedParams =
        serde_json::from_value(params).unwrap();
    assert_eq!(lc.revision, r2.revision);

    drop(server);
}

/// Plain HTTP GET against the test server (the ws port doubles as the HTTP port), returning
/// `(status_line, headers, body)`. Carries a loopback `Host` header — the server's rebinding
/// defense rejects requests without one.
async fn http_get(ws_url: &str, path: &str) -> (String, String, Vec<u8>) {
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    let authority = ws_url
        .trim_start_matches("ws://")
        .split('/')
        .next()
        .expect("authority");
    let mut stream = tokio::net::TcpStream::connect(authority)
        .await
        .expect("connect");
    let req = format!("GET {path} HTTP/1.1\r\nHost: {authority}\r\nConnection: close\r\n\r\n");
    stream.write_all(req.as_bytes()).await.unwrap();
    let mut buf = Vec::new();
    stream.read_to_end(&mut buf).await.unwrap();
    let header_end = buf
        .windows(4)
        .position(|w| w == b"\r\n\r\n")
        .map(|p| p + 4)
        .unwrap_or(buf.len());
    let head = String::from_utf8_lossy(&buf[..buf.len().min(header_end)]).to_string();
    let status = head.lines().next().unwrap_or_default().to_string();
    (status, head, buf[header_end..].to_vec())
}

/// The web reading view's image route: serves files relative to a buffer's directory, confined to
/// the buffer's workspace root after canonicalization — `.` and symlink escapes 404, as do unknown
/// buffers and non-image extensions.
#[tokio::test]
async fn buffer_asset_route_serves_and_confines() {
    let dir = tempfile::tempdir().unwrap();
    let outside = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("doc.md"), "![d](img.png)\n").unwrap();
    std::fs::write(dir.path().join("img.png"), b"PNGDATA").unwrap();
    std::fs::write(outside.path().join("secret.png"), b"SECRET").unwrap();
    #[cfg(unix)]
    std::os::unix::fs::symlink(
        outside.path().join("secret.png"),
        dir.path().join("leak.png"),
    )
    .unwrap();
    let dir_path = dir.path().to_path_buf();
    let outside_path = outside.path().to_path_buf();

    let server = spawn_for_test("test-proj", vec![dir_path.clone()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("doc.md", None)).await;
    let id = open.buffer_id;
    let url = server.ws_url();

    // The happy path: an image beside the document — with the hardening headers (nosniff pins
    // the type; `sandbox` neuters scripts when an SVG asset is opened as a page, which would
    // otherwise execute same-origin with the editor client).
    let (status, head, body) = http_get(&url, &format!("/asset/{id}/img.png")).await;
    assert!(status.contains("200"), "got {status}");
    assert_eq!(body, b"PNGDATA");
    assert!(
        head.contains("X-Content-Type-Options: nosniff"),
        "asset responses carry nosniff, got:\n{head}"
    );
    assert!(
        head.contains("Content-Security-Policy: sandbox"),
        "asset responses carry CSP sandbox, got:\n{head}"
    );

    // A parent-relative path that stays inside the root is legitimate (the web shell encodes
    // the whole relative path as one segment, so the `..` reaches the server un-collapsed).
    std::fs::create_dir_all(dir_path.join("docs")).unwrap();
    std::fs::write(dir_path.join("docs/nested.md"), "![up](../img.png)\n").unwrap();
    let nested: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("docs/nested.md", None)).await;
    let (status, _, body) =
        http_get(&url, &format!("/asset/{}/..%2Fimg.png", nested.buffer_id)).await;
    assert!(
        status.contains("200"),
        "in-root ..%2F must serve, got {status}"
    );
    assert_eq!(body, b"PNGDATA");

    // A root-relative source (leading `/`, GitHub semantics) resolves against the buffer's
    // containing root, not the filesystem.
    let (status, _, body) =
        http_get(&url, &format!("/asset/{}/%2Fimg.png", nested.buffer_id)).await;
    assert!(
        status.contains("200"),
        "root-relative %2F must serve, got {status}"
    );
    assert_eq!(body, b"PNGDATA");

    // …and it is confined exactly like a relative path.
    let root_escape = format!(
        "/asset/{id}/%2F..%2F{}%2Fsecret.png",
        outside_path.file_name().unwrap().to_string_lossy()
    );
    let (status, _, _) = http_get(&url, &root_escape).await;
    assert!(
        status.contains("404"),
        "root-relative traversal must 404, got {status}"
    );

    // `..` traversal out of the root → 404 (canonical-prefix check).
    let rel_escape = format!(
        "/asset/{id}/..%2F{}%2Fsecret.png",
        outside_path.file_name().unwrap().to_string_lossy()
    );
    let (status, _, _) = http_get(&url, &rel_escape).await;
    assert!(status.contains("404"), "traversal must 404, got {status}");

    // A symlink pointing outside the root → 404 after canonicalization.
    #[cfg(unix)]
    {
        let (status, _, body) = http_get(&url, &format!("/asset/{id}/leak.png")).await;
        assert!(
            status.contains("404"),
            "symlink escape must 404, got {status} ({:?})",
            String::from_utf8_lossy(&body)
        );
    }

    // Unknown buffer and non-image extensions → 404.
    let (status, _, _) = http_get(&url, "/asset/9999/img.png").await;
    assert!(
        status.contains("404"),
        "unknown buffer must 404, got {status}"
    );
    let (status, _, _) = http_get(&url, &format!("/asset/{id}/doc.md")).await;
    assert!(status.contains("404"), "non-image must 404, got {status}");

    drop(server);
}

/// `buffer/open` params attaching to an existing buffer by id.
fn attach_open_params(buffer_id: u64, transient: Option<bool>) -> BufferOpenParams {
    BufferOpenParams {
        buffer_id: Some(buffer_id),
        path_index: None,
        relative_path: None,
        language: None,
        create_if_missing: false,
        jump_to: None,
        transient,
        ..Default::default()
    }
}

/// A dropped connection — a closed native-client tab, a closed browser tab — hides everything
/// that client was showing: its viewed transients orphan-close on disconnect like any other
/// hide, so Ctrl-t/Ctrl-w tab churn doesn't leave scratch buffers behind.
#[tokio::test]
async fn transient_buffer_closes_on_disconnect() {
    let (server, mut ws) = setup_transient_workspace().await;
    let scratch: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            buffer_id: None,
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            transient: Some(true),
            ..Default::default()
        },
    )
    .await;
    assert!(scratch.transient, "fresh scratch opened transient");
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(scratch.buffer_id)).await;
    drop(ws); // the tab closes its connection

    // The server processes the close on its own task, so wait for it to land rather than guessing
    // at how long it takes.
    wait_for_client_count(&server, 0).await;

    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let err = send_request_expect_err::<BufferOpen>(
        &mut ws2,
        &attach_open_params(scratch.buffer_id, None),
    )
    .await;
    assert!(
        err.to_lowercase().contains("buffer"),
        "attaching to the orphaned transient should fail (got: {err})"
    );
}

/// The core lifecycle: a transient buffer dies when the client's viewport moves elsewhere.
#[tokio::test]
async fn transient_buffer_closes_when_hidden() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    assert!(a.transient, "open with transient:true reports the flag");
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;

    // Switch to b: open + subscribe. The subscribe supersedes a's viewport, hiding a → closed.
    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    assert!(!b.transient, "open without the flag is permanent");
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;

    let err =
        send_request_expect_err::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None))
            .await;
    assert!(
        err.contains("unknown buffer_id"),
        "hidden transient buffer should be closed, got: {err}"
    );
    drop(server);
}

/// A buffer opened without the flag survives being hidden — the pre-transient behavior.
#[tokio::test]
async fn permanent_buffer_survives_hiding() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;
    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;
    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert_eq!(again.buffer_id, a.buffer_id);
    drop(server);
}

/// The first edit promotes: an edited transient buffer survives being hidden.
#[tokio::test]
async fn edit_promotes_transient_buffer() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;
    let _: EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id: a.buffer_id,
            text: "x".into(),
            select_pasted: false,
            replace_selection: false,
            at: None,
        },
    )
    .await;

    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;

    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(!again.transient, "the edit promoted the buffer");
    drop(server);
}

/// Explicit pin (`buffer/open { transient: false }`) promotes without an edit.
#[tokio::test]
async fn pin_promotes_transient_buffer() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;

    let pinned: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, Some(false))).await;
    assert!(!pinned.transient, "pin reports the flag cleared");

    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;
    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert_eq!(again.buffer_id, a.buffer_id);
    drop(server);
}

/// A clean save (save-as flow on an untouched preview) also promotes.
#[tokio::test]
async fn save_promotes_transient_buffer() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;
    let _: BufferSaveResult = send_request::<BufferSave>(
        &mut ws,
        &BufferSaveParams {
            buffer_id: a.buffer_id,
            path_index: None,
            relative_path: None,
            overwrite: false,
        },
    )
    .await;

    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;
    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(!again.transient);
    drop(server);
}

/// Opening an already-open (permanent) buffer with `transient: true` never demotes it.
#[tokio::test]
async fn transient_open_does_not_demote_existing_buffer() {
    let (server, mut ws) = setup_transient_workspace().await;
    let first: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", None)).await;
    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    assert_eq!(again.buffer_id, first.buffer_id);
    assert!(!again.transient, "an open never demotes a permanent buffer");
    drop(server);
}

/// `buffer/set_transient` flips the flag *both* ways — including the deliberate demotion
/// (permanent → transient) that `buffer/open` refuses. Drives the `Space k` keep toggle.
#[tokio::test]
async fn set_transient_flips_the_flag_both_ways() {
    let (server, mut ws) = setup_transient_workspace().await;
    // Open a.txt permanent (a fresh non-transient open ⇒ transient: false).
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", None)).await;
    assert!(!a.transient, "a fresh non-transient open is permanent");
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;

    // Demote it to transient — the thing `buffer/open` can't do.
    let demoted: BufferSetTransientResult = send_request::<BufferSetTransient>(
        &mut ws,
        &BufferSetTransientParams {
            buffer_id: a.buffer_id,
            transient: true,
        },
    )
    .await;
    assert!(
        demoted.transient,
        "set_transient(true) reports the flag set"
    );
    // Reopening (attach, no intent) reflects the new server-side state.
    let reopen: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(reopen.transient, "the demotion stuck server-side");

    // Pin it permanent again.
    let pinned: BufferSetTransientResult = send_request::<BufferSetTransient>(
        &mut ws,
        &BufferSetTransientParams {
            buffer_id: a.buffer_id,
            transient: false,
        },
    )
    .await;
    assert!(!pinned.transient);
    let reopen2: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(!reopen2.transient, "pinned back to permanent");

    drop(server);
}

/// The bootstrap placeholder: a transient scratch closes once a real file replaces it.
#[tokio::test]
async fn transient_scratch_closes_when_replaced_by_file() {
    let (server, mut ws) = setup_transient_workspace().await;
    let scratch: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            buffer_id: None,
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            transient: Some(true),
            ..Default::default()
        },
    )
    .await;
    assert!(scratch.transient);
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(scratch.buffer_id)).await;

    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;

    let err = send_request_expect_err::<BufferOpen>(
        &mut ws,
        &attach_open_params(scratch.buffer_id, None),
    )
    .await;
    assert!(
        err.contains("unknown buffer_id"),
        "hidden transient scratch should be closed, got: {err}"
    );
    drop(server);
}

/// A second client's viewport keeps a transient buffer alive; it closes only once the *last*
/// viewer leaves.
#[tokio::test]
async fn transient_buffer_survives_while_another_client_views_it() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;

    // Client 2 starts viewing the same buffer.
    let mut ws2 = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let a2: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws2, &file_open_params("a.txt", Some(true))).await;
    assert_eq!(a2.buffer_id, a.buffer_id);
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws2, &transient_sub_params(a.buffer_id)).await;

    // Client 1 switches away — buffer stays (client 2 still shows it).
    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;
    let still: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(still.transient, "still transient while client 2 views it");

    // Client 2 switches away too — now it's hidden everywhere and closes. (Client 1's attach
    // above didn't resubscribe a viewport, so its viewport is still on b.)
    let b2: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws2, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws2, &transient_sub_params(b2.buffer_id)).await;
    let err =
        send_request_expect_err::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None))
            .await;
    assert!(
        err.contains("unknown buffer_id"),
        "expected close once the last viewer left, got: {err}"
    );
    drop(server);
}

/// Nav back into a since-closed transient buffer reopens it by path — transient again, so
/// walking history doesn't re-accumulate buffers.
#[tokio::test]
async fn nav_back_reopens_closed_transient_as_transient() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;
    // Switch to b.txt, recording the jump origin (a) on the open itself — the composite the TUI
    // uses for a picker-driven switch (`record_nav_from`, composite A).
    let b: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            record_nav_from: Some(a.buffer_id),
            ..file_open_params("b.txt", None)
        },
    )
    .await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;

    // a is gone; nav/back reopens it by path, transient again.
    let res: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: b.buffer_id,
            direction: Direction::Backward,
        },
    )
    .await;
    let target = res.target.expect("nav/back has an entry");
    assert_ne!(target.buffer_id, a.buffer_id, "reopened under a fresh id");
    assert!(target.transient, "nav reopen is a revisit, not a keep");
    drop(server);
}

/// A user-initiated reload promotes: it's a keep-this-buffer signal, like save. (The watcher's
/// silent reload deliberately doesn't.)
#[tokio::test]
async fn reload_promotes_transient_buffer() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", Some(true))).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(a.buffer_id)).await;
    let _: BufferReloadResult = send_request::<BufferReload>(
        &mut ws,
        &BufferReloadParams {
            buffer_id: a.buffer_id,
            force: false,
        },
    )
    .await;

    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", None)).await;
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;
    let again: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &attach_open_params(a.buffer_id, None)).await;
    assert!(!again.transient, "the reload promoted the buffer");
    drop(server);
}

/// The buffers picker carries the transient flag so clients can italicise preview rows.
#[tokio::test]
async fn buffers_picker_reports_transient_flag() {
    let (server, mut ws) = setup_transient_workspace().await;
    let a: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("a.txt", None)).await;
    let b: BufferOpenResult =
        send_request::<BufferOpen>(&mut ws, &file_open_params("b.txt", Some(true))).await;
    // Keep the transient buffer visible so it survives until the picker reads it.
    let _: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(&mut ws, &transient_sub_params(b.buffer_id)).await;

    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            limit: 30,
            ..view_params(PickerKind::Buffers)
        },
    )
    .await;
    let update: PickerUpdateParams = expect_notification::<PickerUpdate>(&mut ws).await;
    let flags: Vec<(u64, bool)> = update
        .items()
        .iter()
        .map(|i| {
            let PickerItem::Buffer {
                buffer_id,
                transient,
                ..
            } = i
            else {
                panic!("expected Buffer, got {i:?}")
            };
            (*buffer_id, *transient)
        })
        .collect();
    assert!(
        flags.contains(&(b.buffer_id, true)),
        "transient buffer flagged: {flags:?}"
    );
    assert!(
        flags.contains(&(a.buffer_id, false)),
        "permanent buffer unflagged: {flags:?}"
    );
    drop(server);
}

// ---- block edits (markdown reading view) -----------------------------

#[tokio::test]
async fn move_block_swaps_siblings_selects_the_moved_text_and_undoes_atomically() {
    use aether_protocol::input::{BlockUnit, InputMoveBlock, MoveBlockParams};
    let (server, mut ws, buffer_id) = setup_with_buffer("# T\n\nAlpha.\n\nBeta.\n\nGamma.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    // Reading position on "Alpha." (line 2).
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputMoveBlock>(
        &mut ws,
        &MoveBlockParams {
            buffer_id,
            direction: VerticalDirection::Down,
            unit: BlockUnit::Block,
        },
    )
    .await;
    assert!(r.applied);
    // The moved block lands selected whole-line at its new position (line 4).
    assert_eq!(r.cursor.anchor, p(4, 0));
    assert_eq!(r.cursor.position.line, 4);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "# T\n\nBeta.\n\nAlpha.\n\nGamma.\n");
    // ONE undo reverses the whole move — the swap was a single transaction.
    let u: UndoResult = send_request::<EditUndo>(
        &mut ws,
        &UndoRedoParams {
            buffer_id,
            count: 1,
            collapse_selection: false,
        },
    )
    .await;
    assert!(u.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "# T\n\nAlpha.\n\nBeta.\n\nGamma.\n");
    drop(server);
}

#[tokio::test]
async fn move_block_on_a_focused_container_moves_the_whole_container() {
    use aether_protocol::input::{BlockUnit, InputMoveBlock, MoveBlockParams};
    // A `j`/`k` walk parks the point on the quote's own `>` — the reading view lights the
    // whole quote there, so the move must take the quote and its nested children, not the
    // quote's single-line first paragraph (which used to win the line-extent resolution).
    let (server, mut ws, buffer_id) =
        setup_with_buffer("Intro.\n\n> Outer.\n>\n> > Inner.\n\nOutro.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputMoveBlock>(
        &mut ws,
        &MoveBlockParams {
            buffer_id,
            direction: VerticalDirection::Down,
            unit: BlockUnit::Block,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "Intro.\n\nOutro.\n\n> Outer.\n>\n> > Inner.\n");
    // Point in, point out: parked on the quote at its new position.
    assert_eq!(r.cursor.anchor, p(4, 0));
    assert_eq!(r.cursor.position, p(4, 0));
    drop(server);
}

#[tokio::test]
async fn move_block_at_the_end_is_a_quiet_noop() {
    use aether_protocol::input::{BlockUnit, InputMoveBlock, MoveBlockParams};
    let (server, mut ws, buffer_id) = setup_with_buffer("Alpha.\n\nBeta.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputMoveBlock>(
        &mut ws,
        &MoveBlockParams {
            buffer_id,
            direction: VerticalDirection::Down,
            unit: BlockUnit::Block,
        },
    )
    .await;
    assert!(!r.applied);
    assert_eq!(r.reason, None, "boundary no-op stays quiet");
    drop(server);
}

#[tokio::test]
async fn move_paragraph_unit_works_on_plain_text() {
    use aether_protocol::input::{BlockUnit, InputMoveBlock, MoveBlockParams};
    let (server, mut ws, buffer_id) = setup_with_buffer("fn a() {\n}\n\nfn b() {\n}\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(0, 0), p(0, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputMoveBlock>(
        &mut ws,
        &MoveBlockParams {
            buffer_id,
            direction: VerticalDirection::Down,
            unit: BlockUnit::Paragraph,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "fn b() {\n}\n\nfn a() {\n}\n");
    drop(server);
}

#[tokio::test]
async fn delete_block_cuts_around_and_paste_block_restores() {
    use aether_protocol::input::{InputDeleteBlock, InputPasteBlock, PasteBlockParams};
    let (server, mut ws, buffer_id) = setup_with_buffer("Alpha.\n\nBeta.\n\nGamma.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputDeleteBlock>(&mut ws, &BufferOnlyParams { buffer_id }).await;
    assert!(r.applied);
    assert_eq!(r.text.as_deref(), Some("Beta.\n"), "clipboard payload");
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "Alpha.\n\nGamma.\n",
        "separator went with the block"
    );
    // Cursor landed on the block now filling the gap; paste the cut text back before it.
    let r: aether_protocol::input::BlockEditResult = send_request::<InputPasteBlock>(
        &mut ws,
        &PasteBlockParams {
            buffer_id,
            text: "Beta.\n".into(),
            replace: false,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "Alpha.\n\nBeta.\n\nGamma.\n",
        "cut → paste round-trips"
    );
    drop(server);
}

#[tokio::test]
async fn block_depth_demotes_headings_and_quotes_paragraphs() {
    use aether_protocol::input::{BlockDepthParams, InputBlockDepth};
    let (server, mut ws, buffer_id) = setup_with_buffer("## Head\n\nBody.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(0, 0), p(0, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputBlockDepth>(
        &mut ws,
        &BlockDepthParams {
            buffer_id,
            deeper: true,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "### Head\n\nBody.\n");
    // A paragraph has no level to change, so "deeper" means one more blockquote level — a
    // quote is a container in the block tree, so wrapping is genuinely a step down.
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputBlockDepth>(
        &mut ws,
        &BlockDepthParams {
            buffer_id,
            deeper: true,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "### Head\n\n> Body.\n");
    // And `Ctrl-h` peels it back off.
    let r: aether_protocol::input::BlockEditResult = send_request::<InputBlockDepth>(
        &mut ws,
        &BlockDepthParams {
            buffer_id,
            deeper: false,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "### Head\n\nBody.\n");
    drop(server);
}

#[tokio::test]
async fn move_block_past_a_list_that_interrupts_it_keeps_the_block_separate() {
    use aether_protocol::input::{BlockUnit, InputMoveBlock, MoveBlockParams};
    // A list may follow a paragraph with no blank line between them. Reversing that adjacency
    // without restoring a separator would leave the paragraph re-parsed as a lazy continuation
    // of the last list item — appended to it, and unmovable from there.
    let (server, mut ws, buffer_id) = setup_with_buffer("Intro.\n- a\n- b\n\nOutro.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(0, 0), p(0, 0), Granularity::Char).await;
    let down = || MoveBlockParams {
        buffer_id,
        direction: VerticalDirection::Down,
        unit: BlockUnit::Block,
    };
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputMoveBlock>(&mut ws, &down()).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- a\n- b\n\nIntro.\n\nOutro.\n");
    // Still a top-level block: it keeps moving instead of being stuck inside the list.
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputMoveBlock>(&mut ws, &down()).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- a\n- b\n\nOutro.\n\nIntro.\n");
    drop(server);
}

#[tokio::test]
async fn block_edits_refuse_front_matter_with_a_reason() {
    use aether_protocol::input::{InputDeleteBlock, InputPasteBlock, PasteBlockParams};
    // Front matter is only front matter while it opens the file: cutting it, replacing it or
    // pushing a block above it all refuse with a toastable reason.
    let (server, mut ws, buffer_id) = setup_with_buffer("---\nkey: v\n---\n\nBody.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(0, 0), p(0, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputDeleteBlock>(&mut ws, &BufferOnlyParams { buffer_id }).await;
    assert!(!r.applied);
    assert_eq!(r.reason.as_deref(), Some("Front matter stays at the top"));
    assert_eq!(r.text, None, "nothing reached the clipboard");
    let r: aether_protocol::input::BlockEditResult = send_request::<InputPasteBlock>(
        &mut ws,
        &PasteBlockParams {
            buffer_id,
            text: "Injected.".into(),
            replace: false,
        },
    )
    .await;
    assert!(!r.applied);
    assert!(r.reason.is_some());
    // Opening *above* it would push it down; opening below is an ordinary paragraph after a
    // legal block, so only one direction refuses.
    use aether_protocol::input::{InputOpenBlock, OpenBlockParams};
    let r: aether_protocol::input::BlockEditResult = send_request::<InputOpenBlock>(
        &mut ws,
        &OpenBlockParams {
            buffer_id,
            above: true,
        },
    )
    .await;
    assert!(!r.applied);
    assert_eq!(r.reason.as_deref(), Some("Front matter stays at the top"));
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "---\nkey: v\n---\n\nBody.\n", "document untouched");
    let r: aether_protocol::input::BlockEditResult = send_request::<InputOpenBlock>(
        &mut ws,
        &OpenBlockParams {
            buffer_id,
            above: false,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "---\nkey: v\n---\n\n\n\nBody.\n");
    drop(server);
}

#[tokio::test]
async fn open_block_continues_a_list_and_lands_where_the_typing_goes() {
    use aether_protocol::input::{InputOpenBlock, InputText, InputTextParams, OpenBlockParams};
    // Why this op is resolved against the parse at all: a paragraph opened at column 0 inside a
    // list splits the list in two. The new line has to carry the marker, and the caret has to
    // come back past it, so the next thing typed is the item's text.
    let (server, mut ws, buffer_id) = setup_with_buffer("- one\n- two\n- three\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(1, 2), p(1, 2), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult = send_request::<InputOpenBlock>(
        &mut ws,
        &OpenBlockParams {
            buffer_id,
            above: false,
        },
    )
    .await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- one\n- two\n- \n- three\n", "a sibling, tight");
    assert_eq!(r.cursor.position, p(2, 2), "parked past the new marker");
    assert_eq!(r.cursor.anchor, r.cursor.position, "collapsed for Insert");
    // The client enters Insert on that landing, so what it types has to complete the item.
    let _: aether_protocol::input::EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id,
            text: "two and a half".into(),
            select_pasted: false,
            replace_selection: false,
            at: None,
        },
    )
    .await;
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- one\n- two\n- two and a half\n- three\n");
    drop(server);
}

#[tokio::test]
async fn open_block_reads_the_block_it_opens_from() {
    use aether_protocol::input::{InputOpenBlock, OpenBlockParams};
    // A task item's sibling starts unchecked; a quote's new paragraph stays quoted (blank line
    // included, or the quote would end there); a heading begets body text, not a heading.
    let (server, mut ws, buffer_id) =
        setup_with_buffer("# Title\n\n- [x] done\n\n> One.\n>\n> Two.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    let open = |above: bool| OpenBlockParams { buffer_id, above };
    set_snapped(&mut ws, buffer_id, p(2, 0), p(2, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputOpenBlock>(&mut ws, &open(false)).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text,
        "# Title\n\n- [x] done\n- [ ] \n\n> One.\n>\n> Two.\n"
    );
    assert_eq!(r.cursor.position, p(3, 6), "past marker and empty box");

    set_snapped(&mut ws, buffer_id, p(5, 2), p(5, 2), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputOpenBlock>(&mut ws, &open(false)).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "# Title\n\n- [x] done\n- [ ] \n\n> One.\n>\n> \n>\n> Two.\n",
        "still inside the quote, separator included"
    );
    assert_eq!(r.cursor.position, p(7, 2), "past the quote marker");

    // The heading: the blank-pair paragraph shape, unchanged from before the op knew about
    // block types.
    set_snapped(&mut ws, buffer_id, p(0, 0), p(0, 0), Granularity::Char).await;
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputOpenBlock>(&mut ws, &open(false)).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "# Title\n\n\n\n- [x] done\n- [ ] \n\n> One.\n>\n> \n>\n> Two.\n",
        "a paragraph, not another heading"
    );
    assert_eq!(r.cursor.position, p(2, 0));
    drop(server);
}

#[tokio::test]
async fn indenting_a_list_item_lands_the_cursor_on_that_item() {
    use aether_protocol::input::{BlockDepthParams, InputBlockDepth};
    // A nested item's span starts at its marker, so the indent in front of it belongs to the
    // parent. Landing on the line start focused the parent and the next press acted on it.
    let (server, mut ws, buffer_id) = setup_with_buffer("- one\n- two\n- three\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(1, 2), p(1, 2), Granularity::Char).await;
    let deeper = |deeper: bool| BlockDepthParams { buffer_id, deeper };
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputBlockDepth>(&mut ws, &deeper(true)).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- one\n  - two\n- three\n");
    // Invoked from a bare reading position, so the landing stays a point — parked on the
    // indented item's own marker (col 2), not out in the indent that belongs to its parent.
    assert_eq!(r.cursor.position, p(1, 2));
    assert_eq!(r.cursor.anchor, r.cursor.position, "no selection conjured");
    // And the next press still acts on it: un-nesting puts it straight back.
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputBlockDepth>(&mut ws, &deeper(false)).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "- one\n- two\n- three\n",
        "Ctrl-l / Ctrl-h ping-pong"
    );
    drop(server);
}

#[tokio::test]
async fn toggle_task_flips_the_checkbox_under_the_cursor() {
    use aether_protocol::input::{InputToggleTask, ToggleTaskParams};
    let (server, mut ws, buffer_id) = setup_with_buffer("- [ ] open\n- [x] done\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    set_snapped(&mut ws, buffer_id, p(0, 6), p(0, 6), Granularity::Char).await;
    let toggle = |set| ToggleTaskParams { buffer_id, set };
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputToggleTask>(&mut ws, &toggle(None)).await;
    assert!(r.applied);
    assert_eq!(r.cursor.position, p(0, 6), "length unchanged, cursor stays");
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "- [x] open\n- [x] done\n");
    // `set` asks for a state rather than a flip — `Ctrl-a`/`Ctrl-Alt-a`. Asking for the state the
    // box is already in is a quiet no-op, so a held key settles the list instead of flapping it.
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputToggleTask>(&mut ws, &toggle(Some(true))).await;
    assert!(!r.applied, "already checked");
    assert!(r.reason.is_none(), "quietly, with no toast");
    let r: aether_protocol::input::BlockEditResult =
        send_request::<InputToggleTask>(&mut ws, &toggle(Some(false))).await;
    assert!(r.applied);
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(
        c.text, "- [ ] open\n- [x] done\n",
        "unchecked, neighbour untouched"
    );
    drop(server);
}

#[tokio::test]
async fn toggle_task_refuses_when_the_cursor_is_not_inside_a_task_item() {
    use aether_protocol::input::{InputToggleTask, ToggleTaskParams};
    // `Ctrl-a` sends unconditionally, so the resolver is the only gate: from a neighbouring
    // block it must refuse quietly, not reach into the list and toggle a box the cursor never
    // touched.
    let (server, mut ws, buffer_id) = setup_with_buffer("Intro.\n\n- [ ] open\n\nOutro.\n").await;
    let p = |line: u32, col: u32| LogicalPosition { line, col };
    let toggle = ToggleTaskParams {
        buffer_id,
        set: Some(true),
    };
    for (line, col, from) in [(0, 2, "Intro"), (4, 2, "Outro"), (3, 0, "the separator")] {
        set_snapped(
            &mut ws,
            buffer_id,
            p(line, col),
            p(line, col),
            Granularity::Char,
        )
        .await;
        let r: aether_protocol::input::BlockEditResult =
            send_request::<InputToggleTask>(&mut ws, &toggle).await;
        assert!(!r.applied, "no toggle from {from}");
        assert!(r.reason.is_none(), "and quietly, from {from}");
    }
    let c: BufferContentResult =
        send_request::<BufferContent>(&mut ws, &BufferContentParams { buffer_id }).await;
    assert_eq!(c.text, "Intro.\n\n- [ ] open\n\nOutro.\n", "box untouched");
    drop(server);
}

/// The status-bar breadcrumb (`lsp/symbol_path_changed`): the outline arrives a beat after the
/// buffer opens, so the *push* — not the subscribe snapshot — is what first fills the bar, and it
/// carries the enclosing chain outermost-first.
///
/// The dummy answers `documentSymbol` with a flat list whose ranges nest, which is the
/// `SymbolInformation` shape real servers without hierarchy support send; the server's
/// `assign_depth_by_containment` rebuilds the tree, so this also pins that the breadcrumb works for
/// flat servers and not just hierarchical ones.
#[tokio::test]
async fn symbol_path_pushes_the_enclosing_chain_when_the_outline_lands() {
    use aether_protocol::lsp::{LspSymbolPathChanged, LspSymbolPathChangedParams};
    use aether_server::{DummyDocSymbol, DummyLspConfig, DummyRange};
    use std::time::Duration;

    // impl Foo { fn bar { … } }, spanning lines 0..=4 with `fn bar` inside it at 1..=3.
    let content = "impl Foo {\n    fn bar() {\n        let x = 1;\n    }\n}\n";
    let dir = lay_out(&[("main.rs", content)]);
    let outer = DummyRange {
        line: 0,
        character: 0,
        end_line: 4,
        end_character: 1,
    };
    let inner = DummyRange {
        line: 1,
        character: 4,
        end_line: 3,
        end_character: 5,
    };
    let dummy = DummyLspConfig {
        document_symbols: vec![
            DummyDocSymbol {
                name: "impl Foo".into(),
                kind: 5, // Class
                range: outer,
                selection: DummyRange::on(0, 5, 8),
            },
            DummyDocSymbol {
                name: "fn bar".into(),
                kind: 6, // Method
                range: inner,
                selection: DummyRange::on(1, 7, 10),
            },
        ],
        ..Default::default()
    };
    let (server, mut ws) = open_and_subscribe_with_lsp(
        "crumbs",
        dir.path(),
        "main.rs",
        vec![("rust".into(), dummy)],
    )
    .await;
    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: Some(0),
            relative_path: Some("main.rs".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;

    // Cursor inside `fn bar`'s body. The outline may or may not have landed yet, so the assertion
    // is on the push, which fires either way (on arrival, or on this cursor move once it's cached).
    set_cursor(&mut ws, buffer_id, 2, 8).await;
    let deep: LspSymbolPathChangedParams =
        expect_notification_within::<LspSymbolPathChanged>(&mut ws, Duration::from_secs(10)).await;
    assert_eq!(deep.buffer_id, buffer_id);
    let names: Vec<&str> = deep.path.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(
        names,
        vec!["impl Foo", "fn bar"],
        "outermost first, innermost last"
    );

    // Out of `fn bar` but still inside the impl: the chain sheds its innermost crumb.
    set_cursor(&mut ws, buffer_id, 4, 0).await;
    let shallow: LspSymbolPathChangedParams =
        expect_notification_within::<LspSymbolPathChanged>(&mut ws, Duration::from_secs(10)).await;
    let names: Vec<&str> = shallow.path.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(names, vec!["impl Foo"]);

    drop(server);
}

/// Re-subscribing to a buffer whose outline was cached long ago answers with the breadcrumb in the
/// `viewport/subscribe` snapshot. Without this seed the bar would stay blank until the next symbol
/// boundary crossing — the push only fires on *change*, and switching buffers isn't one.
#[tokio::test]
async fn symbol_path_seeds_the_subscribe_snapshot() {
    use aether_protocol::lsp::{LspSymbolPathChanged, LspSymbolPathChangedParams};
    use aether_server::{DummyDocSymbol, DummyLspConfig, DummyRange};
    use std::time::Duration;

    let content = "fn solo() {\n    let x = 1;\n}\n";
    let dir = lay_out(&[("main.rs", content)]);
    let dummy = DummyLspConfig {
        document_symbols: vec![DummyDocSymbol {
            name: "fn solo".into(),
            kind: 12,
            range: DummyRange {
                line: 0,
                character: 0,
                end_line: 2,
                end_character: 1,
            },
            selection: DummyRange::on(0, 3, 7),
        }],
        ..Default::default()
    };
    let (server, mut ws) = open_and_subscribe_with_lsp(
        "crumb-seed",
        dir.path(),
        "main.rs",
        vec![("rust".into(), dummy)],
    )
    .await;
    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: Some(0),
            relative_path: Some("main.rs".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let buffer_id = open.buffer_id;
    set_cursor(&mut ws, buffer_id, 1, 4).await;
    // Wait for the outline to be cached (the push is the observable signal that it is).
    let _: LspSymbolPathChangedParams =
        expect_notification_within::<LspSymbolPathChanged>(&mut ws, Duration::from_secs(10)).await;

    // A fresh viewport on the same buffer — what a buffer switch back does.
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            buffer_id,
            cols: 100,
            rows: 40,
            overscan_rows: 0,
            scroll: ScrollPosition {
                logical_line: 0,
                sub_row: 0.0,
            },
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    let names: Vec<&str> = sub
        .buffer_status
        .symbol_path
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(names, vec!["fn solo"]);

    drop(server);
}
