// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.

mod common;

use common::*;

// ---- search/* -----------------------------------------------------------------------------------

#[tokio::test]
async fn search_set_returns_summary_and_jumps_to_first_match() {
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 3);
    assert!(!r.summary.truncated);
    assert_eq!(r.summary.current_index, 1);
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 2 });
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 0 });

    drop(server);
}

#[tokio::test]
async fn search_set_honours_match_options() {
    // Helper: set the search and return the total match count for the given options.
    async fn total(ws: &mut Ws, buffer_id: u64, q: &str, options: MatchOptions) -> u32 {
        let r: SearchSetResult = send_request::<SearchSet>(
            ws,
            &SearchSetParams {
                buffer_id,
                query: q.into(),
                anchor: None,
                extend: false,
                from_selection: false,
                options,
            },
        )
        .await;
        r.summary.total
    }

    // Case: smartcase (lowercase query) matches all three; forced-sensitive matches only the two
    // lowercase runs; forced-insensitive matches all three again.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo Foo foo\n").await;
    assert_eq!(
        total(&mut ws, buffer_id, "foo", MatchOptions::default()).await,
        3
    );
    let sensitive = MatchOptions {
        case: CaseMode::Sensitive,
        ..Default::default()
    };
    assert_eq!(total(&mut ws, buffer_id, "foo", sensitive).await, 2);
    let insensitive = MatchOptions {
        case: CaseMode::Insensitive,
        ..Default::default()
    };
    assert_eq!(total(&mut ws, buffer_id, "Foo", insensitive).await, 3);
    drop(server);

    // Whole-word: "foo" inside "foobar" is excluded once word boundaries are required.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo foobar foo\n").await;
    assert_eq!(
        total(&mut ws, buffer_id, "foo", MatchOptions::default()).await,
        3
    );
    let word = MatchOptions {
        whole_word: true,
        ..Default::default()
    };
    assert_eq!(total(&mut ws, buffer_id, "foo", word).await, 2);
    drop(server);

    // Regex opt-in: "a.c" matches literally by default (only "a.c"); with `regex` it matches
    // "abc"/"axc" too.
    let (server, mut ws, buffer_id) = setup_with_buffer("a.c abc axc\n").await;
    assert_eq!(
        total(&mut ws, buffer_id, "a.c", MatchOptions::default()).await,
        1,
        "literal is the default — a.c matches only a.c"
    );
    let regex = MatchOptions {
        regex: true,
        ..Default::default()
    };
    assert_eq!(total(&mut ws, buffer_id, "a.c", regex).await, 3);
    // Literal (default) + whole-word together don't double-escape: "a.c" still matches as a word.
    let literal_word = MatchOptions {
        whole_word: true,
        ..Default::default()
    };
    assert_eq!(total(&mut ws, buffer_id, "a.c", literal_word).await, 1);
    drop(server);
}

#[tokio::test]
async fn search_set_extend_grows_selection_from_anchor_through_match() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2). `?` from a caret at (0,4) selects
    // from there *through* the next match (0,8) — anchor stays at (0,4), head lands on the match's
    // last char (0,10). The counter tracks the head, so it reads "2".
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 4 }),
            extend: true,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 4 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 10 });
    assert_eq!(r.summary.current_index, 2);

    drop(server);
}

#[tokio::test]
async fn search_set_extend_resets_to_match_on_wrap() {
    // `?` from a caret past the last match (1,4) finds a match only by wrapping to the top. A wrap
    // resets to selecting just the match — anchor at its start (0,0), head at its last char (0,2) —
    // rather than ballooning the selection backward across the whole buffer.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 1, col: 4 }),
            extend: true,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 2 });
    assert_eq!(r.summary.current_index, 1);

    drop(server);
}

#[tokio::test]
async fn search_smartcase_lowercase_is_case_insensitive() {
    let (server, mut ws, buffer_id) = setup_with_buffer("Foo foo FOO\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 3); // matches all three regardless of case

    drop(server);
}

#[tokio::test]
async fn search_smartcase_uppercase_is_case_sensitive() {
    let (server, mut ws, buffer_id) = setup_with_buffer("Foo foo FOO\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "Foo".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 1);

    drop(server);
}

#[tokio::test]
async fn search_regex_metacharacters() {
    let (server, mut ws, buffer_id) = setup_with_buffer("abc 123 def 4567\n").await;
    // Regex is opt-in: `\d+` matches literally (nothing) by default, two runs with `regex` on.
    let lit: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: r"\d+".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(lit.summary.total, 0, "literal `\\d+` matches nothing");
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: r"\d+".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: MatchOptions {
                regex: true,
                ..Default::default()
            },
        },
    )
    .await;
    assert_eq!(r.summary.total, 2);

    drop(server);
}

#[tokio::test]
async fn search_no_matches_returns_zero_summary() {
    let (server, mut ws, buffer_id) = setup_with_buffer("alpha\nbeta\n").await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "zzz".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 0);
    assert_eq!(r.summary.current_index, 0);
    assert!(!r.summary.truncated);

    drop(server);
}

#[tokio::test]
async fn search_empty_query_clears_active_search() {
    let (server, mut ws, buffer_id) = setup_with_buffer("alpha\n").await;
    let _: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "alpha".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    let r: SearchSetResult = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: String::new(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 0);

    drop(server);
}

#[tokio::test]
async fn search_next_cycles_forward_and_wraps() {
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    let r1: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r1.summary.current_index, 2);
    assert_eq!(r1.cursor.anchor, LogicalPosition { line: 0, col: 8 });
    let r2: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r2.summary.current_index, 3);
    // Wrap.
    let r3: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r3.summary.current_index, 1);

    drop(server);
}

#[tokio::test]
async fn search_prev_cycles_backward_with_wrap() {
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // From the first match, prev wraps to the last.
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.current_index, 3);

    drop(server);
}

#[tokio::test]
async fn search_prev_orients_backward() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2).
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 8 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Backward (non-extend) re-selects the previous match oriented by travel direction: the head
    // leads on the start char (cursor before anchor), the anchor trails on the last char.
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.current_index, 1);
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 2 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 0 });

    drop(server);
}

#[tokio::test]
async fn search_next_wrap_stays_forward_oriented() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2).
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 1, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // From the last match, forward `next` wraps physically backward to the first match — but the
    // orientation follows logical travel (forward), so it stays forward-oriented: anchor on the
    // start, head on the last char. The wrap doesn't flip orientation.
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.current_index, 1);
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 2 });

    drop(server);
}

#[tokio::test]
async fn search_prev_wrap_stays_backward_oriented() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2).
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // From the first match, backward `prev` wraps physically forward to the last match — orientation
    // still follows logical travel (backward), so it stays backward-oriented: head on the start,
    // anchor on the last char.
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.current_index, 3);
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 1, col: 2 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 1, col: 0 });

    drop(server);
}

#[tokio::test]
async fn search_backward_oriented_then_extend_forward_grows_over_both() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2). Land on the second match, step
    // back (non-extend) to the first — leaving a backward-oriented selection — then extend forward.
    // The forward extend must reach back across the pivot and grow to cover both matches rather than
    // collapsing onto just the second.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 8 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Alt-n: backward-oriented selection of the first match — anchor (0,2), head (0,0).
    let back: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(back.cursor.anchor, LogicalPosition { line: 0, col: 2 });
    assert_eq!(back.cursor.position, LogicalPosition { line: 0, col: 0 });
    // Shift-n: extend forward to the second match. Crosses the pivot, re-anchors to the previous
    // head (0,0), so the selection grows to (0,0)..(0,10) — both matches covered, not just the second.
    let fwd: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(fwd.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(fwd.cursor.position, LogicalPosition { line: 0, col: 10 });

    drop(server);
}

#[tokio::test]
async fn search_extend_resets_to_single_match_on_wrap() {
    // Four matches of "foo". Extend forward across the first three, then one more extend past the end
    // wraps to the first match — and instead of ballooning the selection across the wrap boundary it
    // resets to just the first match (forward-oriented), letting the user start a fresh selection.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo foo bar foo baz foo\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 4 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Start on the second match (0,4). Extend forward twice: spans matches 2..4 (0,4)..(0,22).
    let _: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    let pre: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(pre.cursor.anchor, LogicalPosition { line: 0, col: 4 });
    assert_eq!(pre.cursor.position, LogicalPosition { line: 0, col: 22 });
    // One more extend wraps past the end. Rather than re-anchoring across the wrap (which would
    // engulf (0,0)..(0,22)), it resets to just the first match, forward-oriented.
    let wrap: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(wrap.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(wrap.cursor.position, LogicalPosition { line: 0, col: 2 });
    assert_eq!(wrap.summary.current_index, 1);

    drop(server);
}

#[tokio::test]
async fn search_reverse_off_a_match_steps_to_adjacent_not_current() {
    // Matches of "foo": (0,0)..(0,2), (0,8)..(0,10), (1,0)..(1,2). `next` to the second match leaves
    // a forward-oriented selection (head on the right). Immediately reversing with `prev` must step
    // to the *first* match, not re-select the second — i.e. one keypress moves you, not two.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // On the first match; `next` → second match (forward-oriented, head at (0,10)).
    let fwd: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(fwd.summary.current_index, 2);
    // Reverse: `prev` steps to the first match, not back onto the second.
    let back: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(back.summary.current_index, 1);

    drop(server);
}

#[tokio::test]
async fn search_plain_next_steps_off_multi_match_extend_selection() {
    // Four matches of "foo". Extend across the first two, then a plain (non-extend) `next` must step
    // off the *whole* selection to the third match — not land back inside it on the second.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo foo bar foo baz foo\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Extend forward: selection now spans the first two matches (anchor (0,0), head (0,6)).
    let _: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    // Plain next: steps off the whole selection to the third match at (0,12), not the second (0,4).
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.current_index, 3);
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 0, col: 12 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 14 });

    drop(server);
}

#[tokio::test]
async fn search_next_extend_keeps_anchor_and_grows_selection() {
    // Matches of "foo": (0,0), (0,8), (1,0).
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Cursor sits on the first match: anchor (0,0), head (0,2).
    // Extend-next pins the anchor and moves only the head onto the second match's end.
    let r1: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r1.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(r1.cursor.position, LogicalPosition { line: 0, col: 10 });
    // Selection spans two matches, but the counter tracks the match the *head* rests on — here the
    // second match, whose last char (0,10) the head sits on.
    assert_eq!(r1.summary.current_index, 2);
    // A second extend-next keeps the same anchor and steps the head to the third match — i.e. it
    // makes progress rather than re-finding the second match.
    let r2: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r2.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(r2.cursor.position, LogicalPosition { line: 1, col: 2 });

    drop(server);
}

#[tokio::test]
async fn search_prev_extend_keeps_anchor_and_grows_backward() {
    // Matches of "foo": (0,0), (0,8), (1,0).
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 1, col: 0 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // Cursor sits on the third match: anchor (1,0), head (1,2). Extend-prev moves the head back to
    // the second match's start. Because that crosses the pivot (the head jumps from the right of the
    // anchor to its left), the anchor re-pins to the previous cursor position (1,2) so the third
    // match stays fully covered — the selection becomes (0,8)..(1,2), not (0,8)..(1,0).
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.cursor.anchor, LogicalPosition { line: 1, col: 2 });
    assert_eq!(r.cursor.position, LogicalPosition { line: 0, col: 8 });

    drop(server);
}

#[tokio::test]
async fn search_extend_reversing_direction_grows_instead_of_shrinking() {
    // Matches of "foo": (0,0), (0,8), (1,0). Start on the middle match, extend backward, then
    // forward. Each reversal crosses the pivot, so the anchor re-pins to the previous cursor and the
    // selection keeps growing outward rather than collapsing back across the anchor.
    let (server, mut ws, buffer_id) = setup_with_buffer("foo bar foo baz\nfoo qux\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: Some(LogicalPosition { line: 0, col: 8 }),
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    // On the second match: anchor (0,8), head (0,10). Extend-prev to the first match crosses the
    // pivot → anchor re-pins to (0,10), selection (0,0)..(0,10) (both matches covered).
    let back: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Backward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(back.cursor.anchor, LogicalPosition { line: 0, col: 10 });
    assert_eq!(back.cursor.position, LogicalPosition { line: 0, col: 0 });
    // Now extend forward to the third match. This reverses again and crosses the pivot, so the
    // anchor re-pins to the previous cursor (0,0): the selection grows to (0,0)..(1,2), covering all
    // three matches, rather than shrinking back to just the third.
    let fwd: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: true,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(fwd.cursor.anchor, LogicalPosition { line: 0, col: 0 });
    assert_eq!(fwd.cursor.position, LogicalPosition { line: 1, col: 2 });

    drop(server);
}

#[tokio::test]
async fn search_clear_removes_active_search() {
    let (server, mut ws, buffer_id) = setup_with_buffer("foo\n").await;
    let _ = send_request::<SearchSet>(
        &mut ws,
        &SearchSetParams {
            buffer_id,
            query: "foo".into(),
            anchor: None,
            extend: false,
            from_selection: false,
            options: Default::default(),
        },
    )
    .await;
    let _: () = send_request::<SearchClear>(&mut ws, &SearchClearParams { buffer_id }).await;
    // After clear, n/prev should report no matches.
    let r: SearchNavResult = send_request::<SearchStep>(
        &mut ws,
        &SearchStepParams {
            direction: Direction::Forward,
            buffer_id,
            extend: false,
            count: 1,
            set_query: None,
            options: Default::default(),
        },
    )
    .await;
    assert_eq!(r.summary.total, 0);

    drop(server);
}

// -------- view/open jump_to --------------------------------------------------------------------

/// `view/open { jump_to }` lands the returned cursor at the requested position and persists it
/// so a follow-up open without `jump_to` resumes from the same spot.
#[tokio::test]
async fn buffer_open_jump_to_places_and_persists_cursor() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    std::fs::write(&path, "alpha\nbeta\ngamma\n").unwrap();
    let dir_path = dir.path().to_path_buf();
    let server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    let opened: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: Some(LogicalPosition { line: 1, col: 2 }),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(opened.cursor.position, LogicalPosition { line: 1, col: 2 });
    assert_eq!(opened.cursor.anchor, LogicalPosition { line: 1, col: 2 });

    // Reopen without jump_to — should resume the just-set position, not snap to origin.
    let reopen: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            view_id: Some(opened.view_id),
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen.cursor.position, LogicalPosition { line: 1, col: 2 });

    drop(server);
}

/// `view/open { jump_to }` clamps line past EOF and col past line end — used by the grep
/// picker when a persisted hit's coordinates have drifted out from under the file.
#[tokio::test]
async fn buffer_open_jump_to_clamps_out_of_range() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("a.txt");
    std::fs::write(&path, "ab\ncd\n").unwrap();
    let dir_path = dir.path().to_path_buf();
    let server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    // Line 99 doesn't exist; col 99 is past any line. Server should clamp to (last_line, line_end).
    let opened: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: Some(LogicalPosition { line: 99, col: 99 }),
            ..Default::default()
        },
    )
    .await;
    // The file has lines "ab\n", "cd\n", "". Last visible line is index 1 ("cd"), length 2 bytes.
    assert!(opened.cursor.position.line <= 2);
    assert!(opened.cursor.position.col <= 2);

    drop(server);
}

// -------- nav (back/forward history) --------------------------------------------------------------

/// Open + viewport-subscribe a file, returning (buffer_id, viewport_id). Mirrors a client switching
/// buffers: the client only ever has one viewport, since subscribing supersedes (and drops) the
/// previous one server-side, so there's no explicit unsubscribe. `record_from` is the origin
/// buffer for a qualifying jump — the open records it onto the nav back-stack (`record_nav_from`,
/// composite A); pass `None` when the open is just following a back/forward step (which must not
/// record).
///
/// Opened kept: these tests step back onto a file they left, and a preview would have closed
/// itself the moment the next file's subscribe hid it, coming back under a new buffer id.
async fn nav_open_file(ws: &mut Ws, file: &str, record_from: Option<u64>) -> (u64, u64) {
    let open: ViewOpenResult = send_request::<ViewOpen>(
        ws,
        &ViewOpenParams {
            transient: Some(false),
            path_index: Some(0),
            relative_path: Some(file.into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            record_nav_from: record_from,
            ..Default::default()
        },
    )
    .await;
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        ws,
        &ViewportSubscribeParams {
            view_id: open.view_id,
            cols: 80,
            rows: 10,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::Soft,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    (open.buffer_id, sub.viewport_id)
}

/// nav/back then nav/forward step across files, restoring the recorded cursor/selection.
#[tokio::test]
async fn nav_back_and_forward_across_files() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("a.txt"), "alpha\nsecond\n").unwrap();
    std::fs::write(dir.path().join("b.txt"), "bravo\n").unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    // In a.txt, make a selection on line 1 (anchor before cursor) so we can prove it's restored.
    let (buf_a, _vp_a) = nav_open_file(&mut ws, "a.txt", None).await;
    send_request::<CursorSet>(
        &mut ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id: buf_a,
            position: LogicalPosition { line: 1, col: 4 },
            anchor: LogicalPosition { line: 1, col: 1 },
        },
    )
    .await;

    // Jump to b.txt; the open records the origin (buf_a) onto the back-stack via `record_nav_from`.
    let (buf_b, _vp_b) = nav_open_file(&mut ws, "b.txt", Some(buf_a)).await;

    // Back (from b) → returns a.txt with the selection restored.
    let back: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: buf_b,
            direction: Direction::Backward,
        },
    )
    .await;
    let target = back.target.expect("back should move to a.txt");
    assert_eq!(target.buffer_id, buf_a);
    assert_eq!(target.cursor.position, LogicalPosition { line: 1, col: 4 });
    assert_eq!(target.cursor.anchor, LogicalPosition { line: 1, col: 1 });

    // Re-point the viewport to a (the client follows the target — a back step never records),
    // then forward (from a) → b.txt.
    let (_a_again, _vp_a2) = nav_open_file(&mut ws, "a.txt", None).await;
    let fwd: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: buf_a,
            direction: Direction::Forward,
        },
    )
    .await;
    assert_eq!(
        fwd.target.expect("forward should move to b.txt").buffer_id,
        buf_b
    );

    // Re-point to b, then back again (from b) lands on a once more (stack intact).
    let (_b_again, _vp_b2) = nav_open_file(&mut ws, "b.txt", None).await;
    let back2: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: buf_b,
            direction: Direction::Backward,
        },
    )
    .await;
    assert_eq!(back2.target.expect("back again to a.txt").buffer_id, buf_a);

    drop(server);
}

/// nav/back with nothing recorded is a no-op (`target: None`).
#[tokio::test]
async fn nav_back_empty_is_noop() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("a.txt"), "x\n").unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let (buf_a, _) = nav_open_file(&mut ws, "a.txt", None).await;

    let back: NavStepResult = send_request::<NavStep>(
        &mut ws,
        &NavStepParams {
            buffer_id: buf_a,
            direction: Direction::Backward,
        },
    )
    .await;
    assert!(back.target.is_none());
    drop(server);
}

/// nav/goto restores a closed file by path (its buffer_id is long gone) with the saved cursor,
/// without touching the back/forward stacks. Models the web client's `popstate` restore.
#[tokio::test]
async fn nav_goto_reopens_by_path() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("a.txt"), "one\ntwo\nthree\n").unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let (buf_a, _) = nav_open_file(&mut ws, "a.txt", None).await;
    // Close it so the stale buffer_id forces the path fallback.
    send_request::<ViewClose>(
        &mut ws,
        &ViewCloseParams {
            view_id: view_of(buf_a),
            open_next: false,
        },
    )
    .await;

    let res: NavStepResult = send_request::<NavGoto>(
        &mut ws,
        &NavGotoParams {
            virtual_key: None,
            read: None,
            view_id: Some(view_of(buf_a)), // stale on purpose
            path_index: Some(0),
            relative_path: Some("a.txt".into()),
            cursor: CursorState {
                position: LogicalPosition { line: 2, col: 1 },
                anchor: LogicalPosition { line: 2, col: 1 },
                match_bracket: None,
                jumplist_position: None,
            },
        },
    )
    .await;
    let target = res.target.expect("goto should open the file");
    assert_eq!(
        target.path.as_deref().map(|p| p.ends_with("a.txt")),
        Some(true)
    );
    assert_eq!(target.cursor.position, LogicalPosition { line: 2, col: 1 });
    drop(server);
}

// ---- nav history is per (context, client) --------------------------------------------------
//
// A nav entry names its file as `(path_index, relative_path)` *relative to the roots of the
// workspace that recorded it*, so a trail shared across workspaces resolves its entries against
// the wrong roots. These pin the ownership that fixes it: one trail per (context, client), plus
// the copy a context keeps of the last trail to leave it.

/// Two workspaces on one server, each rooted at a directory of its own — `proj-a` holding
/// `a1..a3.txt`, `proj-b` holding `b1..b2.txt`. Both roots are `path_index: 0` of their own
/// workspace, which is exactly the collision a cross-workspace trail used to fall into.
async fn two_workspaces() -> aether_server::ServerHandle {
    let dir_a = tempfile::tempdir().unwrap();
    for (name, content) in [
        ("a1.txt", "alpha\nsecond\n"),
        ("a2.txt", "another\n"),
        ("a3.txt", "again\n"),
    ] {
        std::fs::write(dir_a.path().join(name), content).unwrap();
    }
    let dir_b = tempfile::tempdir().unwrap();
    for (name, content) in [("b1.txt", "bravo\n"), ("b2.txt", "beta\n")] {
        std::fs::write(dir_b.path().join(name), content).unwrap();
    }
    let mut server = spawn_for_test_multi(vec![
        ("proj-a".to_string(), vec![dir_a.path().to_path_buf()]),
        ("proj-b".to_string(), vec![dir_b.path().to_path_buf()]),
    ])
    .await
    .unwrap();
    server.keep_alive(dir_a);
    server.keep_alive(dir_b);
    server
}

async fn activate(ws: &mut Ws, name: &str) {
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: name.into(),
            open_last: false,
        },
    )
    .await;
}

/// A client standing in `workspace`.
async fn join_at(server: &aether_server::ServerHandle, workspace: &str) -> Ws {
    let mut ws = Ws::connect(server).await;
    activate(&mut ws, workspace).await;
    ws
}

async fn nav_step_from(
    ws: &mut Ws,
    buffer_id: u64,
    direction: Direction,
) -> Option<ViewOpenResult> {
    let result: NavStepResult = send_request::<NavStep>(
        ws,
        &NavStepParams {
            buffer_id,
            direction,
        },
    )
    .await;
    result.target
}

/// Wait for the server to finish tearing a disconnected client down — the socket closing and the
/// teardown running are two different moments, and the hand-over happens in the second.
async fn await_no_clients(server: &aether_server::ServerHandle) {
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
    loop {
        if server.state.lock().await.clients.is_empty() {
            return;
        }
        assert!(
            std::time::Instant::now() < deadline,
            "the disconnecting client was never torn down"
        );
        tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    }
}

/// An entry recorded in one workspace is not steppable from another: A's trail is non-empty, and a
/// back step taken in B answers "no earlier location" rather than reaching across. B's own trail
/// works independently.
#[tokio::test]
async fn nav_history_does_not_cross_workspaces() {
    let server = two_workspaces().await;
    let mut ws = join_at(&server, "proj-a").await;
    let (a1, _) = nav_open_file(&mut ws, "a1.txt", None).await;
    let (_a2, _) = nav_open_file(&mut ws, "a2.txt", Some(a1)).await;

    activate(&mut ws, "proj-b").await;
    let (b1, _) = nav_open_file(&mut ws, "b1.txt", None).await;
    assert!(
        nav_step_from(&mut ws, b1, Direction::Backward)
            .await
            .is_none(),
        "A's trail is not B's — there is no earlier location here"
    );

    // B's own trail is a trail like any other.
    let (b2, _) = nav_open_file(&mut ws, "b2.txt", Some(b1)).await;
    assert_eq!(
        nav_step_from(&mut ws, b2, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(b1),
        "B steps its own"
    );
    drop(server);
}

/// A → B → A leaves A's trail exactly as it was, in both directions: the switch neither clears it
/// nor carries it across.
#[tokio::test]
async fn nav_history_survives_a_workspace_round_trip() {
    let server = two_workspaces().await;
    let mut ws = join_at(&server, "proj-a").await;
    let (a1, _) = nav_open_file(&mut ws, "a1.txt", None).await;
    let (a2, _) = nav_open_file(&mut ws, "a2.txt", Some(a1)).await;
    let (a3, _) = nav_open_file(&mut ws, "a3.txt", Some(a2)).await;
    // Back: [a1, a2], forward: [a3] — both stacks carry something to lose.
    assert_eq!(
        nav_step_from(&mut ws, a3, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(a2)
    );

    activate(&mut ws, "proj-b").await;
    let (b1, _) = nav_open_file(&mut ws, "b1.txt", None).await;
    assert!(nav_step_from(&mut ws, b1, Direction::Backward)
        .await
        .is_none());
    activate(&mut ws, "proj-a").await;
    let (a2_again, _) = nav_open_file(&mut ws, "a2.txt", None).await;
    assert_eq!(a2_again, a2, "the kept buffer survived the switch");

    // The back stack is where it was...
    assert_eq!(
        nav_step_from(&mut ws, a2, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(a1),
        "A's back stack came back intact"
    );
    // ...and so is the forward stack, both the entry that step just pushed and the one recorded
    // before the round trip.
    assert_eq!(
        nav_step_from(&mut ws, a1, Direction::Forward)
            .await
            .map(|t| t.buffer_id),
        Some(a2)
    );
    assert_eq!(
        nav_step_from(&mut ws, a2, Direction::Forward)
            .await
            .map(|t| t.buffer_id),
        Some(a3),
        "A's forward stack came back intact"
    );
    drop(server);
}

/// A context keeps the trail of the last client to leave it: a fresh client activating A steps
/// back along the trail the disconnected one left behind.
#[tokio::test]
async fn a_fresh_client_inherits_the_trail_of_the_last_to_leave() {
    let server = two_workspaces().await;
    let mut ws1 = join_at(&server, "proj-a").await;
    let (a1, _) = nav_open_file(&mut ws1, "a1.txt", None).await;
    let (_a2, _) = nav_open_file(&mut ws1, "a2.txt", Some(a1)).await;
    drop(ws1);
    await_no_clients(&server).await;

    let mut ws2 = join_at(&server, "proj-a").await;
    let (a2_again, _) = nav_open_file(&mut ws2, "a2.txt", None).await;
    assert_eq!(
        nav_step_from(&mut ws2, a2_again, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(a1),
        "the new window steps the trail the old one left"
    );
    drop(server);
}

/// The hand-over is a **copy**: a second client that picks up a context's trail steps its own, and
/// the window that left it behind still finds its trail where it was.
#[tokio::test]
async fn the_handed_over_trail_is_a_copy() {
    let server = two_workspaces().await;
    let mut ws1 = join_at(&server, "proj-a").await;
    let (a1, _) = nav_open_file(&mut ws1, "a1.txt", None).await;
    let (_a2, _) = nav_open_file(&mut ws1, "a2.txt", Some(a1)).await;
    // Leaving by switching, not by disconnecting: ws1 is still connected and still owns its trail.
    activate(&mut ws1, "proj-b").await;

    let mut ws2 = join_at(&server, "proj-a").await;
    let (a2_for_ws2, _) = nav_open_file(&mut ws2, "a2.txt", None).await;
    assert_eq!(
        nav_step_from(&mut ws2, a2_for_ws2, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(a1),
        "the second window starts from the copy"
    );
    assert!(
        nav_step_from(&mut ws2, a1, Direction::Backward)
            .await
            .is_none(),
        "and it has spent that copy"
    );

    // ws1 comes back to a trail its neighbour's stepping never touched.
    activate(&mut ws1, "proj-a").await;
    let (a2_again, _) = nav_open_file(&mut ws1, "a2.txt", None).await;
    assert_eq!(
        nav_step_from(&mut ws1, a2_again, Direction::Backward)
            .await
            .map(|t| t.buffer_id),
        Some(a1),
        "stepping in one window did not move the other's trail"
    );
    drop(server);
}
