// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.

mod common;

use aether_protocol::coords::ViewLine;
use common::*;

// -------- workspace/activate + switching ---------------------------------------------------------

/// `workspace/activate` returns the workspace's name + paths and lets buffer ops work afterwards.
/// (Already covered indirectly by every other test, but pinned explicitly here.)
#[tokio::test]
async fn workspace_activate_returns_info_and_unlocks_buffer_ops() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;

    // Before activation, buffer/open should fail with NO_ACTIVE_WORKSPACE (-32002).
    let pre_err = send_request_expect_err::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert!(
        pre_err.contains("no active workspace"),
        "expected NO_ACTIVE_WORKSPACE before activate, got: {pre_err}"
    );

    let activated: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(activated.workspace.name, "test-proj");
    assert_eq!(activated.workspace.paths.len(), 1);

    // Scratch buffer now works.
    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: None,
            relative_path: None,
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert!(open.buffer_id > 0);

    drop(server);
}

/// Activating an unknown workspace name returns UNKNOWN_WORKSPACE (-32003).
#[tokio::test]
async fn workspace_activate_rejects_unknown_name() {
    let dir = tempfile::tempdir().unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let msg = send_request_expect_err::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "no-such-workspace-12345".into(),
            open_last: false,
        },
    )
    .await;
    assert!(
        msg.contains("no configured workspace"),
        "expected UNKNOWN_WORKSPACE, got: {msg}"
    );
    drop(server);
}

/// Re-activating the *same* workspace is idempotent — no error, returns the same paths, and the
/// client's per-buffer state survives (no teardown when the name doesn't change).
#[tokio::test]
async fn workspace_activate_same_workspace_is_idempotent() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("buf.txt");
    std::fs::write(&path, "hello\n").unwrap();
    let server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: Some(0),
            relative_path: Some("buf.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;

    // Activate the same workspace again — should succeed and not destroy the buffer state.
    let again: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(again.workspace.name, "test-proj");

    // Re-opening the same path returns the same buffer (state preserved).
    let reopen: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            transient: None,
            buffer_id: None,
            path_index: Some(0),
            relative_path: Some("buf.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(reopen.buffer_id, open.buffer_id);

    drop(server);
}

// -------- git/worktree_add + git/worktree_remove --------------------------------------------------

/// A repo with `a.rs` committed on `main`, isolated config, and the workspace active. Leaks the
/// tempdir deliberately (like the checkout fixture) so the tree outlives the test body.
async fn setup_worktree_workspace() -> (
    aether_server::ServerHandle,
    Ws,
    git2::Repository,
    std::path::PathBuf,
    tempfile::TempDir,
) {
    // The `TempDir` is handed back rather than forgotten: `/tmp` here is a tmpfs, so a leaked
    // fixture survives until reboot, and a suite that leaks one per test exhausts the *inode*
    // table long before it runs out of bytes.
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().canonicalize().unwrap();
    let repo = init_repo_at(&root);
    isolate_repo_config(&repo, &root.join(".git/test-hooks"));
    commit_file(&repo, "a.rs", "one\n");
    let (server, ws) = setup_repos_workspace(vec![root.clone()]).await;
    (server, ws, repo, root, dir)
}

async fn worktree_add(
    ws: &mut Ws,
    root: &std::path::Path,
    branch: &str,
    create_branch: bool,
) -> GitWorktreeAddResult {
    send_request::<GitWorktreeAdd>(
        ws,
        &GitWorktreeAddParams {
            repo_id: Some(root.to_string_lossy().into()),
            branch: branch.into(),
            create_branch,
            ..Default::default()
        },
    )
    .await
}

#[tokio::test]
async fn worktree_add_creates_a_tree_in_the_store_off_the_workspace() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;

    let res = worktree_add(&mut ws, &root, "feature", true).await;
    assert_eq!(res.status, GitWorktreeAddStatus::Created);
    let wt = res.worktree.expect("a created worktree is reported");
    let path = std::path::PathBuf::from(&wt.path);

    // A real checkout, on the requested branch.
    assert!(path.join("a.rs").is_file(), "tracked files are checked out");
    let opened = git2::Repository::open(&path).unwrap();
    assert_eq!(opened.head().unwrap().shorthand().unwrap(), "feature");

    // The whole point of the centralised store: it is nowhere near the workspace root, so nothing
    // in the current workspace can see it until it is opened deliberately.
    assert!(
        !path.starts_with(&root),
        "{} must not live under the repo",
        path.display()
    );
    // Namespaced per repo family, so two repos wanting `feature` can't collide.
    let bucket = path
        .parent()
        .unwrap()
        .file_name()
        .unwrap()
        .to_string_lossy();
    assert!(bucket.contains('-'), "store bucket should be <name>-<hash>");

    drop(server);
}

#[tokio::test]
async fn worktree_add_derives_the_directory_and_leaves_the_branch_alone() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;

    // The Zed #47208 / orca #13011 pair: a slash must flatten into the directory name and must not
    // nest, while the *branch* keeps every character the user typed.
    let res = worktree_add(&mut ws, &root, "feature/auth", true).await;
    assert_eq!(res.status, GitWorktreeAddStatus::Created);
    let wt = res.worktree.unwrap();
    let path = std::path::PathBuf::from(&wt.path);

    assert_eq!(path.file_name().unwrap(), "feature-auth");
    assert_eq!(wt.name, "feature-auth");
    let opened = git2::Repository::open(&path).unwrap();
    assert_eq!(
        opened.head().unwrap().shorthand().unwrap(),
        "feature/auth",
        "the branch name must survive the directory derivation untouched"
    );

    drop(server);
}

#[tokio::test]
async fn worktree_add_uniquifies_a_second_tree_for_a_similar_branch() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;

    let first = worktree_add(&mut ws, &root, "feature/auth", true).await;
    assert_eq!(first.status, GitWorktreeAddStatus::Created);
    // `feature-auth` and `feature/auth` sanitise to the same directory name; the second must get
    // git's numeric suffix rather than colliding.
    let second = worktree_add(&mut ws, &root, "feature-auth", true).await;
    assert_eq!(second.status, GitWorktreeAddStatus::Created);

    let a = first.worktree.unwrap();
    let b = second.worktree.unwrap();
    assert_eq!(a.name, "feature-auth");
    assert_eq!(b.name, "feature-auth1");
    assert_ne!(a.path, b.path);

    drop(server);
}

#[tokio::test]
async fn worktree_add_refuses_a_branch_checked_out_elsewhere_and_says_where() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;

    let first = worktree_add(&mut ws, &root, "feature", true).await;
    assert_eq!(first.status, GitWorktreeAddStatus::Created);
    let existing = first.worktree.unwrap().path;

    // Git allows one checkout of a branch per family. The answer that matters is *where* it is, so
    // the client can offer to go there instead of reporting a failure.
    let again = worktree_add(&mut ws, &root, "feature", false).await;
    assert_eq!(again.status, GitWorktreeAddStatus::AlreadyCheckedOut);
    assert_eq!(again.checked_out_in.as_deref(), Some(existing.as_str()));

    drop(server);
}

#[tokio::test]
async fn worktree_add_classifies_a_missing_branch_before_spawning_git() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;
    let res = worktree_add(&mut ws, &root, "nope", false).await;
    assert_eq!(res.status, GitWorktreeAddStatus::NoSuchBranch);
    assert!(res.worktree.is_none());
    drop(server);
}

#[tokio::test]
async fn worktree_add_seeds_gitignored_files_named_by_worktreeinclude() {
    let (server, mut ws, repo, root, _dir) = setup_worktree_workspace().await;

    // `.env` is gitignored *and* named by `.worktreeinclude` → copied. `secret.key` is gitignored
    // but unnamed → not copied. `tracked.rs` is named but tracked → never duplicated, which is the
    // rule that keeps seeding from shadowing a checkout.
    std::fs::write(root.join(".gitignore"), ".env\nsecret.key\n").unwrap();
    std::fs::write(root.join(".worktreeinclude"), ".env\ntracked.rs\n").unwrap();
    std::fs::write(root.join("tracked.rs"), "fn main() {}\n").unwrap();
    commit_file(&repo, ".gitignore", ".env\nsecret.key\n");
    commit_file(&repo, "tracked.rs", "fn main() {}\n");
    std::fs::write(root.join(".env"), "TOKEN=abc\n").unwrap();
    std::fs::write(root.join("secret.key"), "shh\n").unwrap();

    let res = worktree_add(&mut ws, &root, "feature", true).await;
    assert_eq!(res.status, GitWorktreeAddStatus::Created);
    assert_eq!(res.seeded_files, 1, "only .env matches AND is ignored");
    let path = std::path::PathBuf::from(&res.worktree.unwrap().path);
    assert_eq!(
        std::fs::read_to_string(path.join(".env")).unwrap(),
        "TOKEN=abc\n"
    );
    assert!(!path.join("secret.key").exists(), "unnamed ignored file");
    assert!(path.join("tracked.rs").is_file(), "checked out, not copied");

    drop(server);
}

#[tokio::test]
async fn worktree_remove_takes_a_clean_tree_and_refuses_a_dirty_one() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;
    let created = worktree_add(&mut ws, &root, "feature", true).await;
    let wt = created.worktree.unwrap();
    let path = std::path::PathBuf::from(&wt.path);

    // Dirty first: an uncommitted change is the entire risk surface, so it must refuse and say
    // what would be lost rather than ask "are you sure?".
    std::fs::write(path.join("a.rs"), "changed\n").unwrap();
    std::fs::write(path.join("new.txt"), "untracked\n").unwrap();
    let refused: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(root.to_string_lossy().into()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(refused.status, GitWorktreeRemoveStatus::Dirty);
    let at_risk = refused.at_risk.expect("a dirty refusal itemises the risk");
    assert_eq!(at_risk.modified, 1);
    assert_eq!(at_risk.untracked, 1);
    assert!(path.exists(), "a refused removal changes nothing");

    // Clean it, and the same request succeeds.
    std::fs::write(path.join("a.rs"), "one\n").unwrap();
    std::fs::remove_file(path.join("new.txt")).unwrap();
    let removed: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(root.to_string_lossy().into()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(removed.status, GitWorktreeRemoveStatus::Removed);
    assert!(!path.exists(), "the directory is gone");
    // The branch survives — removing a worktree never discards committed work.
    let repo = git2::Repository::open(&root).unwrap();
    assert!(repo.find_branch("feature", git2::BranchType::Local).is_ok());

    drop(server);
}

#[tokio::test]
async fn worktree_remove_force_discards_and_refuses_the_main_worktree() {
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;
    let created = worktree_add(&mut ws, &root, "feature", true).await;
    let wt = created.worktree.unwrap();
    let path = std::path::PathBuf::from(&wt.path);
    std::fs::write(path.join("a.rs"), "changed\n").unwrap();

    let forced: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(root.to_string_lossy().into()),
            name: wt.name.clone(),
            force: true,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(forced.status, GitWorktreeRemoveStatus::Removed);
    assert!(!path.exists());

    // The main worktree has no admin name, and "you can't remove the repository" is the useful
    // answer rather than git's phrasing.
    let main: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(root.to_string_lossy().into()),
            name: String::new(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(main.status, GitWorktreeRemoveStatus::IsMain);
    assert!(root.join("a.rs").is_file());

    drop(server);
}

/// The merged branch picker's rows as `(name, admin name of the tree holding it)`, in window order.
/// `None` means no tree has that branch; `Some("")` is the main checkout, which has no admin name.
fn merged_rows(items: &[PickerItem]) -> Vec<(String, Option<String>)> {
    items
        .iter()
        .filter_map(|i| match i {
            PickerItem::GitBranch { name, checkout, .. } => {
                Some((name.clone(), checkout.as_ref().map(|k| k.worktree.clone())))
            }
            _ => None,
        })
        .collect()
}

#[tokio::test]
async fn the_branch_picker_lists_worktrees_and_branches_as_one_list() {
    // The merge: one branch-keyed list where a checked-out branch is a branch row carrying a
    // `checkout`, not a row in a second picker. `feature` appears exactly once — as itself, with
    // its tree named — which is how the one-checkout-per-family rule stops being a refusal and
    // becomes a destination.
    let (server, mut ws, repo, root, _dir) = setup_worktree_workspace().await;
    repo.branch(
        "spare",
        &repo.head().unwrap().peel_to_commit().unwrap(),
        false,
    )
    .unwrap();
    let created = worktree_add(&mut ws, &root, "feature", true).await;
    assert_eq!(created.status, GitWorktreeAddStatus::Created);

    // The picker takes its repo from the buffer it was opened over.
    let buffer = open_test_buffer(&mut ws, "a.rs").await;
    let view =
        send_request::<PickerView>(&mut ws, &view_params_on(PickerKind::GitBranches, buffer)).await;
    let update = view.update.expect("the view carries its initial window");
    let rows = merged_rows(update.items());

    // Checked-out branches pinned above the rest: where you are, then the family's other trees,
    // then branches no tree holds. Pinning rather than sectioning — two sections scattered the
    // branches you were looking for across two places.
    assert_eq!(
        rows[0],
        ("main".to_string(), Some(String::new())),
        "the main checkout is where we are standing, and has no admin name"
    );
    assert_eq!(
        rows[1],
        ("feature".to_string(), Some("feature".to_string())),
        "the branch row names the tree holding it"
    );
    assert_eq!(
        rows.iter().filter(|(n, _)| n == "feature").count(),
        1,
        "exactly one row per branch — it is not both a branch row and a worktree row"
    );
    assert_eq!(
        rows.iter().find(|(n, _)| n == "spare"),
        Some(&("spare".to_string(), None)),
        "a branch with no tree is an ordinary row, and Enter checks it out"
    );

    drop(server);
}

// -------- workspace variants (worktree bindings) --------------------------------------------------

/// A workspace with two roots — a repo and a plain notes directory — plus a worktree of the repo
/// already created. Sessions are on, because a variant's bindings live in that file.
async fn setup_variant_workspace() -> (
    aether_server::ServerHandle,
    Ws,
    std::path::PathBuf,
    std::path::PathBuf,
    tempfile::TempDir,
) {
    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().canonicalize().unwrap();
    let repo_root = base.join("repo");
    let notes = base.join("notes");
    std::fs::create_dir_all(&repo_root).unwrap();
    std::fs::create_dir_all(&notes).unwrap();
    std::fs::write(notes.join("todo.md"), "- one\n").unwrap();
    let repo = init_repo_at(&repo_root);
    isolate_repo_config(&repo, &repo_root.join(".git/test-hooks"));
    commit_file(&repo, "a.rs", "one\n");

    let sessions = base.join("sessions.json");
    // A second workspace so a test can switch away from `p` — `workspace/delete` refuses while
    // anyone is still in it.
    let server = aether_server::spawn_for_test_multi_with_sessions(
        vec![
            ("p".to_string(), vec![repo_root.clone(), notes.clone()]),
            ("q".to_string(), vec![notes.clone()]),
        ],
        Some(sessions),
    )
    .await
    .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws, repo_root, notes, dir)
}

async fn bind(ws: &mut Ws, repo_id: &std::path::Path, worktree: &str) -> WorkspaceActivateResult {
    send_request::<WorkspaceBindWorktree>(
        ws,
        &WorkspaceBindWorktreeParams {
            repo_id: Some(repo_id.to_string_lossy().into()),
            worktree: worktree.into(),
            // What the real client sends: land somewhere on arrival rather than leaving the window
            // showing a buffer from the context we just left.
            open_last: true,
            ..Default::default()
        },
    )
    .await
}

#[tokio::test]
async fn binding_remaps_the_repo_root_and_leaves_the_others_alone() {
    let (server, mut ws, repo_root, notes, _dir) = setup_variant_workspace().await;
    let created = worktree_add(&mut ws, &repo_root, "feature", true).await;
    let wt = created.worktree.unwrap();

    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    // Binding adjusts the workspace you are in. It does not rename it, and it does not create a
    // second one — which tree it is on is carried by `worktrees`, not by the id.
    assert_eq!(bound.workspace.name, "p");
    // Same shape: same root count, same order. That is what lets a project's positional
    // `root_index` survive a binding untouched.
    assert_eq!(bound.workspace.paths.len(), 2);
    assert_eq!(bound.workspace.paths[0], wt.path);
    assert_eq!(
        bound.workspace.paths[1],
        notes.to_string_lossy(),
        "a root outside every bound repo must not move"
    );

    drop(server);
}

#[tokio::test]
async fn a_second_repo_binds_alongside_the_first() {
    // Binding a repo that isn't bound yet adds to what this workspace holds. That is the
    // whole multi-repo story — run the command once per repo.
    let dir = tempfile::tempdir().unwrap();
    let base = dir.path().canonicalize().unwrap();
    let a = base.join("a");
    let b = base.join("b");
    for root in [&a, &b] {
        std::fs::create_dir_all(root).unwrap();
        let repo = init_repo_at(root);
        isolate_repo_config(&repo, &root.join(".git/test-hooks"));
        commit_file(&repo, "f.rs", "one\n");
    }
    let server = aether_server::spawn_for_test_multi_with_sessions(
        vec![("p".to_string(), vec![a.clone(), b.clone()])],
        Some(base.join("sessions.json")),
    )
    .await
    .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;

    let wt_a = worktree_add(&mut ws, &a, "oauth", true)
        .await
        .worktree
        .unwrap();
    let first = bind(&mut ws, &a, &wt_a.name).await;
    assert_eq!(first.workspace.name, "p");

    // The two worktrees need not share a name — the binding is per repo.
    let wt_b = worktree_add(&mut ws, &b, "auth-api", true)
        .await
        .worktree
        .unwrap();
    let second = bind(&mut ws, &b, &wt_b.name).await;
    assert_eq!(second.workspace.name, "p");
    assert_eq!(second.workspace.paths[0], wt_a.path);
    assert_eq!(second.workspace.paths[1], wt_b.path);
    assert_ne!(
        second.workspace.paths[0], second.workspace.paths[1],
        "two repos, two trees, one workspace"
    );

    drop(server);
}

#[tokio::test]
async fn rebinding_updates_in_place_and_keeps_the_other_bindings() {
    // Rebinding must not silently drop what else the workspace holds, and must not spawn a second
    // workspace — the reason the "first-bound repo is special" rule was deleted.
    //
    // The second bind here is issued with the *worktree's* path as the repo id, which is the state
    // you are actually in after the first one. Keyed by workdir that wrote a second binding for the
    // same repo and left the two to fight; keyed by common dir — which every worktree of a family
    // shares — there is one key by construction, which is what the count below pins.
    let (server, mut ws, repo_root, _notes, dir) = setup_variant_workspace().await;
    let oauth = worktree_add(&mut ws, &repo_root, "oauth", true)
        .await
        .worktree
        .unwrap();
    let hotfix = worktree_add(&mut ws, &repo_root, "hotfix", true)
        .await
        .worktree
        .unwrap();

    let first = bind(&mut ws, &repo_root, &oauth.name).await;
    assert_eq!(first.workspace.paths[0], oauth.path);

    let second = bind(&mut ws, std::path::Path::new(&oauth.path), &hotfix.name).await;
    assert_eq!(
        second.workspace.name, "p",
        "still the workspace you were standing in"
    );
    assert_eq!(second.workspace.paths[0], hotfix.path);
    // Both contexts survive, one per binding set — that is the model, not a leak. You can go back
    // to `oauth` and find the buffers you left there.
    let contexts = sessions_json(&dir)["workspaces"]["p"]["contexts"]
        .as_array()
        .expect("the workspace recorded its bound contexts")
        .clone();
    assert_eq!(
        contexts.len(),
        2,
        "one context per binding set, both remembered: {contexts:?}"
    );
    // What must *not* accumulate is keys within a context. The second bind was issued with the
    // worktree's own path as the repo id, which is the state you are actually in after the first;
    // keyed by workdir that wrote a second binding for the same repo and left the two to fight.
    for ctx in &contexts {
        let bindings = ctx["worktrees"]
            .as_object()
            .expect("a context records what it is bound to");
        assert_eq!(
            bindings.len(),
            1,
            "one key per repo family, however you reach it: {bindings:?}"
        );
        assert!(
            bindings.keys().all(|k| k.ends_with("/.git")),
            "keyed by common dir, not by any checkout's workdir: {bindings:?}"
        );
    }

    drop(server);
}

#[tokio::test]
async fn unbinding_the_last_repo_returns_to_the_configured_roots() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // An empty worktree name is "send this repo back to main". The configured roots are what it
    // returns to — this is why binding can never strand you, and why nothing has to be created or
    // destroyed to get back. The repo is named as the workspace *currently* sees it (the worktree),
    // which is what a picker row carries.
    let back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    assert_eq!(back.workspace.name, "p");
    assert_eq!(back.workspace.paths[0], repo_root.to_string_lossy());

    drop(server);
}

/// Editing the roots of a **bound** workspace edits its *configured* roots, not the materialised
/// ones it is currently standing on.
///
/// A bound workspace's `paths` point into the app-managed worktree store. Those are machine state:
/// `git worktree remove` can delete them, and they are not what the workspace *is*. Writing them
/// back as the workspace's own roots — which every `from_parts` call site did — replaced its
/// definition with a checkout, so unbinding had nothing to return to. The two lists also have to
/// stay positionally identical, or the added root falls off the next materialisation entirely.
#[tokio::test]
async fn adding_a_root_while_bound_edits_the_configured_roots_not_the_worktree_ones() {
    let (server, mut ws, repo_root, notes, dir) = setup_variant_workspace().await;
    let extra = dir.path().canonicalize().unwrap().join("extra");
    std::fs::create_dir_all(&extra).unwrap();

    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    let added: aether_protocol::workspace::WorkspaceInfo =
        send_request::<aether_protocol::workspace::WorkspaceAddRoot>(
            &mut ws,
            &aether_protocol::workspace::WorkspaceAddRootParams {
                workspace: "p".into(),
                path: extra.to_string_lossy().into(),
            },
        )
        .await;
    assert_eq!(added.paths.len(), 3);
    assert_eq!(
        added.paths[0], wt.path,
        "the bound root stays materialised — adding a root is not an unbind"
    );

    // The proof: unbinding returns to the configured roots, and the root added while bound is
    // among them. With the addition recorded only against the materialised list, the configured
    // list still held two entries and the third silently vanished on the next materialisation.
    let back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    assert_eq!(
        back.workspace.paths,
        vec![
            repo_root.to_string_lossy().into_owned(),
            notes.to_string_lossy().into_owned(),
            extra.to_string_lossy().into_owned(),
        ],
        "back on the main checkout, with the added root still there and in order"
    );

    drop(server);
}

/// The mirror of the above: removing a root while bound drops the same index from both halves.
///
/// The client sends back a path it was *shown*, which for a bound repo is the worktree path — so
/// the lookup has to find it in the materialised list and then remove the corresponding
/// **configured** root, not retain-by-value on one list and leave the other a slot longer.
#[tokio::test]
async fn removing_a_root_while_bound_drops_it_from_both_halves() {
    let (server, mut ws, repo_root, notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // Remove the bound repo's root, naming it the way the client sees it: the worktree path.
    let after: aether_protocol::workspace::WorkspaceRemoveRootResult =
        send_request::<aether_protocol::workspace::WorkspaceRemoveRoot>(
            &mut ws,
            &aether_protocol::workspace::WorkspaceRemoveRootParams {
                workspace: "p".into(),
                path: wt.path.clone(),
            },
        )
        .await;
    assert_eq!(
        after.workspace.paths,
        vec![notes.to_string_lossy().into_owned()],
        "the worktree root is gone and the untouched one stays"
    );

    // And the configured half went with it. Re-activating re-materialises from the configured
    // roots, so a stale entry there resurrects the root we just removed.
    let again: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(
        again.workspace.paths,
        vec![notes.to_string_lossy().into_owned()],
        "the removed root must not come back on the next activation"
    );

    drop(server);
}

#[tokio::test]
async fn open_buffers_follow_the_switch_and_unsaved_ones_stay_behind() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    // One clean buffer in the repo (should follow), one in the notes root (shouldn't move at all),
    // and one dirty buffer in the repo (should stay behind).
    let clean: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;
    let _note: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(1),
            relative_path: Some("todo.md".into()),
            ..Default::default()
        },
    )
    .await;
    std::fs::write(repo_root.join("b.rs"), "two\n").unwrap();
    let dirty: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("b.rs".into()),
            ..Default::default()
        },
    )
    .await;
    let _typed: aether_protocol::input::EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id: dirty.buffer_id,
            text: "x".into(),
            select_pasted: false,
            replace_selection: false,
            at: None,
        },
    )
    .await;

    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);
    assert_ne!(bound.workspace.paths[0], repo_root.to_string_lossy());

    // A rebind destroys nothing, so the unsaved buffer isn't refused — it simply doesn't follow to
    // the other tree, and is still open (and still dirty) at its own path when you unbind.
    let back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    assert_eq!(back.workspace.name, "p");
    let view = send_request::<PickerView>(&mut ws, &view_params(PickerKind::Buffers)).await;
    let update = view.update.expect("the view carries its initial window");
    assert!(
        update.items().iter().any(|i| matches!(
            i,
            PickerItem::Buffer { buffer_id, status, .. }
                if *buffer_id == dirty.buffer_id && *status == BufferDirtyState::Unsaved
        )),
        "the unsaved buffer is still open in the context it stayed in, still unsaved"
    );
    let _ = clean;

    drop(server);
}

/// Which checkout a file lives in is a fact about *its repo*, so it rides `GitBufferStatus` beside
/// the branch — not the workspace label, which would have to aggregate across every bound repo and
/// then couldn't say which root each name belonged to.
///
/// The branch alone cannot carry it: git allows one checkout per branch per family, so a worktree
/// on `feature` and a main checkout on `feature` produce the same string. That is why the status
/// bar marks the branch (`⧉` in the warning colour) rather than repeating it.
#[tokio::test]
async fn a_buffer_in_a_bound_repo_reports_its_checkout_as_a_worktree() {
    let (server, mut ws, repo_root, notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    async fn status_of(
        ws: &mut Ws,
        path_index: u32,
        rel: &str,
    ) -> Option<aether_protocol::git::GitBufferStatus> {
        let open: BufferOpenResult = send_request::<BufferOpen>(
            ws,
            &BufferOpenParams {
                path_index: Some(path_index),
                relative_path: Some(rel.into()),
                ..Default::default()
            },
        )
        .await;
        let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
            ws,
            &ViewportSubscribeParams {
                buffer_id: aether_protocol::ViewId(open.buffer_id),
                cols: 80,
                rows: 24,
                overscan_rows: 0,
                scroll: ScrollPosition {
                    logical_line: ViewLine(0),
                    sub_row: 0.0,
                },
                wrap: WrapMode::None,
                continuation_marker_width: 0,
                tab_width: 4,
                diff_view: false,
            },
        )
        .await;
        sub.window.git_status
    }

    // Unbound: the file is in the main checkout.
    let before = status_of(&mut ws, 0, "a.rs")
        .await
        .expect("tracked file carries git status");
    assert!(!before.worktree, "the main checkout is not a worktree");

    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // Bound: the same relative path now resolves into the worktree, and says so.
    let after = status_of(&mut ws, 0, "a.rs")
        .await
        .expect("tracked file carries git status");
    assert!(after.worktree, "a file under a bound root is in a worktree");
    assert_eq!(after.branch.as_deref(), Some("feature"));
    // Note what this *can't* be tested against: git forbids one branch in two checkouts, so there
    // is no fixture where the same branch name appears in both a main tree and a worktree. That is
    // exactly why the branch string can't carry the fact — `feature` tells you nothing about which
    // checkout holds it, and the answer isn't derivable from the name at all.

    // A file under the unbound notes root is untouched by the binding — per-repo, not per-workspace.
    let _ = notes;
    let note = status_of(&mut ws, 1, "todo.md").await;
    assert!(
        note.is_none_or(|g| !g.worktree),
        "a root outside every bound repo is not in a worktree"
    );

    drop(server);
}

#[tokio::test]
async fn a_workspace_whose_worktree_vanished_degrades_to_its_configured_roots() {
    // A `git worktree remove` in a terminal invalidates a binding at any moment. Refusing to
    // open would leave no way back in, so the root falls back to the configured path instead. This
    // is the property that makes bindings safe to keep in machine state.
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // Unbind first, so the repo is reachable under its configured root again, and remove the tree.
    // Our own removal drops the binding (`forget_worktree_bindings`), so it is planted back
    // afterwards — what is under test is the activation path a *terminal* removal leaves behind.
    let _ = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    let removed: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(repo_root.to_string_lossy().into()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(removed.status, GitWorktreeRemoveStatus::Removed);

    let sessions_path = _dir.path().canonicalize().unwrap().join("sessions.json");
    let mut sessions: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&sessions_path).unwrap()).unwrap();
    sessions["workspaces"]["p"]["worktrees"] =
        serde_json::json!({ repo_root.to_string_lossy(): wt.name });
    std::fs::write(&sessions_path, serde_json::to_string(&sessions).unwrap()).unwrap();

    // A fresh client, so the workspace is loaded cold from disk with the dangling binding.
    let mut ws2 = Ws::connect(&server).await;
    let reopened: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(
        reopened.workspace.paths[0],
        repo_root.to_string_lossy(),
        "an unresolvable binding degrades that root to the configured path rather than failing"
    );

    drop(server);
}

#[tokio::test]
async fn the_tree_you_are_in_is_the_pickers_opening_selection() {
    // The picker opens *on* where you are, like the buffer picker opens on the current buffer.
    // Since the merge that row is a branch row carrying a current checkout — and the ordering pins
    // it to index 0, which is the default highlight, so Enter-on-open is a no-op with no extra
    // mechanism. In the base the main checkout is already current, so the case worth testing is
    // standing in a worktree.
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // The picker takes its repo from the buffer it was opened over.
    let buffer = open_test_buffer(&mut ws, "a.rs").await;
    let view =
        send_request::<PickerView>(&mut ws, &view_params_on(PickerKind::GitBranches, buffer)).await;
    let centred = view
        .effective_center_on
        .expect("a fresh open centres on where you are");
    assert!(
        matches!(&centred, PickerItem::GitBranch { checkout: Some(k), .. }
            if k.worktree == wt.name && k.is_current),
        "centred on the tree we're standing in: {centred:?}"
    );

    let update = view.update.expect("the view carries its initial window");
    let rows = merged_rows(update.items());
    assert_eq!(
        rows[0].1.as_deref(),
        Some(wt.name.as_str()),
        "and it leads the list: {rows:?}"
    );

    drop(server);
}

/// **Creating** refreshes the open picker too, which only became necessary when the verbs split.
///
/// `Ctrl-o` deliberately stays put — it is a lifecycle verb, not a navigation one — so the row
/// gaining its worktree marker *is* the feedback that it worked. Without this the list still says
/// the branch has no tree, and the next press tries to make a second one. Caught by driving the
/// real TUI, not by any unit test: the create path had never needed a refresh, because it used to
/// be followed by a bind that closed and reopened everything.
#[tokio::test]
async fn creating_a_worktree_refreshes_the_open_picker() {
    use aether_protocol::picker::PickerItem;
    let (server, mut ws, repo, root, _dir) = setup_worktree_workspace().await;
    repo.branch(
        "spare",
        &repo.head().unwrap().peel_to_commit().unwrap(),
        false,
    )
    .unwrap();

    // Open *and* subscribe — a refresh only reaches a picker with a window.
    // The picker takes its repo from the buffer it was opened over.
    let buffer = open_test_buffer(&mut ws, "a.rs").await;
    let view =
        send_request::<PickerView>(&mut ws, &view_params_on(PickerKind::GitBranches, buffer)).await;
    let holds_a_tree = |update: &PickerUpdateParams, branch: &str| {
        update.items().iter().any(|i| {
            matches!(i, PickerItem::GitBranch { name, checkout: Some(_), .. }
                if name.as_str() == branch)
        })
    };
    assert!(
        !holds_a_tree(&view.update.expect("initial window"), "spare"),
        "`spare` has no tree before we make one"
    );

    let (created, mut updates) = send_request_collecting_updates::<GitWorktreeAdd>(
        &mut ws,
        &GitWorktreeAddParams {
            repo_id: Some(root.to_string_lossy().into()),
            branch: "spare".into(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(created.status, GitWorktreeAddStatus::Created);

    // Which window arrives when is not fixed — the writer prefers replies to pushes, and the open's
    // own push may still be in flight. Read on until one reflects the create.
    let mut update = updates.pop();
    for _ in 0..4 {
        match &update {
            Some(u) if holds_a_tree(u, "spare") => break,
            _ => {
                update = Some(
                    expect_notification_within::<PickerUpdate>(
                        &mut ws,
                        std::time::Duration::from_secs(5),
                    )
                    .await,
                )
            }
        }
    }
    assert!(
        holds_a_tree(&update.expect("a window after the create"), "spare"),
        "the row must gain its worktree marker in place — that is the whole feedback"
    );

    drop(server);
}

#[tokio::test]
async fn removing_a_worktree_refreshes_the_open_picker() {
    // Removal leaves the picker *up* — it has no confirm dialog and no switch to follow. So the
    // list has to be corrected underneath the user, or the tree they just removed stays on screen
    // and the next press acts on a row that isn't there. `Ctrl-o` is the same in reverse: it stays
    // put deliberately, and the marker appearing on the row is the feedback that it worked.
    use aether_protocol::picker::PickerItem;
    let (server, mut ws, _repo, root, _dir) = setup_worktree_workspace().await;
    let wt = worktree_add(&mut ws, &root, "feature", true)
        .await
        .worktree
        .unwrap();

    // Open *and* subscribe — a refresh only reaches a picker with a window.
    // The picker takes its repo from the buffer it was opened over.
    let buffer = open_test_buffer(&mut ws, "a.rs").await;
    let view =
        send_request::<PickerView>(&mut ws, &view_params_on(PickerKind::GitBranches, buffer)).await;
    // Keyed on the row's *checkout*, not its name: since the merge the branch keeps its row after
    // the tree goes, so "is `feature` listed" stays true either way and would answer the wrong
    // question. What changes is that the row stops naming a tree.
    let lists_tree = |update: &PickerUpdateParams, want: &str| {
        update.items().iter().any(|i| {
            matches!(i, PickerItem::GitBranch { checkout: Some(k), .. }
                if k.worktree.as_str() == want)
        })
    };
    assert!(
        lists_tree(&view.update.expect("initial window"), &wt.name),
        "the tree is listed before it is removed"
    );

    let (removed, mut updates) = send_request_collecting_updates::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(root.to_string_lossy().into()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(removed.status, GitWorktreeRemoveStatus::Removed);
    // Which window arrives when is not fixed: the writer prefers replies to pushes, and the open's
    // own push may still be in flight. So read on until one reflects the removal.
    let mut update = updates.pop();
    for _ in 0..4 {
        match &update {
            Some(u) if !lists_tree(u, &wt.name) => break,
            _ => {
                update = Some(
                    expect_notification_within::<PickerUpdate>(
                        &mut ws,
                        std::time::Duration::from_secs(5),
                    )
                    .await,
                )
            }
        }
    }
    let update = update.expect("a window after the removal");

    assert!(
        !lists_tree(&update, &wt.name),
        "the removed tree must not still be listed: {:?}",
        update.items()
    );
    // And the branch survives, now holding no tree — the same rebuild the next fresh open would
    // do, rather than a row simply deleted from the window. This is `Ctrl-d`'s progression made
    // visible: the first press takes the tree off, and only then is there a branch to delete.
    assert!(
        update.items().iter().any(|i| matches!(
            i,
            PickerItem::GitBranch { name, checkout: None, .. } if name == "feature"
        )),
        "the branch survives the worktree: {:?}",
        update.items()
    );

    drop(server);
}

#[tokio::test]
async fn a_branch_row_carries_everything_its_actions_need() {
    // The merged picker is not a jump target: `picker/select` never fires for it, and the client
    // acts on the highlighted row directly — `workspace/bind_worktree` for a row with a tree,
    // `git/checkout` for one without, `git/worktree_add` on `Ctrl-o`, `git/worktree_remove` on
    // `Ctrl-d`. So every one of those has to be answerable from the row alone, without a second
    // round trip: the repo (resolution runs off the active buffer, which may have moved) and the
    // admin name (which drifts from the branch, so it can't be re-derived).
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    // The picker takes its repo from the buffer it was opened over.
    let buffer = open_test_buffer(&mut ws, "a.rs").await;
    let view =
        send_request::<PickerView>(&mut ws, &view_params_on(PickerKind::GitBranches, buffer)).await;
    let update = view.update.expect("the view carries its initial window");
    let row = update
        .items()
        .iter()
        .find(|i| matches!(i, PickerItem::GitBranch { checkout: Some(k), .. } if !k.is_main))
        .expect("the linked worktree's branch is listed")
        .clone();

    let PickerItem::GitBranch {
        repo_id, checkout, ..
    } = row
    else {
        unreachable!("filtered above")
    };
    let checkout = checkout.expect("filtered above");
    assert_eq!(checkout.worktree, wt.name, "the admin name to bind by");
    assert_eq!(checkout.path, wt.path);
    assert_eq!(
        repo_id,
        repo_root.to_string_lossy(),
        "the repo the row belongs to, echoed onto every action it triggers"
    );
    assert!(!checkout.is_current, "we are still in the main checkout");

    drop(server);
}

/// The session file as JSON, for asserting on what survived a delete or a rename.
fn sessions_json(dir: &tempfile::TempDir) -> serde_json::Value {
    let path = dir.path().canonicalize().unwrap().join("sessions.json");
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

#[tokio::test]
async fn deleting_a_bound_workspace_takes_its_bindings_and_leaves_the_worktree() {
    // A workspace's bound contexts are nested under its own session entry, so deleting it takes
    // them along with no cascade to forget — a context stranded in the file would resurrect against
    // an unrelated workspace that later took the same name. The worktree is not the workspace's to
    // delete.
    let (server, mut ws, repo_root, _notes, dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);
    assert!(
        sessions_json(&dir)["workspaces"]["p"]["contexts"]
            .as_array()
            .is_some_and(|c| !c.is_empty()),
        "the bound context is nested under the workspace's own entry"
    );

    // Switch away — deletion refuses on an active workspace.
    let _ephemeral: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    let _elsewhere: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "q".into(),
            open_last: false,
        },
    )
    .await;

    let _: () =
        send_request::<WorkspaceDelete>(&mut ws, &WorkspaceDeleteParams { name: "p".into() }).await;

    let sessions = sessions_json(&dir);
    assert!(
        sessions["workspaces"].get("p").is_none(),
        "the session goes, bindings and all: {sessions}"
    );
    // The worktree itself is untouched: it is a git object in a shared store, not the workspace's.
    assert!(std::path::Path::new(&wt.path).exists());

    drop(server);
}

#[tokio::test]
async fn removing_a_worktree_forgets_the_bindings_that_named_it() {
    // A binding left pointing at a tree we just deleted would open the workspace onto nothing. The
    // workspace itself survives — it simply goes back to its configured roots, which is the same
    // thing unbinding does.
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);

    // Unbind first: removing the tree you are standing in is a different problem.
    let _back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    let removed: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(repo_root.to_string_lossy().into()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(removed.status, GitWorktreeRemoveStatus::Removed);

    // Asserted against the session file because that *is* the registry for bindings — nothing else
    // holds them, so nothing else can disagree.
    let sessions: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(_dir.path().canonicalize().unwrap().join("sessions.json"))
            .unwrap(),
    )
    .unwrap();
    assert!(
        sessions["workspaces"]["p"]["worktrees"]
            .as_object()
            .is_none_or(|m| m.is_empty()),
        "no binding may outlive the tree it names: {sessions}"
    );
    assert!(
        sessions["workspaces"].get("p").is_some(),
        "but the workspace itself survives losing a binding: {sessions}"
    );

    drop(server);
}

/// Removing the tree the workspace is *standing in* must put it back on its configured roots first.
///
/// Before this, the removal succeeded and left the workspace pointing at a directory that no longer
/// existed — roots, index, watches and open buffers all aimed at deleted paths, recoverable only by
/// restarting the server, because nothing re-materialises a workspace whose bindings moved
/// underneath it.
/// The first promise: "the active buffer always follows" — *the* active buffer, not whichever
/// one the workspace's MRU happens to head.
///
/// `open_last` alone can't keep that promise: it lands on the MRU head, which is the same file only
/// by coincidence. With several buffers it is whichever the rebind listed first, and with none left
/// to list it is a fresh scratch. So the landing is chosen from the old-buffer → new-file mapping
/// the rebind builds, and `open_last` stays as the fallback.
#[tokio::test]
async fn the_rebinding_client_lands_on_the_file_it_was_viewing() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    // Committed *before* the worktree is created, so the branch it checks out has this file — an
    // uncommitted one has nothing to follow to (see the sibling test).
    let repo = git2::Repository::open(&repo_root).unwrap();
    commit_file(&repo, "b.rs", "two\n");
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    // Two buffers, both kept (not transient previews), ending *viewing* b.rs while a.rs is the one
    // that would otherwise be reached first.
    let mut viewing = 0;
    for (_, rel) in [(11u64, "a.rs"), (13, "b.rs")] {
        let open: BufferOpenResult = send_request::<BufferOpen>(
            &mut ws,
            &BufferOpenParams {
                path_index: Some(0),
                relative_path: Some(rel.into()),
                transient: Some(false),
                ..Default::default()
            },
        )
        .await;
        let _sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
            &mut ws,
            &ViewportSubscribeParams {
                buffer_id: aether_protocol::ViewId(open.buffer_id),
                cols: 80,
                rows: 24,
                overscan_rows: 0,
                scroll: ScrollPosition {
                    logical_line: ViewLine(0),
                    sub_row: 0.0,
                },
                wrap: WrapMode::None,
                continuation_marker_width: 0,
                tab_width: 4,
                diff_view: false,
            },
        )
        .await;
        viewing = open.buffer_id;
    }
    assert_ne!(viewing, 0);

    let bound: WorkspaceActivateResult = send_request::<WorkspaceBindWorktree>(
        &mut ws,
        &WorkspaceBindWorktreeParams {
            repo_id: Some(repo_root.to_string_lossy().into()),
            worktree: wt.name.clone(),
            open_last: true,
            // What the real client sends: the buffer it is looking at.
            buffer_id: Some(viewing),
            ..Default::default()
        },
    )
    .await;
    let path = bound
        .opened
        .expect("a bind with open_last lands somewhere")
        .path
        .expect("…on a file, not a scratch");
    assert!(
        path.starts_with(&wt.path) && path.ends_with("b.rs"),
        "landed on the file it was viewing, on the new tree, got {path}"
    );

    drop(server);
}

/// A file the target tree doesn't have can't be landed on, so the switch lands somewhere valid
/// instead of on a path that isn't there.
#[tokio::test]
async fn a_file_absent_from_the_target_branch_cannot_follow() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    // A worktree on a *new* branch created at HEAD, then a file that exists only in the main
    // checkout — so the tree genuinely lacks it.
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    std::fs::write(repo_root.join("only-here.rs"), "fn main() {}\n").unwrap();
    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("only-here.rs".into()),
            ..Default::default()
        },
    )
    .await;
    assert!(open.path.is_some());

    let bound: WorkspaceActivateResult = send_request::<WorkspaceBindWorktree>(
        &mut ws,
        &WorkspaceBindWorktreeParams {
            repo_id: Some(repo_root.to_string_lossy().into()),
            worktree: wt.name.clone(),
            open_last: true,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(bound.workspace.paths[0], wt.path, "we did move");
    // Whatever it landed on, it is not a path outside the tree we just entered. Landing on the old
    // checkout's copy would be the worst outcome: the same-looking file, edited in the tree you
    // just left.
    if let Some(path) = bound.opened.and_then(|o| o.path) {
        assert!(
            path.starts_with(&wt.path),
            "landed outside the tree we switched into: {path}"
        );
    }

    drop(server);
}

/// **The point of keying contexts by their bindings.** Binding moves *only the client that asked*.
///
/// This used to be the opposite, and deliberately so: a workspace had one binding set, so binding
/// re-rooted it under everyone standing in it and they were pushed the new shape to follow. That is
/// what made "two trees of one repo at once" impossible. Now a context is `(workspace, bindings)`,
/// the base is the empty set, and the two are separate entries — so the client that binds moves and
/// nobody else does.
#[tokio::test]
async fn binding_moves_only_the_client_that_asked() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    // A second client in the same workspace, viewing a file in the repo.
    let mut ws2 = Ws::connect(&server).await;
    let act2: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    let base_root = act2.workspace.paths[0].clone();
    assert_eq!(
        base_root,
        repo_root.to_string_lossy(),
        "client 2 is in the base"
    );
    let open2: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws2,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;

    // Client 1 binds.
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path, "client 1 moved");
    assert_eq!(
        bound.workspace.worktrees.len(),
        1,
        "and its info says which tree it is in"
    );

    // Client 2 is told nothing and moved nowhere. Asked again, it still reports the base — and its
    // buffer is still the base's copy, not closed out from under it.
    let act2_again: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws2,
        &WorkspaceActivateParams {
            worktrees: Some(Default::default()),
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(
        act2_again.workspace.paths[0], base_root,
        "client 2 stayed on the configured roots"
    );
    assert!(
        act2_again.workspace.worktrees.is_empty(),
        "…and is bound to nothing"
    );
    let content: aether_protocol::buffer::BufferContentResult =
        send_request::<aether_protocol::buffer::BufferContent>(
            &mut ws2,
            &aether_protocol::buffer::BufferContentParams {
                buffer_id: open2.buffer_id,
            },
        )
        .await;
    assert!(
        !content.text.is_empty(),
        "client 2's buffer survived a bind it had nothing to do with"
    );

    drop(server);
}

/// Each context keeps its **own** buffer list, and going back and forth restores rather than
/// accumulates.
///
/// The old model moved buffers with the workspace, so there was one list and the risk was
/// duplicating it. Contexts keep separate lists — which is the point — so what has to hold now is
/// that returning to one finds what you left there.
#[tokio::test]
async fn each_context_keeps_its_own_buffers() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    let base_open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;
    let base_path = base_open.path.clone().expect("a file buffer");
    assert!(base_path.starts_with(repo_root.to_string_lossy().as_ref()));

    // Into the tree: the file follows, but as the *tree's* copy.
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);
    let in_tree = bound
        .opened
        .and_then(|o| o.path)
        .expect("the file you were on follows you in");
    assert!(
        in_tree.starts_with(&wt.path),
        "the tree's copy, not the checkout's: {in_tree}"
    );
    assert_ne!(in_tree, base_path);

    // ...and back out to the base, which still has its own copy open.
    let back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    assert_eq!(
        back.workspace.paths[0],
        repo_root.to_string_lossy(),
        "an empty admin name unbinds"
    );
    assert!(
        back.workspace.worktrees.is_empty(),
        "and the context is the base again"
    );
    let landed = back.opened.and_then(|o| o.path).expect("landed on a file");
    assert!(
        landed.starts_with(repo_root.to_string_lossy().as_ref()),
        "back on the checkout's copy: {landed}"
    );

    drop(server);
}

/// …and its **own jumplist**, for a reason stronger than tidiness: captured entries carry absolute
/// paths into one tree, so a list that followed a rebind would step you into the tree you just
/// left — the same-looking file, edited in the wrong checkout. Keying entries by their bindings
/// makes that unrepresentable, and the list you left behind is still there when you come back.
#[tokio::test]
async fn each_context_keeps_its_own_jumplist() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    // Untracked, so it exists in the checkout and *not* in a worktree built from HEAD — which makes
    // "the base's entries" a set the feature tree could not possibly resolve.
    std::fs::write(repo_root.join("needle.rs"), "needle\n").unwrap();
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    // Capture the single hit while standing in the base.
    let _ = send_request::<PickerView>(
        &mut ws,
        &PickerViewParams {
            limit: 30,
            ..view_params(PickerKind::Grep)
        },
    )
    .await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await;
    let _: () = send_request::<PickerQuery>(
        &mut ws,
        &PickerQueryParams {
            filters: Default::default(),
            kind: PickerKind::Grep,
            query: "needle".into(),
            generation: 1,
        },
    )
    .await;
    let _ = drain_grep_until_done(&mut ws).await;
    let captured = capture_grep_results(&mut ws, "needle.rs", 0, 0).await;
    assert_eq!(captured.total, 1, "one hit, in the checkout");

    // Into the tree: its own context, its own (empty) list. The base's entries do not follow.
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(bound.workspace.paths[0], wt.path);
    let in_tree = open_test_buffer(&mut ws, "a.rs").await;
    set_point_cursor(&mut ws, in_tree, LogicalPosition { line: 0, col: 0 }).await;
    let outcome = step_results(&mut ws, in_tree, Direction::Forward).await;
    assert!(
        matches!(outcome, JumplistStepResult::Empty),
        "the tree's context has captured nothing; the base's list must not step here: {outcome:?}"
    );
    // Nor can it be *cleared* from here — a clear reaches exactly as far as a step does.
    assert_eq!(
        clear_jumplist(&mut ws, Some(in_tree)).await.cleared,
        0,
        "clearing the tree's empty list must not reach into the base's"
    );

    // Back out: the base still holds what was captured there.
    let back = bind(&mut ws, std::path::Path::new(&wt.path), "").await;
    assert!(back.workspace.worktrees.is_empty(), "the base again");
    let in_base = open_test_buffer(&mut ws, "a.rs").await;
    set_point_cursor(&mut ws, in_base, LogicalPosition { line: 0, col: 0 }).await;
    let target = step_results(&mut ws, in_base, Direction::Forward)
        .await
        .moved()
        .expect("the base's capture was waiting where it was left");
    let path = target.path.expect("a file entry");
    assert!(
        path.starts_with(repo_root.to_string_lossy().as_ref()) && path.ends_with("needle.rs"),
        "stepped into the checkout it was captured from, got {path}"
    );

    drop(server);
}

/// The single-buffer case, which the MRU head happens to get right too.
#[tokio::test]
async fn the_rebinding_client_lands_on_the_same_file_on_the_new_tree() {
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();

    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;
    assert!(open.path.as_deref().is_some_and(|p| p.ends_with("a.rs")));

    let bound: WorkspaceActivateResult = send_request::<WorkspaceBindWorktree>(
        &mut ws,
        &WorkspaceBindWorktreeParams {
            repo_id: Some(repo_root.to_string_lossy().into()),
            worktree: wt.name.clone(),
            open_last: true,
            ..Default::default()
        },
    )
    .await;
    let landed = bound.opened.expect("a bind with open_last lands somewhere");
    let path = landed
        .path
        .expect("…and it should be a file, not a scratch");
    assert!(
        path.starts_with(&wt.path) && path.ends_with("a.rs"),
        "landed on the same file on the new tree, got {path}"
    );

    drop(server);
}

#[tokio::test]
async fn removing_the_worktree_you_are_in_returns_you_to_the_configured_roots() {
    let (server, mut ws, repo_root, _notes, dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let bound = bind(&mut ws, &repo_root, &wt.name).await;
    assert_eq!(
        bound.workspace.paths[0], wt.path,
        "standing in the worktree"
    );

    // A clean buffer in the tree, so the removal has something open to rescue.
    let _open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;

    // Remove it while it is the active tree — named as *this* context sees the repo (the worktree).
    let removed: GitWorktreeRemoveResult = send_request::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(wt.path.clone()),
            name: wt.name.clone(),
            ..Default::default()
        },
    )
    .await;
    assert_eq!(removed.status, GitWorktreeRemoveStatus::Removed);
    assert!(
        !std::path::Path::new(&wt.path).exists(),
        "the tree really is gone"
    );

    // The workspace is back on its configured roots — not pointing into the hole.
    let after: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "p".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(
        after.workspace.paths[0],
        repo_root.to_string_lossy(),
        "the roots followed the unbind, without a restart"
    );
    let sessions = sessions_json(&dir);
    assert!(
        sessions["workspaces"]["p"]["worktrees"]
            .as_object()
            .is_none_or(|m| m.is_empty()),
        "and the binding went with it: {sessions}"
    );

    drop(server);
}

#[tokio::test]
async fn removal_refuses_while_a_buffer_in_the_tree_has_unsaved_edits() {
    // git can't see this: the file on disk is clean, the unsaved work is in the editor. `--force`
    // would take it out from under the buffer, so the refusal is ours to make.
    let (server, mut ws, repo_root, _notes, _dir) = setup_variant_workspace().await;
    let wt = worktree_add(&mut ws, &repo_root, "feature", true)
        .await
        .worktree
        .unwrap();
    let _bound = bind(&mut ws, &repo_root, &wt.name).await;

    let open: BufferOpenResult = send_request::<BufferOpen>(
        &mut ws,
        &BufferOpenParams {
            path_index: Some(0),
            relative_path: Some("a.rs".into()),
            ..Default::default()
        },
    )
    .await;
    let _typed: aether_protocol::input::EditResult = send_request::<InputText>(
        &mut ws,
        &InputTextParams {
            buffer_id: open.buffer_id,
            text: "x".into(),
            select_pasted: false,
            replace_selection: false,
            at: None,
        },
    )
    .await;

    let err = send_request_expect_error::<GitWorktreeRemove>(
        &mut ws,
        &GitWorktreeRemoveParams {
            repo_id: Some(wt.path.clone()),
            name: wt.name.clone(),
            force: true,
            ..Default::default()
        },
    )
    .await;
    assert_eq!(
        err["code"],
        serde_json::json!(aether_protocol::error::ErrorCode::DIRTY_BUFFERS_PREVENT_REMOVE.code()),
        "even --force must not discard an editor buffer's unsaved edits"
    );
    assert!(std::path::Path::new(&wt.path).exists());

    drop(server);
}

// ---- workspace/create + workspace/rename (validation) -------------------------------------------
//
// Only the paths that refuse *before* touching disk are covered here. The success paths write
// `<name>.toml` into the profile's real config directory, and unlike the app settings there is no
// injectable path for it yet — a test would litter (or clobber) the developer's own workspaces.

/// A name that can't become a filename is refused, and refused before anything is written.
#[tokio::test]
async fn workspace_create_refuses_a_name_that_is_not_a_filename() {
    let dir = tempfile::tempdir().unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;

    for bad in ["", "   ", "has/slash", "has\\backslash"] {
        let msg = send_request_expect_err::<WorkspaceCreate>(
            &mut ws,
            &WorkspaceCreateParams { name: bad.into() },
        )
        .await;
        assert!(
            !msg.is_empty(),
            "creating a workspace named {bad:?} should be refused"
        );
    }
    drop(server);
}

/// Renaming a workspace the server has never heard of is an error, not a silent no-op that would
/// leave the client believing a rename happened.
#[tokio::test]
async fn workspace_rename_refuses_an_unknown_workspace() {
    let dir = tempfile::tempdir().unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;

    let msg = send_request_expect_err::<WorkspaceRename>(
        &mut ws,
        &WorkspaceRenameParams {
            workspace: "no-such-workspace".into(),
            new_name: "whatever".into(),
        },
    )
    .await;
    assert!(
        msg.contains("no-such-workspace"),
        "the refusal should name what it couldn't find, got {msg:?}"
    );
    drop(server);
}

/// Renaming a workspace to the name it already has short-circuits: it returns the current info
/// without touching disk. Worth pinning because the disk path is `fs::rename`, and letting a
/// same-name rename reach it would be renaming a file onto itself.
#[tokio::test]
async fn workspace_rename_to_the_same_name_is_a_no_op() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().to_path_buf();
    let mut server = spawn_for_test("test-proj", vec![root.clone()])
        .await
        .unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    let info: WorkspaceInfo = send_request::<WorkspaceRename>(
        &mut ws,
        &WorkspaceRenameParams {
            workspace: "test-proj".into(),
            new_name: "test-proj".into(),
        },
    )
    .await;
    assert_eq!(info.name, "test-proj");
    assert_eq!(info.paths.len(), 1, "its roots come back untouched");

    // Still activatable under the same name — nothing was re-keyed underneath us.
    let again: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    assert_eq!(again.workspace.name, "test-proj");
    drop(server);
}

/// A new name that isn't a usable filename is refused before the config file is touched.
#[tokio::test]
async fn workspace_rename_refuses_an_invalid_new_name() {
    let dir = tempfile::tempdir().unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir.path().to_path_buf()])
        .await
        .unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;

    let msg = send_request_expect_err::<WorkspaceRename>(
        &mut ws,
        &WorkspaceRenameParams {
            workspace: "test-proj".into(),
            new_name: "a/b".into(),
        },
    )
    .await;
    assert!(!msg.is_empty(), "a path-separator name must be refused");
    drop(server);
}

// -------- workspace CRUD against a redirected store ----------------------------------------------
//
// These reach the *success* paths — writing, renaming and deleting `<name>.toml` — which was only
// possible once `ServerState::workspaces_dir` existed. Before it, a test doing any of this would
// have written into the developer's own configured workspaces.

/// A server whose workspace definitions live in a tempdir. Returns the server, the store path, and
/// the workspace root the tests declare projects under.
async fn setup_workspace_store() -> (
    aether_server::ServerHandle,
    std::path::PathBuf,
    std::path::PathBuf,
) {
    let dir = tempfile::tempdir().unwrap();
    let store = dir.path().join("workspaces");
    let root = dir.path().join("proj");
    std::fs::create_dir_all(root.join("web")).unwrap();
    std::fs::write(root.join("web/package.json"), "{}\n").unwrap();
    std::fs::write(root.join("a.txt"), "hi\n").unwrap();

    let mut server = spawn_for_test("seed", vec![root.clone()]).await.unwrap();
    server.state.lock().await.workspaces_dir = Some(store.clone());
    server.keep_alive(dir);
    (server, store, root)
}

/// `workspace/list` enumerates the store, and a workspace created through the RPC shows up in it.
/// Both halves were untestable while the store was the developer's real config directory.
#[tokio::test]
async fn workspace_list_reflects_what_create_wrote() {
    let (server, store, _root) = setup_workspace_store().await;
    let mut ws = Ws::connect(&server).await;

    let before: WorkspaceListResult =
        send_request::<WorkspaceList>(&mut ws, &WorkspaceListParams {}).await;
    assert!(
        before.workspaces.is_empty(),
        "a fresh store lists nothing, got {:?}",
        before.workspaces
    );

    let created: WorkspaceActivateResult = send_request::<WorkspaceCreate>(
        &mut ws,
        &WorkspaceCreateParams {
            name: "fresh".into(),
        },
    )
    .await;
    assert_eq!(created.workspace.name, "fresh");
    assert!(
        store.join("fresh.toml").exists(),
        "the definition lands in the redirected store, not the real config dir"
    );

    let after: WorkspaceListResult =
        send_request::<WorkspaceList>(&mut ws, &WorkspaceListParams {}).await;
    assert_eq!(
        after
            .workspaces
            .iter()
            .map(|w| w.name.as_str())
            .collect::<Vec<_>>(),
        vec!["fresh"]
    );
    drop(server);
}

/// Creating a workspace that already exists is refused rather than silently overwriting the
/// definition — a `fs::write` would have clobbered it.
#[tokio::test]
async fn workspace_create_refuses_a_name_already_in_the_store() {
    let (server, _store, _root) = setup_workspace_store().await;
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult =
        send_request::<WorkspaceCreate>(&mut ws, &WorkspaceCreateParams { name: "dup".into() })
            .await;

    let msg = send_request_expect_err::<WorkspaceCreate>(
        &mut ws,
        &WorkspaceCreateParams { name: "dup".into() },
    )
    .await;
    assert!(
        msg.contains("already exists"),
        "the refusal should say why, got {msg:?}"
    );
    drop(server);
}

/// Renaming moves the definition rather than copying it: the old name stops resolving and the new
/// one starts. `fs::rename` is the operation, so leaving the old file behind would be a silent
/// duplicate.
#[tokio::test]
async fn workspace_rename_moves_the_definition_in_the_store() {
    let (server, store, _root) = setup_workspace_store().await;
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceCreate>(
        &mut ws,
        &WorkspaceCreateParams {
            name: "before".into(),
        },
    )
    .await;
    assert!(store.join("before.toml").exists());

    let info: WorkspaceInfo = send_request::<WorkspaceRename>(
        &mut ws,
        &WorkspaceRenameParams {
            workspace: "before".into(),
            new_name: "after".into(),
        },
    )
    .await;
    assert_eq!(info.name, "after");
    assert!(store.join("after.toml").exists(), "the new name is on disk");
    assert!(
        !store.join("before.toml").exists(),
        "and the old one is gone — a rename, not a copy"
    );

    let listed: WorkspaceListResult =
        send_request::<WorkspaceList>(&mut ws, &WorkspaceListParams {}).await;
    assert_eq!(
        listed
            .workspaces
            .iter()
            .map(|w| w.name.as_str())
            .collect::<Vec<_>>(),
        vec!["after"]
    );
    drop(server);
}

/// A root is a directory. `add_root` is the only RPC that writes one, so this is the boundary that
/// lets the index, the watcher and `buffer/open`'s `base.join(rel)` treat every root as a tree —
/// they used to carry their own "what if this is a file" branches, kept alive by refactors from an
/// era when a workspace was a hand-authored list of arbitrary paths.
#[tokio::test]
async fn add_root_refuses_a_file() {
    let (server, store, root) = setup_workspace_store().await;
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceCreate>(
        &mut ws,
        &WorkspaceCreateParams {
            name: "proj".into(),
        },
    )
    .await;

    let err = send_request_expect_err::<WorkspaceAddRoot>(
        &mut ws,
        &WorkspaceAddRootParams {
            workspace: "proj".into(),
            // The fixture's own file, so this is a path that exists and canonicalizes — the
            // rejection is about what it *is*, not about it being missing.
            path: root.join("a.txt").to_string_lossy().into(),
        },
    )
    .await;
    assert!(
        err.contains("must be directories"),
        "expected a directory-only rejection, got {err:?}"
    );
    assert!(
        !std::fs::read_to_string(store.join("proj.toml"))
            .unwrap()
            .contains("a.txt"),
        "a refused root must not reach the TOML"
    );

    // The same workspace still takes the directory, so the guard rejects the file rather than
    // wedging the workspace.
    let ok: WorkspaceInfo = send_request::<WorkspaceAddRoot>(
        &mut ws,
        &WorkspaceAddRootParams {
            workspace: "proj".into(),
            path: root.to_string_lossy().into(),
        },
    )
    .await;
    assert_eq!(ok.paths.len(), 1);
    drop(server);
}

/// Declaring a project pins a language server to a subdirectory; dropping it takes it back out.
/// Both write the workspace's TOML, so both were untestable before the store could be redirected.
#[tokio::test]
async fn add_and_remove_project_round_trip_through_the_store() {
    let (server, store, root) = setup_workspace_store().await;
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceCreate>(
        &mut ws,
        &WorkspaceCreateParams {
            name: "proj".into(),
        },
    )
    .await;
    let _: WorkspaceInfo = send_request::<WorkspaceAddRoot>(
        &mut ws,
        &WorkspaceAddRootParams {
            workspace: "proj".into(),
            path: root.to_string_lossy().into(),
        },
    )
    .await;

    let added: WorkspaceInfo = send_request::<WorkspaceAddProject>(
        &mut ws,
        &WorkspaceAddProjectParams {
            workspace: "proj".into(),
            path_index: 0,
            relative_path: "web".into(),
            language: None,
        },
    )
    .await;
    let names: Vec<&str> = added
        .projects
        .iter()
        .map(|p| p.relative_path.as_str())
        .collect();
    assert_eq!(names, vec!["web"]);
    assert_eq!(
        added.projects[0].language, "typescript",
        "the language is inferred from package.json, not guessed by the client"
    );
    assert!(
        std::fs::read_to_string(store.join("proj.toml"))
            .unwrap()
            .contains("web"),
        "the project is persisted, not just held in memory"
    );

    let removed: WorkspaceInfo = send_request::<WorkspaceRemoveProject>(
        &mut ws,
        &WorkspaceRemoveProjectParams {
            workspace: "proj".into(),
            path_index: 0,
            relative_path: "web".into(),
        },
    )
    .await;
    assert!(removed.projects.is_empty(), "the project is gone");
    assert!(
        !std::fs::read_to_string(store.join("proj.toml"))
            .unwrap()
            .contains("web"),
        "and gone from disk too"
    );
    drop(server);
}
