// @generated by a one-off split of the former tests/integration.rs — hand-edit freely.
//! Shared harness for the server integration test binaries: the WebSocket plumbing
//! (`send_request`, `expect_notification`), and the fixtures the topic binaries build on.
//!
//! Every test binary compiles this module separately and reaches for a different subset of
//! it, so the parts a given binary doesn't touch are genuinely unused *in that binary* —
//! both the re-exported protocol surface and the fixtures. Without these two allows, each
//! binary would fail `clippy -D warnings` for the helpers its siblings need.
#![allow(dead_code, unused_imports)]
pub use aether_client::grid::Measured;
pub use aether_protocol::coords::{ElementRow, VisualRow};
pub use aether_protocol::ViewId;

pub use aether_protocol::buffer::{
    BufferChanged, BufferChangedParams, BufferContent, BufferContentParams, BufferContentResult,
    BufferCopy, BufferCopyParams, BufferCopyResult, BufferCut, BufferCutResult, BufferSave,
    BufferSaveParams, BufferSaveResult, BufferState, BufferStateParams, CopyScope,
};
pub use aether_protocol::buffer::{BufferReload, BufferReloadParams, BufferReloadResult};
pub use aether_protocol::cursor::{
    CursorMove, CursorMoveParams, CursorRedo, CursorSelectAll, CursorSelectAllParams,
    CursorSelectLine, CursorSelectLineParams, CursorSelectWord, CursorSelectWordParams, CursorSet,
    CursorSetParams, CursorState, CursorSwapAnchor, CursorSwapAnchorParams, CursorTreeSelect,
    CursorTreeSelectParams, CursorUndo, CursorUndoParams, CursorUndoResult, Direction, Granularity,
    Motion, SelectionEdge, TreeSelectDirection, VerticalDirection, WordBoundary,
};
pub use aether_protocol::envelope::{
    ClientInbound, JsonRpc, NotificationMethod, Request, RpcMethod,
};
pub use aether_protocol::git::{
    ApplyHunkStatus, ApplyScope, ConflictSide, GitAbortOperation, GitAbortOperationParams,
    GitAbortOperationResult, GitAbortStatus, GitApplyHunk, GitApplyHunkParams, GitApplyHunkResult,
    GitBaselineChoice, GitBaselineSource, GitBlameChanged, GitBlameChangedParams, GitBlameLine,
    GitBlameLineParams, GitBlameLineResult, GitCancel, GitCancelParams, GitCancelResult,
    GitCheckout, GitCheckoutParams, GitCheckoutResult, GitCheckoutStatus, GitCommit,
    GitCommitParams, GitCommitResult, GitDeleteBranch, GitDeleteBranchParams,
    GitDeleteBranchResult, GitDeleteBranchStatus, GitFetch, GitFetchParams, GitFetchResult,
    GitFetchStatus, GitFollowPatchLine, GitFollowPatchLineParams, GitFollowPatchLineResult,
    GitHead, GitOperationChanged, GitOperationKind, GitPrepareCommit, GitPrepareCommitParams,
    GitPrepareCommitResult, GitPull, GitPullParams, GitPullResult, GitPullStatus, GitPush,
    GitPushParams, GitPushResult, GitPushStatus, GitRefresh, GitRefreshParams, GitRefreshResult,
    GitRepoOperation, GitReset, GitResetParams, GitResetResult, GitResolveConflict,
    GitResolveConflictParams, GitResolveConflictResult, GitSetBaseline, GitSetBaselineParams,
    GitSetBaselineResult, GitSetBlameFollow, GitSetBlameFollowParams, GitSetDiffView,
    GitSetDiffViewParams, GitShow, GitShowParams, GitStashApply, GitStashApplyParams, GitStashDrop,
    GitStashDropParams, GitStashPush, GitStashPushParams, GitStashResult, GitStashStatus,
    GitWorktreeAdd, GitWorktreeAddParams, GitWorktreeAddResult, GitWorktreeAddStatus,
    GitWorktreeRemove, GitWorktreeRemoveParams, GitWorktreeRemoveResult, GitWorktreeRemoveStatus,
    HunkAction, ResolveConflictStatus, ShowTarget,
};
pub use aether_protocol::input::{
    BlockDepthParams, BlockUnit, BufferOnlyParams, CaseKind, CommentStyle, CountedEditParams,
    EditRedo, EditResult, EditUndo, InputAdjustNumber, InputAdjustNumberParams, InputBackspace,
    InputBlockDepth, InputChange, InputDedent, InputDelete, InputDeleteBlock, InputDeleteWord,
    InputDeleteWordParams, InputIndent, InputJoinLines, InputMoveBlock, InputMoveLines,
    InputMoveLinesParams, InputNewlineAndIndent, InputNewlineAndIndentParams, InputOpenBlock,
    InputOpenLine, InputOpenLineParams, InputPasteBlock, InputSurround, InputSurroundParams,
    InputTab, InputText, InputTextParams, InputToggleComment, InputToggleTask, InputTransformCase,
    InputTransformCaseParams, InputUnsurround, InputUnsurroundParams, LineSide, MoveBlockParams,
    OpenBlockParams, PasteBlockParams, SurroundTarget, ToggleCommentParams, ToggleTaskParams,
    UndoRedoParams, UndoResult,
};
pub use aether_protocol::input::{
    InputChangeLine, InputDeleteLine, InputReplaceLine, InputReplaceLineParams,
};
pub use aether_protocol::jumplist::{
    JumplistCapture, JumplistCaptureParams, JumplistCaptureResult, JumplistClear,
    JumplistClearParams, JumplistClearResult, JumplistStep, JumplistStepParams, JumplistStepResult,
    JumplistStepScope,
};
pub use aether_protocol::lsp::{
    DiagnosticDirection, FormatStatus, LspBufferParams, LspDocumentHighlight,
    LspDocumentHighlightParams, LspFormat, LspFormatResult, LspGotoDefinition,
    LspGotoDefinitionResult, LspHover, LspHoverResult, LspNavigateDiagnostic,
    LspNavigateDiagnosticParams, LspNavigateDiagnosticResult, LspReadiness, LspRestartServer,
    LspRestartServerParams, LspServerStatus, LspStatus, LspStatusChanged,
};
pub use aether_protocol::nav::{NavGoto, NavGotoParams, NavStep, NavStepParams, NavStepResult};
pub use aether_protocol::path::{PathDelete, PathDeleteParams, PathDeleteResult};
pub use aether_protocol::picker::{
    BufferDirtyState, CaseMode, GroupHeader, MatchOptions, PickerFilters, PickerGroupAction,
    PickerHide, PickerHideParams, PickerItem, PickerKind, PickerQuery, PickerQueryParams,
    PickerReset, PickerSelect, PickerSelectParams, PickerSelectResult, PickerSetGroup,
    PickerSetGroupParams, PickerSetGroupResult, PickerUpdate, PickerUpdateParams, PickerView,
    PickerViewParams, ScopedPath,
};
pub use aether_protocol::search::{
    SearchClear, SearchClearParams, SearchNavResult, SearchSet, SearchSetParams, SearchSetResult,
    SearchStep, SearchStepParams,
};
pub use aether_protocol::settings::{
    AppSettings, SettingsChanged, SettingsGet, SettingsGetParams, SettingsSet,
};
pub use aether_protocol::sneak::{
    SneakCancel, SneakCancelParams, SneakSelect, SneakSelectParams, SneakUpdate, SneakUpdateParams,
    SneakUpdateResult,
};
pub use aether_protocol::view::{
    BufferDescription, ViewClose, ViewCloseParams, ViewCloseResult, ViewClosed, ViewClosedParams,
    ViewOpen, ViewOpenParams, ViewOpenResult, ViewSetTransient, ViewSetTransientParams,
    ViewSetTransientResult, ViewState, ViewStateParams,
};
pub use aether_protocol::viewport::Element;
pub use aether_protocol::viewport::{
    BaselineRow, ConflictLine, DiagnosticSeverity, DiffMarker, DiffStage, EmphasisRange, PatchLine,
};
pub use aether_protocol::viewport::{
    ChromeKind, ScrollPosition, SliceRequest, ViewportLinesChanged, ViewportLinesChangedParams,
    ViewportResize, ViewportResizeParams, ViewportSetWrap, ViewportSetWrapParams,
    ViewportSubscribe, ViewportSubscribeParams, ViewportSubscribeResult, ViewportWindow,
    ViewportWindowParams, ViewportWindowResult, WrapMode,
};
pub use aether_protocol::workspace::{
    WorkspaceActivate, WorkspaceActivateParams, WorkspaceActivateResult, WorkspaceAddProject,
    WorkspaceAddProjectParams, WorkspaceAddRoot, WorkspaceAddRootParams, WorkspaceBindWorktree,
    WorkspaceBindWorktreeParams, WorkspaceCreate, WorkspaceCreateParams, WorkspaceDelete,
    WorkspaceDeleteParams, WorkspaceInfo, WorkspaceList, WorkspaceListParams, WorkspaceListResult,
    WorkspaceOpenPath, WorkspaceOpenPathParams, WorkspaceRemoveProject,
    WorkspaceRemoveProjectParams, WorkspaceRename, WorkspaceRenameParams,
};
pub use aether_protocol::LogicalPosition;
pub use aether_server::{spawn_for_test, spawn_for_test_multi};
pub use futures_util::{SinkExt, StreamExt};
pub use serde_json::Value;
pub use tokio_tungstenite::tungstenite::Message;

/// The raw socket a [`Ws`] wraps.
type RawWs =
    tokio_tungstenite::WebSocketStream<tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>>;

/// The test end of one client connection: the socket, the request-id counter, and a log of every
/// notification that arrived.
///
/// Ids are allocated here rather than written at the call site. They only have to be unique within
/// a connection and nothing asserts on their values, so hand-numbering them was noise that made
/// every insertion a renumbering decision — and a duplicate id silently matched the wrong reply.
pub struct Ws {
    inner: RawWs,
    next_id: u64,
    /// Every notification seen on this connection, in arrival order.
    ///
    /// `send_request` has to skip past notifications to find its reply. Dropping them on the floor
    /// meant a push could only be asserted by a test that happened to be watching at exactly the
    /// right moment — so a regression in `jumplist/changed`, a streaming picker row or
    /// `git/operation_changed` could pass the suite untouched. Keeping them lets a test assert
    /// after the fact, without predicting ordering. Read with [`Ws::saw`].
    ///
    /// Stored as `(method, params)` because `Notification` isn't `Clone`.
    seen: Vec<(String, serde_json::Value)>,
}

impl Ws {
    /// Connect to `server` as a client would (loopback origin, our own protocol version).
    pub async fn connect(server: &aether_server::ServerHandle) -> Self {
        Self::connect_url(server.ws_url()).await
    }

    /// [`Ws::connect`] for the few fixtures that carry a URL rather than the handle.
    pub async fn connect_url(url: impl Into<String>) -> Self {
        let (inner, _) = tokio_tungstenite::connect_async(url.into()).await.unwrap();
        Self {
            inner,
            next_id: 1,
            seen: Vec::new(),
        }
    }

    fn alloc_id(&mut self) -> u64 {
        let id = self.next_id;
        self.next_id += 1;
        id
    }

    /// Every `N` notification that has arrived on this connection so far, typed.
    ///
    /// Only covers frames already read — a notification the server hasn't sent, or that no
    /// `send_request`/`expect_notification` has yet read past, won't appear. Assert with this
    /// after the request that should have provoked the push.
    pub fn saw<N: NotificationMethod>(&self) -> Vec<N::Params> {
        self.seen
            .iter()
            .filter(|(method, _)| method == N::NAME)
            .map(|(_, params)| serde_json::from_value(params.clone()).expect("typed params"))
            .collect()
    }

    /// Every notification of `method` as raw JSON — for capturing a real push to replay against a
    /// client (a shell bug is reproduced by the bytes it received, not by a hand-built fixture).
    pub fn seen_raw(&self, method: &str) -> Vec<serde_json::Value> {
        self.seen
            .iter()
            .filter(|(m, _)| m == method)
            .map(|(_, params)| params.clone())
            .collect()
    }

    /// Forget the notifications seen so far, so a later [`Ws::saw`] speaks only about what follows.
    pub fn clear_seen(&mut self) {
        self.seen.clear();
    }

    /// Read the next frame, logging notifications as they go past and every opened view.
    async fn next_inbound(&mut self) -> ClientInbound {
        let text = next_text(self).await;
        let inbound: ClientInbound = serde_json::from_str(&text).expect("parseable inbound");
        match &inbound {
            ClientInbound::Notification(n) => {
                self.seen.push((n.method.clone(), n.params.clone()));
            }
            ClientInbound::Response(r) => record_opened_views(&r.result),
            ClientInbound::Error(_) => {}
        }
        inbound
    }
}

thread_local! {
    /// Every view a `view/open`-shaped result on this test's thread has reported, by the buffer
    /// it presents — the most recent first. See [`view_of`].
    static OPENED_VIEWS: std::cell::RefCell<std::collections::HashMap<u64, ViewId>> =
        std::cell::RefCell::new(std::collections::HashMap::new());
}

/// Note the view an open result reports: the result itself, or the open a composite carries
/// (`opened`, `target`, `open`). Not the buffers a focus result describes — an element's buffer
/// may have no view of its own, and a focus says nothing about one.
fn record_opened_views(result: &Value) {
    let mut candidates = vec![result];
    for key in ["opened", "target", "open"] {
        if let Some(v) = result.get(key) {
            candidates.push(v);
        }
    }
    for v in candidates {
        let (Some(buffer), Some(view)) = (
            v.get("buffer_id").and_then(Value::as_u64),
            v.get("view_id").and_then(Value::as_u64),
        ) else {
            continue;
        };
        if v.get("line_count").is_none() || view == 0 {
            continue;
        }
        OPENED_VIEWS.with(|m| {
            m.borrow_mut().insert(buffer, ViewId(view));
        });
    }
}

/// The view this test most recently opened `buffer_id` through — what the wire names where a
/// test reasons in buffers. A test that holds only a buffer id (from [`setup_with_buffer`], say)
/// subscribes to, closes and reopens *this*; the ids are unrelated numbers, and the server hands
/// the view out only in the open's result, which every helper here reads on the way past.
pub fn view_of(buffer_id: u64) -> ViewId {
    OPENED_VIEWS.with(|m| {
        m.borrow().get(&buffer_id).copied().unwrap_or_else(|| {
            panic!("no view opened for buffer {buffer_id} on this test — open it first")
        })
    })
}

impl std::ops::Deref for Ws {
    type Target = RawWs;
    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl std::ops::DerefMut for Ws {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}

/// Stamp `path`'s modification time a few seconds into the future.
///
/// For the tests that need one file to read as newer than another. Filesystem mtime granularity is
/// coarse — a second on some filesystems — so arranging that by *waiting* costs a real second of
/// every run, and still only probably works. Setting it is exact and free.
pub fn stamp_modified_ahead(path: &std::path::Path) {
    let file = std::fs::File::options()
        .write(true)
        .open(path)
        .expect("open to stamp mtime");
    let ahead = std::time::SystemTime::now() + std::time::Duration::from_secs(5);
    file.set_times(std::fs::FileTimes::new().set_modified(ahead))
        .expect("set mtime");
}

/// Wait until the server has no deferred work outstanding — every debounced follow-up provoked so
/// far has run (or been superseded) and nothing more is coming.
///
/// This is how a test asserts that something *didn't* happen. Absence can't be polled for, so the
/// alternative is to sleep longer than the debounce and hope, which passes on an idle machine and
/// fails on a loaded one. Waiting for quiescence turns the same assertion into an exact one, and
/// it is sound because the work is counted while the provoking RPC still holds the state lock —
/// by the time the reply is in hand, it is already outstanding.
///
/// The timeout is a failure bound, not a cost: a quiet server returns immediately.
pub async fn settled(server: &aether_server::ServerHandle) {
    let deferred = server.state.lock().await.deferred.clone();
    tokio::time::timeout(std::time::Duration::from_secs(10), deferred.wait_quiet())
        .await
        .expect("server never went quiet: deferred work is outstanding");
}

/// Stamp `path`'s modification time a few seconds into the past.
///
/// The mirror of [`stamp_modified_ahead`], for the watcher fixtures: a buffer records the file's
/// mtime when it loads, and the self-save filter treats a later write with an *equal* mtime as its
/// own. Backdating the file before it is loaded makes every subsequent write strictly newer, which
/// sleeping before the load only achieved probabilistically — and paid for on every run.
pub fn stamp_modified_behind(path: &std::path::Path) {
    let file = std::fs::File::options()
        .write(true)
        .open(path)
        .expect("open to stamp mtime");
    let behind = std::time::SystemTime::now() - std::time::Duration::from_secs(5);
    file.set_times(std::fs::FileTimes::new().set_modified(behind))
        .expect("set mtime");
}

/// Poll `check` until it answers `Some`, then return it. Panics after ~10s naming `what`.
///
/// The alternative — sleep a fixed guess, then assert — is how a suite acquires flakes: the guess
/// holds on an idle machine and fails on a loaded one, in a test that has nothing to do with the
/// thing that actually broke. Use this whenever the wait is for *something to happen*. A wait for
/// the clock itself (coarse filesystem mtime granularity) is a different thing and stays a sleep.
pub async fn eventually<T>(what: &str, mut check: impl FnMut() -> Option<T>) -> T {
    for _ in 0..400 {
        if let Some(v) = check() {
            return v;
        }
        tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    }
    panic!("timed out waiting for {what}");
}

/// Poll until the server has exactly `n` clients connected. A dropped socket is torn down
/// asynchronously, so tests that depend on the disconnect having landed wait for it here.
pub async fn wait_for_client_count(server: &aether_server::ServerHandle, n: usize) {
    for _ in 0..400 {
        if server.state.lock().await.clients.len() == n {
            return;
        }
        tokio::time::sleep(std::time::Duration::from_millis(25)).await;
    }
    let got = server.state.lock().await.clients.len();
    panic!("client count never reached {n} (still {got})");
}

pub async fn next_text(ws: &mut Ws) -> String {
    loop {
        let msg = ws.next().await.expect("ws closed").expect("ws error");
        if let Message::Text(t) = msg {
            return t.to_string();
        }
    }
}

pub async fn send_request<M: RpcMethod>(ws: &mut Ws, params: &M::Params) -> M::Result {
    let id = send_no_wait::<M>(ws, params).await;
    await_response::<M>(ws, id).await
}

/// [`send_request`] for a call that may be refused: the typed result, or the error the server
/// answered with. For the tests that ask "is this still here?" of a view or a buffer.
pub async fn send_request_result<M: RpcMethod>(
    ws: &mut Ws,
    params: &M::Params,
) -> Result<M::Result, Value> {
    let id = send_no_wait::<M>(ws, params).await;
    loop {
        match ws.next_inbound().await {
            ClientInbound::Response(r) if r.id == id => {
                return Ok(serde_json::from_value(r.result).expect("typed result"));
            }
            ClientInbound::Error(e) if e.id == id => {
                return Err(serde_json::to_value(e.error).unwrap_or(Value::Null));
            }
            ClientInbound::Notification(_)
            | ClientInbound::Response(_)
            | ClientInbound::Error(_) => {}
        }
    }
}

/// Send `M` without waiting for its reply, returning the id to await it by. For the handful of
/// tests that need a request in flight while they do something else (cancel it, race a second
/// client against it) — pair with [`await_response`].
pub async fn send_no_wait<M: RpcMethod>(ws: &mut Ws, params: &M::Params) -> u64 {
    let id = ws.alloc_id();
    let req = Request {
        jsonrpc: JsonRpc,
        id,
        method: M::NAME.into(),
        params: Some(serde_json::to_value(params).unwrap()),
    };
    let s = serde_json::to_string(&req).unwrap();
    ws.send(Message::text(s)).await.unwrap();
    id
}

/// Await the reply to an id from [`send_no_wait`], draining anything that arrives first.
pub async fn await_response<M: RpcMethod>(ws: &mut Ws, id: u64) -> M::Result {
    loop {
        match ws.next_inbound().await {
            ClientInbound::Response(r) if r.id == id => {
                return serde_json::from_value(r.result).expect("typed result");
            }
            ClientInbound::Error(e) if e.id == id => {
                panic!("request {id} ({}) returned error: {:?}", M::NAME, e.error);
            }
            ClientInbound::Notification(_)
            | ClientInbound::Response(_)
            | ClientInbound::Error(_) => {
                // Another request's reply, or a push — logged on the way past (see `Ws::seen`).
            }
        }
    }
}

/// The `picker/view` params every picker test starts from: a fresh full open (`reset: All`),
/// window at the top, `limit: 50`, nothing else set. Tests that deviate spell out only the
/// deviating fields via struct update: `PickerViewParams { buffer_id: Some(b), ..view_params(k) }`
/// — so the field a test *cares about* is the only one visible at the call site.
/// [`view_params`] for a picker opened *over a buffer* — how the repo-resolving pickers (branches,
/// log, stash) are invoked in practice. They take their repo from this buffer and nowhere else, so
/// omitting it is refused rather than falling back to the workspace.
pub fn view_params_on(kind: PickerKind, buffer_id: u64) -> PickerViewParams {
    PickerViewParams {
        view_id: None,
        buffer_id: Some(buffer_id),
        ..view_params(kind)
    }
}

pub fn view_params(kind: PickerKind) -> PickerViewParams {
    PickerViewParams {
        view_id: None,
        kind,
        reset: PickerReset::All,
        offset: 0,
        limit: 50,
        from_selection: false,
        filters: None,
        center_on: None,
        center_on_cursor: None,
        directory_path: None,
        buffer_id: None,
        explorer_roots: false,
        keybindings: None,
    }
}

/// Like `send_request` but expects the RPC to return an error; returns the error message.
/// Panics on a successful response.
pub async fn send_request_expect_err<M: RpcMethod>(ws: &mut Ws, params: &M::Params) -> String {
    let id = send_no_wait::<M>(ws, params).await;
    loop {
        match ws.next_inbound().await {
            ClientInbound::Response(r) if r.id == id => {
                panic!("expected error for {}, got Ok: {:?}", M::NAME, r.result);
            }
            ClientInbound::Error(e) if e.id == id => return e.error.message,
            _ => {}
        }
    }
}

/// Read frames until one matching notification arrives. Panics if the stream ends first.
pub async fn expect_notification<N: NotificationMethod>(ws: &mut Ws) -> N::Params {
    loop {
        if let ClientInbound::Notification(n) = ws.next_inbound().await {
            if n.method == N::NAME {
                return serde_json::from_value(n.params).expect("typed params");
            }
        }
    }
}

// -------- cursor + input ------------------------------------------------------------------------

pub async fn setup_with_buffer(
    content: &str,
) -> (
    aether_server::ServerHandle,
    Ws,
    u64, // buffer_id
) {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("buf.txt");
    std::fs::write(&path, content).unwrap();
    let dir_path = dir.path().to_path_buf();

    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some("buf.txt".into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    (server, ws, open.buffer_id)
}

/// Convenience for the granularity tests: one `cursor/set` round-trip.
pub async fn set_snapped(
    ws: &mut Ws,
    buffer_id: u64,
    position: LogicalPosition,
    anchor: LogicalPosition,
    granularity: Granularity,
) -> CursorState {
    send_request::<CursorSet>(
        ws,
        &CursorSetParams {
            granularity,
            buffer_id,
            position,
            anchor,
        },
    )
    .await
}

// ---- input/move_lines ---------------------------------------------------------------------------

pub async fn buffer_text(ws: &mut Ws, buffer_id: u64) -> String {
    // Subscribe to a wide-enough viewport and concatenate the visible-text lines.
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        ws,
        &ViewportSubscribeParams {
            view_id: view_of(buffer_id),
            cols: 200,
            rows: 100,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    sub.window
        .root
        .lines()
        .into_iter()
        .map(|l| l.visual_rows[0].segments[0].text.as_str().to_string())
        .collect::<Vec<_>>()
        .join("\n")
}

/// Boilerplate for the comment-toggle tests that need a language: write `content` to
/// `file_name` in a fresh workspace, open it, return the connection and the open result.
pub async fn setup_with_named_file(
    file_name: &str,
    content: &str,
) -> (aether_server::ServerHandle, Ws, ViewOpenResult) {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join(file_name), content).unwrap();
    let dir_path = dir.path().to_path_buf();
    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some(file_name.into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    (server, ws, open)
}

// -------- picker --------------------------------------------------------------------------------

pub async fn setup_picker_workspace() -> (aether_server::ServerHandle, Ws) {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    // A small mix of file names so fuzzy matching has something to chew on.
    std::fs::create_dir_all(dir_path.join("src")).unwrap();
    std::fs::create_dir_all(dir_path.join("docs")).unwrap();
    std::fs::write(dir_path.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(dir_path.join("src/lib.rs"), "pub fn lib() {}\n").unwrap();
    std::fs::write(dir_path.join("docs/intro.md"), "# intro\n").unwrap();
    std::fs::write(dir_path.join("README.md"), "# workspace\n").unwrap();

    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws)
}

// -------- view picker --------------------------------------------------------------------------

/// Workspace + handshake. Same shape as `setup_picker_workspace` but loads a few files we'll
/// open through `view/open` so the view picker has something to surface.
pub async fn setup_buffer_picker_workspace() -> (aether_server::ServerHandle, Ws) {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::create_dir_all(dir_path.join("src")).unwrap();
    std::fs::write(dir_path.join("src/main.rs"), "fn main() {}\n").unwrap();
    std::fs::write(dir_path.join("src/lib.rs"), "pub fn lib() {}\n").unwrap();
    std::fs::write(dir_path.join("README.md"), "# workspace\n").unwrap();
    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws)
}

// -------- picker grep ---------------------------------------------------------------------------

pub async fn setup_grep_workspace() -> (aether_server::ServerHandle, Ws) {
    let dir = tempfile::tempdir().unwrap();
    let dir_path = dir.path().to_path_buf();
    std::fs::create_dir_all(dir_path.join("src")).unwrap();
    std::fs::write(
        dir_path.join("src/main.rs"),
        "fn main() {\n    needle();\n    needle();\n}\n",
    )
    .unwrap();
    std::fs::write(
        dir_path.join("src/lib.rs"),
        "fn needle() {}\nfn other() {}\n",
    )
    .unwrap();
    std::fs::write(dir_path.join("README.md"), "no match here\n").unwrap();

    let mut server = spawn_for_test("test-proj", vec![dir_path]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws)
}

/// A collapsible picker window's `Group` header rows as `(header text, count, expanded)` triples —
/// the file's relative path or the label — which is what a collapsed window is made of by default.
/// Non-header rows are skipped.
pub fn group_rows(items: &[PickerItem]) -> Vec<(String, u32, bool)> {
    items
        .iter()
        .filter_map(|i| match i {
            PickerItem::Group {
                header,
                count,
                expanded,
            } => Some((
                match header {
                    GroupHeader::File { relative_path, .. } => relative_path.clone(),
                    GroupHeader::Label { label } => label.clone(),
                },
                *count,
                *expanded,
            )),
            _ => None,
        })
        .collect()
}

/// Expand one file group in a collapsible picker (`picker/set_group`) and return the header's
/// new absolute row plus the reshaped window. The window comes from a follow-up `Keep` re-view's
/// response, not from the set_group push — `send_request` discards notifications while waiting,
/// so the push may already be gone by the time the response is read. Uses request ids `id`
/// through `id + 2`.
pub async fn expand_file_group(
    ws: &mut Ws,
    kind: PickerKind,
    path: &str,
) -> (u32, PickerUpdateParams) {
    // The header is looked up in the live window rather than constructed, which is what a client
    // does — it echoes back a header it was pushed — and keeps the helper honest if a kind's
    // header shape ever changes.
    let window = send_request::<PickerView>(
        ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            ..view_params(kind)
        },
    )
    .await
    .update
    .expect("a Keep re-view carries its window");
    let header = window
        .items()
        .iter()
        .find_map(|i| match i {
            PickerItem::Group { header, .. } => {
                let label = match header {
                    GroupHeader::File { relative_path, .. } => relative_path.as_str(),
                    GroupHeader::Label { label } => label.as_str(),
                };
                (label == path).then(|| header.clone())
            }
            _ => None,
        })
        .unwrap_or_else(|| panic!("no group header labelled {path:?} in the window"));
    let result: PickerSetGroupResult = send_request::<PickerSetGroup>(
        ws,
        &PickerSetGroupParams {
            kind,
            action: PickerGroupAction::Expand { header },
        },
    )
    .await;
    let view = send_request::<PickerView>(
        ws,
        &PickerViewParams {
            view_id: None,
            reset: PickerReset::Keep,
            ..view_params(kind)
        },
    )
    .await;
    (
        result
            .run
            .expect("selected group is present in the ranking")
            .header_row,
        view.update.expect("a Keep re-view carries its window"),
    )
}

/// Drain `picker/update` notifications until one arrives with `ticking: false` (the search has
/// finished). Returns the final params so the caller can assert on hit count and items.
pub async fn drain_grep_until_done(ws: &mut Ws) -> PickerUpdateParams {
    loop {
        let params: PickerUpdateParams = expect_notification::<PickerUpdate>(ws).await;
        if !params.ticking {
            return params;
        }
    }
}

/// Open a buffer at `relative_path` against an established (server, ws) handshake. Used by the
/// grep_navigate tests to put a buffer in scope before calling the RPC.
pub async fn open_test_buffer(ws: &mut Ws, relative_path: &str) -> u64 {
    let open: ViewOpenResult = send_request::<ViewOpen>(
        ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some(relative_path.into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    open.buffer_id
}

/// Park the client's cursor at `position` (anchor == position, a point cursor) on the buffer.
/// Used by the grep_navigate tests to set up the cursor position the handler will look up.
pub async fn set_point_cursor(ws: &mut Ws, buffer_id: u64, position: LogicalPosition) {
    let _: CursorState = send_request::<CursorSet>(
        ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position,
            anchor: position,
        },
    )
    .await;
}

/// Capture the client's grep results into the jumplist (the picker `Ctrl-j` flow) with the
/// hit at `(relative_path, line, col)` as the highlighted row. Capture doesn't navigate — the
/// client follows with the Jumplist picker. The item's preview/match_indices are irrelevant to
/// identity (`(path_index, relative_path, line, col)`), so they ride empty.
pub async fn capture_grep_results(
    ws: &mut Ws,
    relative_path: &str,
    line: u32,
    col: u32,
) -> JumplistCaptureResult {
    let r: Option<JumplistCaptureResult> = send_request::<JumplistCapture>(
        ws,
        &JumplistCaptureParams {
            kind: PickerKind::Grep,
            item: PickerItem::GrepHit {
                path_index: 0,
                relative_path: relative_path.into(),
                line,
                col,
                preview: String::new(),
                match_indices: vec![],
            },
        },
    )
    .await;
    r.expect("grep candidates are non-empty, capture snapshots them")
}

/// A bare `jumplist/step` (no composite open), returning the raw outcome.
pub async fn step_results(ws: &mut Ws, buffer_id: u64, direction: Direction) -> JumplistStepResult {
    send_request::<JumplistStep>(
        ws,
        &JumplistStepParams {
            buffer_id,
            direction,
            count: 1,
            scope: JumplistStepScope::Full,
            open: false,
        },
    )
    .await
}

/// `Space Alt-j`: discard the captured list.
pub async fn clear_jumplist(ws: &mut Ws, buffer_id: Option<u64>) -> JumplistClearResult {
    send_request::<JumplistClear>(ws, &JumplistClearParams { buffer_id }).await
}

/// Wait up to `max` for a matching notification; panics with a useful message on timeout.
pub async fn expect_notification_within<N: NotificationMethod>(
    ws: &mut Ws,
    max: std::time::Duration,
) -> N::Params {
    match tokio::time::timeout(max, expect_notification::<N>(ws)).await {
        Ok(p) => p,
        Err(_) => panic!("timed out waiting for notification {}", N::NAME),
    }
}

/// Init a git repo at `dir` and commit `name` with `content` under a known author.
pub fn git_commit_file(dir: &std::path::Path, name: &str, content: &str) {
    let repo = git2::Repository::init(dir).unwrap();
    std::fs::write(dir.join(name), content).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(std::path::Path::new(name)).unwrap();
    index.write().unwrap();
    let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
    let sig = git2::Signature::now("Test", "test@example.com").unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init commit", &tree, &[])
        .unwrap();
}

/// Stage the file's current working-tree content (`git add <name>`).
pub fn git_stage_file(dir: &std::path::Path, name: &str) {
    let repo = git2::Repository::open(dir).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(std::path::Path::new(name)).unwrap();
    index.write().unwrap();
}

// -------- git/apply_hunk (stage / unstage / revert) ----------------------------------------------

/// Spawn a server over `dir`, activate a workspace, and open `name`. Shared scaffolding for the
/// `git/apply_hunk` tests, which all start from "a repo-backed buffer is open".
pub async fn setup_git_apply(
    dir: &std::path::Path,
    proj: &str,
    name: &str,
) -> (
    aether_server::ServerHandle,
    Ws,
    u64, // buffer_id
) {
    let server = spawn_for_test(proj, vec![dir.to_path_buf()]).await.unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: proj.into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some(name.into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    (server, ws, open.buffer_id)
}

pub async fn apply_hunk(ws: &mut Ws, buffer_id: u64, action: HunkAction) -> GitApplyHunkResult {
    send_request::<GitApplyHunk>(
        ws,
        &GitApplyHunkParams {
            buffer_id,
            action,
            scope: Default::default(),
        },
    )
    .await
}

/// The file's staged (index) content, or `None` when it has no index entry.
pub fn index_text(dir: &std::path::Path, name: &str) -> Option<String> {
    let repo = git2::Repository::open(dir).unwrap();
    let index = repo.index().unwrap();
    let entry = index.get_path(std::path::Path::new(name), 0)?;
    let blob = repo.find_blob(entry.id).unwrap();
    Some(String::from_utf8(blob.content().to_vec()).unwrap())
}

// ---- real-LSP verification ----------------------------------------------------------------------
//
// These open a file against an actual language server and assert our client integrates with it:
// `lsp_diag_*` assert a diagnostic rides back on `viewport/lines_changed` (the full inbound path);
// `lsp_ready_*` assert the server reaches `Ready` via `lsp/status_changed` (handshake only, for
// servers whose diagnostics need a full workspace or don't fire on a lone file). All are `#[ignore]`d
// (need the server installed) and FAIL — not skip — if a prerequisite is missing, since running
// them is an explicit opt-in. Provision the whole toolchain with `mise install`; run with:
//   AETHER_TEST_TYPESCRIPT_DIR="$(mise where npm:typescript)/lib/node_modules/typescript" \
//     mise exec -- cargo test -p aether-server --test lsp -- --ignored --test-threads=1
// Each test names the server it needs; install it however you like as long as it's on PATH.

/// Spawn a server over `root`, connect, activate, open `rel_path`, subscribe a viewport. Returns the
/// handle (keep it alive) and the socket.
pub async fn open_and_subscribe(
    workspace: &str,
    root: &std::path::Path,
    rel_path: &str,
) -> (aether_server::ServerHandle, Ws) {
    open_and_subscribe_with_lsp(workspace, root, rel_path, Vec::new()).await
}

/// [`open_and_subscribe`] with in-process **dummy language servers** registered per language (see
/// `aether_server::DummyLspConfig`), so the opened buffer's LSP launch uses the dummy instead of a
/// real server binary — deterministic and fast, so the test needn't be `#[ignore]`d.
pub async fn open_and_subscribe_with_lsp(
    workspace: &str,
    root: &std::path::Path,
    rel_path: &str,
    dummy_lsp: Vec<(String, aether_server::DummyLspConfig)>,
) -> (aether_server::ServerHandle, Ws) {
    let server =
        aether_server::spawn_for_test_with_lsp(workspace, vec![root.to_path_buf()], dummy_lsp)
            .await
            .unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: workspace.into(),
            open_last: false,
        },
    )
    .await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            transient: None,
            path_index: Some(0),
            relative_path: Some(rel_path.into()),
            language: None,
            create_if_missing: false,
            jump_to: None,
            ..Default::default()
        },
    )
    .await;
    let _sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        &mut ws,
        &ViewportSubscribeParams {
            view_id: open.view_id,
            cols: 100,
            rows: 40,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view: false,
        },
    )
    .await;
    (server, ws)
}

pub fn lay_out(files: &[(&str, &str)]) -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    for (name, contents) in files {
        let path = dir.path().join(name);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(path, contents).unwrap();
    }
    dir
}

/// [`send_request`], but returning every `picker/update` push that arrived ahead of the response —
/// the connection writer prefers replies over pushes, so which lands first is nondeterministic and
/// a test asserting on a query's own push must capture both sides of the race.
pub async fn send_request_collecting_updates<M: RpcMethod>(
    ws: &mut Ws,
    params: &M::Params,
) -> (M::Result, Vec<PickerUpdateParams>) {
    let id = send_no_wait::<M>(ws, params).await;
    let mut updates = Vec::new();
    loop {
        match ws.next_inbound().await {
            ClientInbound::Response(r) if r.id == id => {
                return (
                    serde_json::from_value(r.result).expect("typed result"),
                    updates,
                );
            }
            ClientInbound::Error(e) if e.id == id => {
                panic!("request {id} ({}) returned error: {:?}", M::NAME, e.error);
            }
            ClientInbound::Notification(n) if n.method == PickerUpdate::NAME => {
                updates.push(serde_json::from_value(n.params).expect("typed params"));
            }
            _ => {}
        }
    }
}

/// Place the cursor at `(line, col)` in `buffer_id`.
pub async fn set_cursor(ws: &mut Ws, buffer_id: u64, line: u32, col: u32) {
    let _: CursorState = send_request::<CursorSet>(
        ws,
        &CursorSetParams {
            granularity: Granularity::Char,
            buffer_id,
            position: LogicalPosition { line, col },
            anchor: LogicalPosition { line, col },
        },
    )
    .await;
}

// -------- picker filters --------------------------------------------------------------------------

/// Git-backed workspace exercising every grep filter. Contents (and their "needle" hits):
///
/// - `src/main.rs`   committed, clean — `needle();` + `needles();`        (2 smart-case hits)
/// - `src/lib.rs`    committed, clean — `fn needle()` + `"a.b"` + `"axb"` (1 hit)
/// - `README.md`     committed, clean — `Needle` + `needle`               (2 smart-case hits)
/// - `changed.rs`    committed then modified — `needle changed`           (1 hit)
/// - `new.rs`        untracked — `needle new`                             (1 hit)
/// - `debug.log`     gitignored — `needle ignored`                        (only with +ignored)
/// - `.hidden.rs`    committed, hidden — `needle hidden`                  (only with +hidden)
///
/// Baseline smart-case "needle" over the default walk: 7 hits.
pub async fn setup_grep_filter_workspace() -> (aether_server::ServerHandle, Ws) {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().to_path_buf();

    let repo = git2::Repository::init(&root).unwrap();
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::write(
        root.join("src/main.rs"),
        "fn main() {\n    needle();\n    needles();\n}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "fn needle() {}\nlet pat = \"a.b\";\nlet other = \"axb\";\n",
    )
    .unwrap();
    std::fs::write(root.join("README.md"), "Needle in docs\nneedle again\n").unwrap();
    std::fs::write(root.join("changed.rs"), "before\n").unwrap();
    std::fs::write(root.join(".hidden.rs"), "needle hidden\n").unwrap();
    std::fs::write(root.join(".gitignore"), "*.log\n").unwrap();
    let mut index = repo.index().unwrap();
    for rel in [
        "src/main.rs",
        "src/lib.rs",
        "README.md",
        "changed.rs",
        ".hidden.rs",
        ".gitignore",
    ] {
        index.add_path(std::path::Path::new(rel)).unwrap();
    }
    index.write().unwrap();
    let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
    let sig = git2::Signature::now("Test", "t@e.com").unwrap();
    repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
        .unwrap();
    drop(tree);
    drop(index);
    drop(repo);

    // Working-tree state after the commit.
    std::fs::write(root.join("changed.rs"), "needle changed\n").unwrap(); // modified
    std::fs::write(root.join("new.rs"), "needle new\n").unwrap(); // untracked
    std::fs::write(root.join("debug.log"), "needle ignored\n").unwrap(); // gitignored

    let mut server = spawn_for_test("test-proj", vec![root]).await.unwrap();
    server.keep_alive(dir);
    let mut ws = Ws::connect(&server).await;
    let _: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "test-proj".into(),
            open_last: false,
        },
    )
    .await;

    // Open the grep picker once; individual tests drive it via picker/query.
    let _ = send_request::<PickerView>(&mut ws, &view_params(PickerKind::Grep)).await;
    let _ = expect_notification::<PickerUpdate>(&mut ws).await; // initial empty push
    (server, ws)
}

/// Send a grep query carrying `filters` and drain pushes until the matching generation's final
/// (non-ticking) update arrives.
pub async fn grep_with_filters(
    ws: &mut Ws,
    query: &str,
    filters: PickerFilters,
    generation: u64,
) -> PickerUpdateParams {
    let _: () = send_request::<PickerQuery>(
        ws,
        &PickerQueryParams {
            kind: PickerKind::Grep,
            query: query.into(),
            generation,
            filters,
        },
    )
    .await;
    loop {
        let params: PickerUpdateParams = expect_notification::<PickerUpdate>(ws).await;
        if params.generation == generation && !params.ticking {
            return params;
        }
    }
}

pub fn file_open_params(rel: &str, transient: Option<bool>) -> ViewOpenParams {
    ViewOpenParams {
        path_index: Some(0),
        relative_path: Some(rel.into()),
        language: None,
        create_if_missing: false,
        jump_to: None,
        transient,
        ..Default::default()
    }
}

/// Where a change step landed: what `git/navigate_hunk` used to answer, read off
/// `view/navigate_change`'s focus result so a test that steps by buffer still reads as it did.
#[derive(Debug)]
pub struct Landed {
    pub moved: bool,
    pub cursor: CursorState,
    /// The viewport the step was taken in — the connection's current one, since the subscribe
    /// that made it superseded whatever came before.
    pub viewport_id: aether_protocol::ViewportId,
}

/// One `view/navigate_change` step of `count` changes from `from_line` in `buffer_id`'s own view:
/// the cursor is parked there first and a viewport opened over the view — the step is a
/// viewport's, and a fresh subscribe supersedes whatever this connection had.
pub async fn navigate_change_from(
    ws: &mut Ws,
    buffer_id: u64,
    from_line: u32,
    direction: aether_protocol::viewport::FocusStep,
    count: u32,
) -> Landed {
    set_point_cursor(
        ws,
        buffer_id,
        LogicalPosition {
            line: from_line,
            col: 0,
        },
    )
    .await;
    let sub: ViewportSubscribeResult =
        send_request::<ViewportSubscribe>(ws, &transient_sub_params(buffer_id)).await;
    let landed: aether_protocol::viewport::ViewportFocusElementResult =
        send_request::<aether_protocol::viewport::ViewportNavigateChange>(
            ws,
            &aether_protocol::viewport::ViewportNavigateChangeParams {
                viewport_id: sub.viewport_id,
                direction,
                count: Some(count),
                grain: aether_protocol::viewport::NavigateGrain::Change,
                extend: false,
            },
        )
        .await;
    Landed {
        moved: landed.buffer.cursor.position.line != from_line,
        cursor: landed.buffer.cursor,
        viewport_id: sub.viewport_id,
    }
}

pub fn transient_sub_params(buffer_id: u64) -> ViewportSubscribeParams {
    ViewportSubscribeParams {
        view_id: view_of(buffer_id),
        cols: 80,
        rows: 10,
        overscan_rows: 0,
        scroll: ScrollPosition {
            element: 0,
            line: 0,
            sub_row: 0.0,
        },
        focus: None,
        wrap: WrapMode::None,
        continuation_marker_width: 0,
        tab_width: 4,
        diff_view: false,
    }
}

// -------- git repo fixtures ------------------------------------------------------------------------

/// A path as a [`RepoId`] — the canonicalized working directory, which is the string form every
/// repo-resolving RPC echoes back.
pub fn root_id(path: &std::path::Path) -> String {
    path.to_string_lossy().to_string()
}

/// A repo with a deterministic initial branch. libgit2 honours `init.defaultBranch`, so a plain
/// `Repository::init` would let the developer's global config decide the branch name and make
/// these assertions machine-dependent.
pub fn init_repo_at(dir: &std::path::Path) -> git2::Repository {
    let mut opts = git2::RepositoryInitOptions::new();
    opts.initial_head("main");
    git2::Repository::init_opts(dir, &opts).unwrap()
}

pub fn commit_file(repo: &git2::Repository, rel: &str, content: &str) {
    let workdir = repo.workdir().unwrap().to_path_buf();
    let path = workdir.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, content).unwrap();
    let mut index = repo.index().unwrap();
    index.add_path(std::path::Path::new(rel)).unwrap();
    index.write().unwrap();
    let tree = repo.find_tree(index.write_tree().unwrap()).unwrap();
    let sig = git2::Signature::now("Test", "test@example.com").unwrap();
    let parents = match repo.head().ok().and_then(|h| h.peel_to_commit().ok()) {
        Some(c) => vec![c],
        None => vec![],
    };
    repo.commit(
        Some("HEAD"),
        &sig,
        &sig,
        "init",
        &tree,
        &parents.iter().collect::<Vec<_>>(),
    )
    .unwrap();
}

/// `git/show`, unwrapping the buffer it materialised. Only a clean working tree answers with
/// nothing, so every caller that expects a patch or a file goes through here; the empty answer has
/// its own tests, which read `opened` directly.
pub async fn show_buffer(
    ws: &mut Ws,
    params: &aether_protocol::git::GitShowParams,
) -> aether_protocol::view::ViewOpenResult {
    send_request::<aether_protocol::git::GitShow>(ws, params)
        .await
        .opened
        .expect("git/show materialised a buffer")
}

pub async fn setup_repos_workspace(
    roots: Vec<std::path::PathBuf>,
) -> (aether_server::ServerHandle, Ws) {
    let server = spawn_for_test("repos-proj", roots).await.unwrap();
    let mut ws = Ws::connect(&server).await;
    let _act: WorkspaceActivateResult = send_request::<WorkspaceActivate>(
        &mut ws,
        &WorkspaceActivateParams {
            worktrees: None,
            name: "repos-proj".into(),
            open_last: false,
        },
    )
    .await;
    (server, ws)
}

/// [`setup_repos_workspace`] plus an open file, returning its buffer id.
///
/// Every git verb resolves its repo from the buffer it was invoked over, so a test that exercises
/// one needs a file open — the same thing the user has to do.
pub async fn setup_repos_workspace_on(
    roots: Vec<std::path::PathBuf>,
    relative_path: &str,
) -> (aether_server::ServerHandle, Ws, u64) {
    let (server, mut ws) = setup_repos_workspace(roots).await;
    let open: ViewOpenResult = send_request::<ViewOpen>(
        &mut ws,
        &ViewOpenParams {
            path_index: Some(0),
            relative_path: Some(relative_path.into()),
            ..Default::default()
        },
    )
    .await;
    (server, ws, open.buffer_id)
}

pub async fn refresh(ws: &mut Ws, root: &std::path::Path) -> GitRefreshResult {
    send_request::<GitRefresh>(
        ws,
        &GitRefreshParams {
            repo_id: root.to_string_lossy().into(),
        },
    )
    .await
}

pub async fn checkout(
    ws: &mut Ws,
    root: &std::path::Path,
    branch: &str,
    create: bool,
) -> GitCheckoutResult {
    send_request::<GitCheckout>(
        ws,
        &GitCheckoutParams {
            repo_id: Some(root.to_string_lossy().into()),
            branch: branch.into(),
            create,
            ..Default::default()
        },
    )
    .await
}

// -------- git/commit ------------------------------------------------------------------------------

/// Isolate a fixture repo from the developer's global git config.
///
/// Repo-local config outranks global for every key that could change an outcome here, and unlike
/// `GIT_CONFIG_GLOBAL` it needs no process-environment surgery — which the tests couldn't do
/// anyway, since git runs inside the server. `core.hooksPath` matters most: without it, a global
/// hooks directory would run a developer's real `pre-commit` against these fixtures.
pub fn isolate_repo_config(repo: &git2::Repository, hooks_dir: &std::path::Path) {
    std::fs::create_dir_all(hooks_dir).unwrap();
    let mut cfg = repo.config().unwrap();
    cfg.set_str("user.name", "Test").unwrap();
    cfg.set_str("user.email", "test@example.com").unwrap();
    cfg.set_bool("commit.gpgsign", false).unwrap();
    cfg.set_str("core.hooksPath", hooks_dir.to_str().unwrap())
        .unwrap();
}

pub async fn commit(ws: &mut Ws, root: &std::path::Path, amend: bool) -> GitCommitResult {
    send_request::<GitCommit>(
        ws,
        &GitCommitParams {
            repo_id: root.to_string_lossy().into(),
            amend,
        },
    )
    .await
}

/// Send a request expecting an RPC *error*, and return the error object. `send_request` panics on
/// one, which is right for every call that should succeed and useless for the ones that shouldn't.
pub async fn send_request_expect_error<M: RpcMethod>(ws: &mut Ws, params: &M::Params) -> Value {
    let id = send_no_wait::<M>(ws, params).await;
    loop {
        let text = next_text(ws).await;
        let v: Value = serde_json::from_str(&text).unwrap();
        if v["id"] == serde_json::json!(id) {
            assert!(
                v.get("error").is_some(),
                "expected an error from {}, got {v}",
                M::NAME
            );
            return v["error"].clone();
        }
    }
}

// -------- git/push ---------------------------------------------------------------------------------

pub async fn push(ws: &mut Ws, repo: &std::path::Path) -> GitPushResult {
    send_request::<GitPush>(
        ws,
        &GitPushParams {
            repo_id: Some(repo.to_string_lossy().into()),
            buffer_id: None,
        },
    )
    .await
}

pub async fn pull(ws: &mut Ws, repo: &std::path::Path) -> GitPullResult {
    send_request::<GitPull>(
        ws,
        &GitPullParams {
            repo_id: Some(repo.to_string_lossy().into()),
            buffer_id: None,
        },
    )
    .await
}

/// Subscribe a viewport on an already-open buffer and return the window it renders.
///
/// With the inline diff **off**, which is what a client opens with. Removed lines are phantoms of
/// that view — on a patch as much as on an ordinary file — so a test that wants to see them wants
/// [`diffed_window_of`].
pub async fn window_of(ws: &mut Ws, buffer_id: u64) -> aether_protocol::viewport::Window {
    window_with_diff(ws, buffer_id, false).await
}

/// [`window_of`] with the inline diff on: the view that draws removed lines.
pub async fn diffed_window_of(ws: &mut Ws, buffer_id: u64) -> aether_protocol::viewport::Window {
    window_with_diff(ws, buffer_id, true).await
}

async fn window_with_diff(
    ws: &mut Ws,
    buffer_id: u64,
    diff_view: bool,
) -> aether_protocol::viewport::Window {
    let sub: ViewportSubscribeResult = send_request::<ViewportSubscribe>(
        ws,
        &ViewportSubscribeParams {
            view_id: view_of(buffer_id),
            cols: 80,
            rows: 40,
            overscan_rows: 0,
            scroll: ScrollPosition {
                element: 0,
                line: 0,
                sub_row: 0.0,
            },
            focus: None,
            wrap: WrapMode::None,
            continuation_marker_width: 0,
            tab_width: 4,
            diff_view,
        },
    )
    .await;
    // A subscribe loads a screen of one element; these helpers answer for the whole (small) view.
    whole_view(ws, sub.viewport_id, sub.window).await
}

/// Load every row of the view on `viewport_id`, as a client tall enough to show it all would.
pub async fn whole_view(
    ws: &mut Ws,
    viewport_id: u64,
    window: aether_protocol::viewport::Window,
) -> aether_protocol::viewport::Window {
    let total = total_rows(&window);
    if total == 0 {
        return window;
    }
    window_at(ws, viewport_id, &window, 0, total, 0)
        .await
        .window
}

pub async fn resolve_conflict(
    ws: &mut Ws,
    buffer_id: u64,
    side: ConflictSide,
) -> GitResolveConflictResult {
    send_request::<GitResolveConflict>(ws, &GitResolveConflictParams { buffer_id, side }).await
}

/// The content tree of a chrome row. Panics on a baseline row — the two are separate
/// variants precisely so a test can't confuse them.
pub fn chrome_content(row: &Element) -> &[Element] {
    match row {
        Element::Chrome { children, .. } => children,
        _ => panic!("expected a chrome node"),
    }
}

/// The literal text a chrome row draws, left to right.
pub fn chrome_text(row: &Element) -> String {
    chrome_content(row)
        .iter()
        .map(Element::text_content)
        .collect()
}

/// Every chrome node of a window's tree, in order.
pub fn chrome_nodes(window: &aether_protocol::viewport::Window) -> Vec<&Element> {
    fn walk<'a>(n: &'a Element, out: &mut Vec<&'a Element>) {
        match n {
            Element::Stack { children } => children.iter().for_each(|c| walk(c, out)),
            Element::Chrome { .. } => out.push(n),
            _ => {}
        }
    }
    let mut out = Vec::new();
    walk(&window.root, &mut out);
    out
}

// -------- view geometry, the client's way ----------------------------------------------------------
//
// The server no longer says how tall a view is or where a slice sits on screen: the tree does, and
// the client's shared row maths reads it. Tests that model a client use the same functions, so a
// disagreement between the tree and the client's reading of it fails here rather than on screen.

/// Rows the whole view occupies — chrome, one row each, and every editor's height.
pub fn total_rows(window: &aether_protocol::viewport::Window) -> u32 {
    aether_client::grid::total_rows(&window.root, &Measured::default())
}

/// The lines the first editor carrying any has loaded, as `(first, last exclusive)`.
pub fn loaded_lines(window: &aether_protocol::viewport::Window) -> (u32, u32) {
    window
        .root
        .editors()
        .into_iter()
        .find_map(|n| match n {
            Element::Editor { lines, .. } if !lines.is_empty() => Some((
                lines[0].logical_line,
                lines[lines.len() - 1].logical_line + 1,
            )),
            _ => None,
        })
        .unwrap_or((0, 0))
}

/// The absolute row the first loaded slice starts on — the element's start plus the slice's row
/// within it.
pub fn first_loaded_row(window: &aether_protocol::viewport::Window) -> u32 {
    aether_client::grid::painted_rows(window, &Measured::default())
        .into_iter()
        .find_map(|(at, item)| match item {
            aether_client::grid::PaintedRow::Chrome(_) => None,
            _ => Some(at.get()),
        })
        .unwrap_or(0)
}

/// How many rows the loaded slices paint, chrome included — what a client can put on screen.
pub fn painted_rows(window: &aether_protocol::viewport::Window) -> u32 {
    aether_client::grid::painted_rows(window, &Measured::default()).len() as u32
}

/// Load the slices a client showing rows `top..top+rows` (with `overscan` each side) would ask for,
/// exactly as the real client computes them from the tree it holds.
pub async fn window_at(
    ws: &mut Ws,
    viewport_id: u64,
    current: &aether_protocol::viewport::Window,
    top: u32,
    rows: u32,
    overscan: u32,
) -> ViewportWindowResult {
    let slices = aether_client::grid::slices_for(
        &current.root,
        VisualRow(top),
        rows,
        overscan,
        &Measured::default(),
    );
    let anchor = aether_client::grid::anchor_at(current, VisualRow(top), &Measured::default());
    send_request::<ViewportWindow>(
        ws,
        &ViewportWindowParams {
            viewport_id,
            anchor,
            slices,
        },
    )
    .await
}

/// [`window_at`] for a single-element, unwrapped view, where row `top` of the view is line `top`:
/// one slice of element 0 from that row.
pub async fn window_from_row(
    ws: &mut Ws,
    viewport_id: u64,
    top: u32,
    rows: u32,
) -> ViewportWindowResult {
    send_request::<ViewportWindow>(
        ws,
        &ViewportWindowParams {
            viewport_id,
            anchor: ScrollPosition {
                element: 0,
                line: top,
                sub_row: 0.0,
            },
            slices: vec![SliceRequest {
                element: 0,
                from_row: ElementRow(top),
                rows,
            }],
        },
    )
    .await
}
